// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: struct sequenceCommandLine_ { int commandType;						// Specifies the type of command client_textmessage_t clientMessage;		// Text HUD message struct char* speakerName;						// Targetname of speaking entity char* listenerName;						// Tar...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct sequenceCommandLine_s
{
    /// <summary>
    /// Specifies the type of command
    /// </summary>
    /// <remarks>
    /// Original: int commandType;						// Specifies the type of command
    /// </remarks>
    public int commandType;
    /// <summary>
    /// Text HUD message struct
    /// </summary>
    /// <remarks>
    /// Original: client_textmessage_t clientMessage;		// Text HUD message struct
    /// </remarks>
    public client_textmessage_t clientMessage;
    /// <summary>
    /// Targetname of speaking entity
    /// </summary>
    /// <remarks>
    /// Original: char* speakerName;						// Targetname of speaking entity
    /// </remarks>
    public NChar* speakerName;
    /// <summary>
    /// Targetname of entity being spoken to
    /// </summary>
    /// <remarks>
    /// Original: char* listenerName;						// Targetname of entity being spoken to
    /// </remarks>
    public NChar* listenerName;
    /// <summary>
    /// Name of sound file to play
    /// </summary>
    /// <remarks>
    /// Original: char* soundFileName;					// Name of sound file to play
    /// </remarks>
    public NChar* soundFileName;
    /// <summary>
    /// Name of sentences.txt to play
    /// </summary>
    /// <remarks>
    /// Original: char* sentenceName;						// Name of sentences.txt to play
    /// </remarks>
    public NChar* sentenceName;
    /// <summary>
    /// List of targetnames to fire
    /// </summary>
    /// <remarks>
    /// Original: char* fireTargetNames;					// List of targetnames to fire
    /// </remarks>
    public NChar* fireTargetNames;
    /// <summary>
    /// List of targetnames to remove
    /// </summary>
    /// <remarks>
    /// Original: char* killTargetNames;					// List of targetnames to remove
    /// </remarks>
    public NChar* killTargetNames;
    /// <summary>
    /// Seconds 'till next command
    /// </summary>
    /// <remarks>
    /// Original: float delay;							// Seconds 'till next command
    /// </remarks>
    public float delay;
    /// <summary>
    /// If nonzero, reset execution pointer to top of block (N times, -1 = infinite)
    /// </summary>
    /// <remarks>
    /// Original: int repeatCount;						// If nonzero, reset execution pointer to top of block (N times, -1 = infinite)
    /// </remarks>
    public int repeatCount;
    /// <summary>
    /// Display channel on which text message is sent
    /// </summary>
    /// <remarks>
    /// Original: int textChannel;						// Display channel on which text message is sent
    /// </remarks>
    public int textChannel;
    /// <summary>
    /// Bit field to specify what clientmessage fields are valid
    /// </summary>
    /// <remarks>
    /// Original: int modifierBitField;					// Bit field to specify what clientmessage fields are valid
    /// </remarks>
    public int modifierBitField;
    /// <summary>
    /// Next command (linked list)
    /// </summary>
    /// <remarks>
    /// Original: sequenceCommandLine_s* nextCommandLine; // Next command (linked list)
    /// </remarks>
    public sequenceCommandLine_s* nextCommandLine;
}

