// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: struct { byte valid; byte total; } num;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct __Anonymous24457708
{
    /// <remarks>
    /// Original: byte valid;
    /// </remarks>
    public byte valid;
    /// <remarks>
    /// Original: byte total;
    /// </remarks>
    public byte total;
}

