// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// sequence descriptions
/// </summary>
/// <remarks>
/// Original: typedef struct { char label[32]; // sequence label float fps; // frames per second int flags; // looping/non-looping flags int activity; int actweight; int numevents; int eventindex; int numframes; // number of frames per sequence int nu...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct mstudioseqdesc_t
{
    /// <summary>
    /// sequence label
    /// </summary>
    /// <remarks>
    /// Original: char label[32]; // sequence label
    /// </remarks>
    public InlineArray32<NChar> label;
    /// <summary>
    /// frames per second
    /// </summary>
    /// <remarks>
    /// Original: float fps; // frames per second
    /// </remarks>
    public float fps;
    /// <summary>
    /// looping/non-looping flags
    /// </summary>
    /// <remarks>
    /// Original: int flags; // looping/non-looping flags
    /// </remarks>
    public int flags;
    /// <remarks>
    /// Original: int activity;
    /// </remarks>
    public int activity;
    /// <remarks>
    /// Original: int actweight;
    /// </remarks>
    public int actweight;
    /// <remarks>
    /// Original: int numevents;
    /// </remarks>
    public int numevents;
    /// <remarks>
    /// Original: int eventindex;
    /// </remarks>
    public int eventindex;
    /// <summary>
    /// number of frames per sequence
    /// </summary>
    /// <remarks>
    /// Original: int numframes; // number of frames per sequence
    /// </remarks>
    public int numframes;
    /// <summary>
    /// number of foot pivots
    /// </summary>
    /// <remarks>
    /// Original: int numpivots; // number of foot pivots
    /// </remarks>
    public int numpivots;
    /// <remarks>
    /// Original: int pivotindex;
    /// </remarks>
    public int pivotindex;
    /// <remarks>
    /// Original: int motiontype;
    /// </remarks>
    public int motiontype;
    /// <remarks>
    /// Original: int motionbone;
    /// </remarks>
    public int motionbone;
    /// <remarks>
    /// Original: Vector linearmovement;
    /// </remarks>
    public Vector3 linearmovement;
    /// <remarks>
    /// Original: int automoveposindex;
    /// </remarks>
    public int automoveposindex;
    /// <remarks>
    /// Original: int automoveangleindex;
    /// </remarks>
    public int automoveangleindex;
    /// <summary>
    /// per sequence bounding box
    /// </summary>
    /// <remarks>
    /// Original: Vector bbmin; // per sequence bounding box
    /// </remarks>
    public Vector3 bbmin;
    /// <remarks>
    /// Original: Vector bbmax;
    /// </remarks>
    public Vector3 bbmax;
    /// <remarks>
    /// Original: int numblends;
    /// </remarks>
    public int numblends;
    /// <summary>
    /// mstudioanim_t pointer relative to start of sequence group data
    /// </summary>
    /// <remarks>
    /// Original: int animindex; // mstudioanim_t pointer relative to start of sequence group data
    /// </remarks>
    public int animindex;
    /// <summary>
    /// X, Y, Z, XR, YR, ZR
    /// </summary>
    /// <remarks>
    /// Original: int blendtype[2];	 // X, Y, Z, XR, YR, ZR
    /// </remarks>
    public InlineArray2<int> blendtype;
    /// <summary>
    /// starting value
    /// </summary>
    /// <remarks>
    /// Original: float blendstart[2]; // starting value
    /// </remarks>
    public InlineArray2<float> blendstart;
    /// <summary>
    /// ending value
    /// </summary>
    /// <remarks>
    /// Original: float blendend[2];	 // ending value
    /// </remarks>
    public InlineArray2<float> blendend;
    /// <remarks>
    /// Original: int blendparent;
    /// </remarks>
    public int blendparent;
    /// <summary>
    /// sequence group for demand loading
    /// </summary>
    /// <remarks>
    /// Original: int seqgroup; // sequence group for demand loading
    /// </remarks>
    public int seqgroup;
    /// <summary>
    /// transition node at entry
    /// </summary>
    /// <remarks>
    /// Original: int entrynode; // transition node at entry
    /// </remarks>
    public int entrynode;
    /// <summary>
    /// transition node at exit
    /// </summary>
    /// <remarks>
    /// Original: int exitnode;  // transition node at exit
    /// </remarks>
    public int exitnode;
    /// <summary>
    /// transition rules
    /// </summary>
    /// <remarks>
    /// Original: int nodeflags; // transition rules
    /// </remarks>
    public int nodeflags;
    /// <summary>
    /// auto advancing sequences
    /// </summary>
    /// <remarks>
    /// Original: int nextseq; // auto advancing sequences
    /// </remarks>
    public int nextseq;
}

