// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct { unsigned short offset[6]; } mstudioanim_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct mstudioanim_t
{
    /// <remarks>
    /// Original: unsigned short offset[6];
    /// </remarks>
    public InlineArray6<ushort> offset;
}

