// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// meshes
/// </summary>
/// <remarks>
/// Original: typedef struct { int numtris; int triindex; int skinref; int numnorms;  // per mesh normals int normindex; // normal Vector } mstudiomesh_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct mstudiomesh_t
{
    /// <remarks>
    /// Original: int numtris;
    /// </remarks>
    public int numtris;
    /// <remarks>
    /// Original: int triindex;
    /// </remarks>
    public int triindex;
    /// <remarks>
    /// Original: int skinref;
    /// </remarks>
    public int skinref;
    /// <summary>
    /// per mesh normals
    /// </summary>
    /// <remarks>
    /// Original: int numnorms;  // per mesh normals
    /// </remarks>
    public int numnorms;
    /// <summary>
    /// normal Vector
    /// </summary>
    /// <remarks>
    /// Original: int normindex; // normal Vector
    /// </remarks>
    public int normindex;
}

