// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// bone controllers
/// </summary>
/// <remarks>
/// Original: typedef struct { int bone; // -1 == 0 int type; // X, Y, Z, XR, YR, ZR, M float start; float end; int rest;  // byte index value at rest int index; // 0-3 user set controller, 4 mouth } mstudiobonecontroller_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct mstudiobonecontroller_t
{
    /// <summary>
    /// -1 == 0
    /// </summary>
    /// <remarks>
    /// Original: int bone; // -1 == 0
    /// </remarks>
    public int bone;
    /// <summary>
    /// X, Y, Z, XR, YR, ZR, M
    /// </summary>
    /// <remarks>
    /// Original: int type; // X, Y, Z, XR, YR, ZR, M
    /// </remarks>
    public int type;
    /// <remarks>
    /// Original: float start;
    /// </remarks>
    public float start;
    /// <remarks>
    /// Original: float end;
    /// </remarks>
    public float end;
    /// <summary>
    /// byte index value at rest
    /// </summary>
    /// <remarks>
    /// Original: int rest;  // byte index value at rest
    /// </remarks>
    public int rest;
    /// <summary>
    /// 0-3 user set controller, 4 mouth
    /// </summary>
    /// <remarks>
    /// Original: int index; // 0-3 user set controller, 4 mouth
    /// </remarks>
    public int index;
}

