// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// attachment
/// </summary>
/// <remarks>
/// Original: typedef struct { char name[32]; int type; int bone; Vector org; // attachment point Vector vectors[3]; } mstudioattachment_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct mstudioattachment_t
{
    /// <remarks>
    /// Original: char name[32];
    /// </remarks>
    public InlineArray32<NChar> name;
    /// <remarks>
    /// Original: int type;
    /// </remarks>
    public int type;
    /// <remarks>
    /// Original: int bone;
    /// </remarks>
    public int bone;
    /// <summary>
    /// attachment point
    /// </summary>
    /// <remarks>
    /// Original: Vector org; // attachment point
    /// </remarks>
    public Vector3 org;
    /// <remarks>
    /// Original: Vector vectors[3];
    /// </remarks>
    public InlineArray3<Vector3> vectors;
}

