// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// body part index
/// </summary>
/// <remarks>
/// Original: typedef struct { char name[64]; int nummodels; int base; int modelindex; // index into models array } mstudiobodyparts_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct mstudiobodyparts_t
{
    /// <remarks>
    /// Original: char name[64];
    /// </remarks>
    public InlineArray64<NChar> name;
    /// <remarks>
    /// Original: int nummodels;
    /// </remarks>
    public int nummodels;
    /// <remarks>
    /// Original: int base;
    /// </remarks>
    public int @base;
    /// <summary>
    /// index into models array
    /// </summary>
    /// <remarks>
    /// Original: int modelindex; // index into models array
    /// </remarks>
    public int modelindex;
}

