// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// demand loaded sequence groups
/// </summary>
/// <remarks>
/// Original: typedef struct { char label[32]; // textual name char name[64];	// file name int32 unused1;	// was "cache"  - index pointer int unused2;	// was "data" -  hack for group 0 } mstudioseqgroup_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct mstudioseqgroup_t
{
    /// <summary>
    /// textual name
    /// </summary>
    /// <remarks>
    /// Original: char label[32]; // textual name
    /// </remarks>
    public InlineArray32<NChar> label;
    /// <summary>
    /// file name
    /// </summary>
    /// <remarks>
    /// Original: char name[64];	// file name
    /// </remarks>
    public InlineArray64<NChar> name;
    /// <summary>
    /// was "cache"  - index pointer
    /// </summary>
    /// <remarks>
    /// Original: int32 unused1;	// was "cache"  - index pointer
    /// </remarks>
    public int unused1;
    /// <summary>
    /// was "data" -  hack for group 0
    /// </summary>
    /// <remarks>
    /// Original: int unused2;	// was "data" -  hack for group 0
    /// </remarks>
    public int unused2;
}

