// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// skin info
/// </summary>
/// <remarks>
/// Original: typedef struct { char name[64]; int flags; int width; int height; int index; } mstudiotexture_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct mstudiotexture_t
{
    /// <remarks>
    /// Original: char name[64];
    /// </remarks>
    public InlineArray64<NChar> name;
    /// <remarks>
    /// Original: int flags;
    /// </remarks>
    public int flags;
    /// <remarks>
    /// Original: int width;
    /// </remarks>
    public int width;
    /// <remarks>
    /// Original: int height;
    /// </remarks>
    public int height;
    /// <remarks>
    /// Original: int index;
    /// </remarks>
    public int index;
}

