// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// intersection boxes
/// </summary>
/// <remarks>
/// Original: typedef struct { int bone; int group;	  // intersection group Vector bbmin; // bounding box Vector bbmax; } mstudiobbox_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct mstudiobbox_t
{
    /// <remarks>
    /// Original: int bone;
    /// </remarks>
    public int bone;
    /// <summary>
    /// intersection group
    /// </summary>
    /// <remarks>
    /// Original: int group;	  // intersection group
    /// </remarks>
    public int group;
    /// <summary>
    /// bounding box
    /// </summary>
    /// <remarks>
    /// Original: Vector bbmin; // bounding box
    /// </remarks>
    public Vector3 bbmin;
    /// <remarks>
    /// Original: Vector bbmax;
    /// </remarks>
    public Vector3 bbmax;
}

