// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// studio models
/// </summary>
/// <remarks>
/// Original: typedef struct { char name[64]; int type; float boundingradius; int nummesh; int meshindex; int numverts;	   // number of unique vertices int vertinfoindex; // vertex bone info int vertindex;	   // vertex Vector int numnorms;	   // numbe...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct mstudiomodel_t
{
    /// <remarks>
    /// Original: char name[64];
    /// </remarks>
    public InlineArray64<NChar> name;
    /// <remarks>
    /// Original: int type;
    /// </remarks>
    public int type;
    /// <remarks>
    /// Original: float boundingradius;
    /// </remarks>
    public float boundingradius;
    /// <remarks>
    /// Original: int nummesh;
    /// </remarks>
    public int nummesh;
    /// <remarks>
    /// Original: int meshindex;
    /// </remarks>
    public int meshindex;
    /// <summary>
    /// number of unique vertices
    /// </summary>
    /// <remarks>
    /// Original: int numverts;	   // number of unique vertices
    /// </remarks>
    public int numverts;
    /// <summary>
    /// vertex bone info
    /// </summary>
    /// <remarks>
    /// Original: int vertinfoindex; // vertex bone info
    /// </remarks>
    public int vertinfoindex;
    /// <summary>
    /// vertex Vector
    /// </summary>
    /// <remarks>
    /// Original: int vertindex;	   // vertex Vector
    /// </remarks>
    public int vertindex;
    /// <summary>
    /// number of unique surface normals
    /// </summary>
    /// <remarks>
    /// Original: int numnorms;	   // number of unique surface normals
    /// </remarks>
    public int numnorms;
    /// <summary>
    /// normal bone info
    /// </summary>
    /// <remarks>
    /// Original: int norminfoindex; // normal bone info
    /// </remarks>
    public int norminfoindex;
    /// <summary>
    /// normal Vector
    /// </summary>
    /// <remarks>
    /// Original: int normindex;	   // normal Vector
    /// </remarks>
    public int normindex;
    /// <summary>
    /// deformation groups
    /// </summary>
    /// <remarks>
    /// Original: int numgroups; // deformation groups
    /// </remarks>
    public int numgroups;
    /// <remarks>
    /// Original: int groupindex;
    /// </remarks>
    public int groupindex;
}

