// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// animation frames
/// </summary>
/// <remarks>
/// Original: typedef union { struct { byte valid; byte total; } num; short value; } mstudioanimvalue_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct mstudioanimvalue_t_num_t
{
    public byte valid;
    public byte total;
}

[StructLayout(LayoutKind.Explicit)]
public struct mstudioanimvalue_t
{
    [FieldOffset(0)] public mstudioanimvalue_t_num_t num;
    [FieldOffset(0)] public short value;
}

