// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// pivots
/// </summary>
/// <remarks>
/// Original: typedef struct { Vector org; // pivot point int start; int end; } mstudiopivot_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct mstudiopivot_t
{
    /// <summary>
    /// pivot point
    /// </summary>
    /// <remarks>
    /// Original: Vector org; // pivot point
    /// </remarks>
    public Vector3 org;
    /// <remarks>
    /// Original: int start;
    /// </remarks>
    public int start;
    /// <remarks>
    /// Original: int end;
    /// </remarks>
    public int end;
}

