// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// bones
/// </summary>
/// <remarks>
/// Original: typedef struct { char name[32];		   // bone name for symbolic links int parent;			   // parent bone int flags;			   // ?? int bonecontroller[6]; // bone controller index, -1 == none float value[6];		   // default DoF values float scale[6...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct mstudiobone_t
{
    /// <summary>
    /// bone name for symbolic links
    /// </summary>
    /// <remarks>
    /// Original: char name[32];		   // bone name for symbolic links
    /// </remarks>
    public InlineArray32<NChar> name;
    /// <summary>
    /// parent bone
    /// </summary>
    /// <remarks>
    /// Original: int parent;			   // parent bone
    /// </remarks>
    public int parent;
    /// <summary>
    /// ??
    /// </summary>
    /// <remarks>
    /// Original: int flags;			   // ??
    /// </remarks>
    public int flags;
    /// <summary>
    /// bone controller index, -1 == none
    /// </summary>
    /// <remarks>
    /// Original: int bonecontroller[6]; // bone controller index, -1 == none
    /// </remarks>
    public InlineArray6<int> bonecontroller;
    /// <summary>
    /// default DoF values
    /// </summary>
    /// <remarks>
    /// Original: float value[6];		   // default DoF values
    /// </remarks>
    public InlineArray6<float> value;
    /// <summary>
    /// scale for delta DoF values
    /// </summary>
    /// <remarks>
    /// Original: float scale[6];		   // scale for delta DoF values
    /// </remarks>
    public InlineArray6<float> scale;
}

