// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct { int id; int version; char name[64]; int length; Vector eyeposition; // ideal eye position Vector min;			// ideal movement hull size Vector max; Vector bbmin; // clipping bounding box Vector bbmax; int flags; int numbones...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct studiohdr_t
{
    /// <remarks>
    /// Original: int id;
    /// </remarks>
    public int id;
    /// <remarks>
    /// Original: int version;
    /// </remarks>
    public int version;
    /// <remarks>
    /// Original: char name[64];
    /// </remarks>
    public InlineArray64<NChar> name;
    /// <remarks>
    /// Original: int length;
    /// </remarks>
    public int length;
    /// <summary>
    /// ideal eye position
    /// </summary>
    /// <remarks>
    /// Original: Vector eyeposition; // ideal eye position
    /// </remarks>
    public Vector3 eyeposition;
    /// <summary>
    /// ideal movement hull size
    /// </summary>
    /// <remarks>
    /// Original: Vector min;			// ideal movement hull size
    /// </remarks>
    public Vector3 min;
    /// <remarks>
    /// Original: Vector max;
    /// </remarks>
    public Vector3 max;
    /// <summary>
    /// clipping bounding box
    /// </summary>
    /// <remarks>
    /// Original: Vector bbmin; // clipping bounding box
    /// </remarks>
    public Vector3 bbmin;
    /// <remarks>
    /// Original: Vector bbmax;
    /// </remarks>
    public Vector3 bbmax;
    /// <remarks>
    /// Original: int flags;
    /// </remarks>
    public int flags;
    /// <summary>
    /// bones
    /// </summary>
    /// <remarks>
    /// Original: int numbones; // bones
    /// </remarks>
    public int numbones;
    /// <remarks>
    /// Original: int boneindex;
    /// </remarks>
    public int boneindex;
    /// <summary>
    /// bone controllers
    /// </summary>
    /// <remarks>
    /// Original: int numbonecontrollers; // bone controllers
    /// </remarks>
    public int numbonecontrollers;
    /// <remarks>
    /// Original: int bonecontrollerindex;
    /// </remarks>
    public int bonecontrollerindex;
    /// <summary>
    /// complex bounding boxes
    /// </summary>
    /// <remarks>
    /// Original: int numhitboxes; // complex bounding boxes
    /// </remarks>
    public int numhitboxes;
    /// <remarks>
    /// Original: int hitboxindex;
    /// </remarks>
    public int hitboxindex;
    /// <summary>
    /// animation sequences
    /// </summary>
    /// <remarks>
    /// Original: int numseq; // animation sequences
    /// </remarks>
    public int numseq;
    /// <remarks>
    /// Original: int seqindex;
    /// </remarks>
    public int seqindex;
    /// <summary>
    /// demand loaded sequences
    /// </summary>
    /// <remarks>
    /// Original: int numseqgroups; // demand loaded sequences
    /// </remarks>
    public int numseqgroups;
    /// <remarks>
    /// Original: int seqgroupindex;
    /// </remarks>
    public int seqgroupindex;
    /// <summary>
    /// raw textures
    /// </summary>
    /// <remarks>
    /// Original: int numtextures; // raw textures
    /// </remarks>
    public int numtextures;
    /// <remarks>
    /// Original: int textureindex;
    /// </remarks>
    public int textureindex;
    /// <remarks>
    /// Original: int texturedataindex;
    /// </remarks>
    public int texturedataindex;
    /// <summary>
    /// replaceable textures
    /// </summary>
    /// <remarks>
    /// Original: int numskinref; // replaceable textures
    /// </remarks>
    public int numskinref;
    /// <remarks>
    /// Original: int numskinfamilies;
    /// </remarks>
    public int numskinfamilies;
    /// <remarks>
    /// Original: int skinindex;
    /// </remarks>
    public int skinindex;
    /// <remarks>
    /// Original: int numbodyparts;
    /// </remarks>
    public int numbodyparts;
    /// <remarks>
    /// Original: int bodypartindex;
    /// </remarks>
    public int bodypartindex;
    /// <summary>
    /// queryable attachable points
    /// </summary>
    /// <remarks>
    /// Original: int numattachments; // queryable attachable points
    /// </remarks>
    public int numattachments;
    /// <remarks>
    /// Original: int attachmentindex;
    /// </remarks>
    public int attachmentindex;
    /// <remarks>
    /// Original: int soundtable;
    /// </remarks>
    public int soundtable;
    /// <remarks>
    /// Original: int soundindex;
    /// </remarks>
    public int soundindex;
    /// <remarks>
    /// Original: int soundgroups;
    /// </remarks>
    public int soundgroups;
    /// <remarks>
    /// Original: int soundgroupindex;
    /// </remarks>
    public int soundgroupindex;
    /// <summary>
    /// animation node to animation node transition graph
    /// </summary>
    /// <remarks>
    /// Original: int numtransitions; // animation node to animation node transition graph
    /// </remarks>
    public int numtransitions;
    /// <remarks>
    /// Original: int transitionindex;
    /// </remarks>
    public int transitionindex;
}

