// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: struct beam_s { BEAM* next; int type; int flags; Vector source; Vector target; Vector delta; float t; // 0 .. 1 over lifetime of beam float freq; float die; float width; float amplitude; float r, g, b; float brightness; float speed; floa...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct BEAM
{
    /// <remarks>
    /// Original: BEAM* next;
    /// </remarks>
    public BEAM* next;
    /// <remarks>
    /// Original: int type;
    /// </remarks>
    public int type;
    /// <remarks>
    /// Original: int flags;
    /// </remarks>
    public int flags;
    /// <remarks>
    /// Original: Vector source;
    /// </remarks>
    public Vector3 source;
    /// <remarks>
    /// Original: Vector target;
    /// </remarks>
    public Vector3 target;
    /// <remarks>
    /// Original: Vector delta;
    /// </remarks>
    public Vector3 delta;
    /// <summary>
    /// 0 .. 1 over lifetime of beam
    /// </summary>
    /// <remarks>
    /// Original: float t; // 0 .. 1 over lifetime of beam
    /// </remarks>
    public float t;
    /// <remarks>
    /// Original: float freq;
    /// </remarks>
    public float freq;
    /// <remarks>
    /// Original: float die;
    /// </remarks>
    public float die;
    /// <remarks>
    /// Original: float width;
    /// </remarks>
    public float width;
    /// <remarks>
    /// Original: float amplitude;
    /// </remarks>
    public float amplitude;
    /// <remarks>
    /// Original: float r, g, b;
    /// </remarks>
    public float r;
    /// <remarks>
    /// Original: float r, g, b;
    /// </remarks>
    public float g;
    /// <remarks>
    /// Original: float r, g, b;
    /// </remarks>
    public float b;
    /// <remarks>
    /// Original: float brightness;
    /// </remarks>
    public float brightness;
    /// <remarks>
    /// Original: float speed;
    /// </remarks>
    public float speed;
    /// <remarks>
    /// Original: float frameRate;
    /// </remarks>
    public float frameRate;
    /// <remarks>
    /// Original: float frame;
    /// </remarks>
    public float frame;
    /// <remarks>
    /// Original: int segments;
    /// </remarks>
    public int segments;
    /// <remarks>
    /// Original: int startEntity;
    /// </remarks>
    public int startEntity;
    /// <remarks>
    /// Original: int endEntity;
    /// </remarks>
    public int endEntity;
    /// <remarks>
    /// Original: int modelIndex;
    /// </remarks>
    public int modelIndex;
    /// <remarks>
    /// Original: int frameCount;
    /// </remarks>
    public int frameCount;
    /// <remarks>
    /// Original: struct model_s* pFollowModel;
    /// </remarks>
    public model_t* pFollowModel;
    /// <remarks>
    /// Original: struct particle_s* particles;
    /// </remarks>
    public particle_t* particles;
}

