// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct cmdalias_s { struct cmdalias_s* next; char name[MAX_ALIAS_NAME]; char* value; } cmdalias_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct cmdalias_t
{
    /// <remarks>
    /// Original: struct cmdalias_s* next;
    /// </remarks>
    public cmdalias_t* next;
    /// <remarks>
    /// Original: char name[MAX_ALIAS_NAME];
    /// </remarks>
    public InlineArray32<NChar> name;
    /// <remarks>
    /// Original: char* value;
    /// </remarks>
    public NChar* value;
}

