// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct model_s { char name[MAX_MODEL_NAME]; qboolean needload; // bmodels and sprites don't cache normally modtype_t type; int numframes; synctype_t synctype; int flags; // // volume occupied by the model // Vector mins, maxs; fl...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct model_t
{
    /// <remarks>
    /// Original: char name[MAX_MODEL_NAME];
    /// </remarks>
    public InlineArray64<NChar> name;
    /// <summary>
    /// bmodels and sprites don't cache normally
    /// </summary>
    /// <remarks>
    /// Original: qboolean needload; // bmodels and sprites don't cache normally
    /// </remarks>
    public qboolean needload;
    /// <remarks>
    /// Original: modtype_t type;
    /// </remarks>
    public modtype_t type;
    /// <remarks>
    /// Original: int numframes;
    /// </remarks>
    public int numframes;
    /// <remarks>
    /// Original: synctype_t synctype;
    /// </remarks>
    public synctype_t synctype;
    /// <remarks>
    /// Original: int flags;
    /// </remarks>
    public int flags;
    /// <summary>
    /// volume occupied by the model
    /// </summary>
    /// <remarks>
    /// Original: Vector mins, maxs;
    /// </remarks>
    public Vector3 mins;
    /// <summary>
    /// volume occupied by the model
    /// </summary>
    /// <remarks>
    /// Original: Vector mins, maxs;
    /// </remarks>
    public Vector3 maxs;
    /// <remarks>
    /// Original: float radius;
    /// </remarks>
    public float radius;
    /// <summary>
    /// brush model
    /// </summary>
    /// <remarks>
    /// Original: int firstmodelsurface, nummodelsurfaces;
    /// </remarks>
    public int firstmodelsurface;
    /// <summary>
    /// brush model
    /// </summary>
    /// <remarks>
    /// Original: int firstmodelsurface, nummodelsurfaces;
    /// </remarks>
    public int nummodelsurfaces;
    /// <remarks>
    /// Original: int numsubmodels;
    /// </remarks>
    public int numsubmodels;
    /// <remarks>
    /// Original: dmodel_t* submodels;
    /// </remarks>
    public dmodel_t* submodels;
    /// <remarks>
    /// Original: int numplanes;
    /// </remarks>
    public int numplanes;
    /// <remarks>
    /// Original: mplane_t* planes;
    /// </remarks>
    public mplane_t* planes;
    /// <summary>
    /// number of visible leafs, not counting 0
    /// </summary>
    /// <remarks>
    /// Original: int numleafs; // number of visible leafs, not counting 0
    /// </remarks>
    public int numleafs;
    /// <remarks>
    /// Original: struct mleaf_s* leafs;
    /// </remarks>
    public mleaf_t* leafs;
    /// <remarks>
    /// Original: int numvertexes;
    /// </remarks>
    public int numvertexes;
    /// <remarks>
    /// Original: mvertex_t* vertexes;
    /// </remarks>
    public mvertex_t* vertexes;
    /// <remarks>
    /// Original: int numedges;
    /// </remarks>
    public int numedges;
    /// <remarks>
    /// Original: medge_t* edges;
    /// </remarks>
    public medge_t* edges;
    /// <remarks>
    /// Original: int numnodes;
    /// </remarks>
    public int numnodes;
    /// <remarks>
    /// Original: mnode_t* nodes;
    /// </remarks>
    public mnode_t* nodes;
    /// <remarks>
    /// Original: int numtexinfo;
    /// </remarks>
    public int numtexinfo;
    /// <remarks>
    /// Original: mtexinfo_t* texinfo;
    /// </remarks>
    public mtexinfo_t* texinfo;
    /// <remarks>
    /// Original: int numsurfaces;
    /// </remarks>
    public int numsurfaces;
    /// <remarks>
    /// Original: msurface_t* surfaces;
    /// </remarks>
    public msurface_t* surfaces;
    /// <remarks>
    /// Original: int numsurfedges;
    /// </remarks>
    public int numsurfedges;
    /// <remarks>
    /// Original: int* surfedges;
    /// </remarks>
    public int* surfedges;
    /// <remarks>
    /// Original: int numclipnodes;
    /// </remarks>
    public int numclipnodes;
    /// <remarks>
    /// Original: dclipnode_t* clipnodes;
    /// </remarks>
    public dclipnode_t* clipnodes;
    /// <remarks>
    /// Original: int nummarksurfaces;
    /// </remarks>
    public int nummarksurfaces;
    /// <remarks>
    /// Original: msurface_t** marksurfaces;
    /// </remarks>
    public msurface_t** marksurfaces;
    /// <remarks>
    /// Original: hull_t hulls[MAX_MAP_HULLS];
    /// </remarks>
    public InlineArray4<hull_t> hulls;
    /// <remarks>
    /// Original: int numtextures;
    /// </remarks>
    public int numtextures;
    /// <remarks>
    /// Original: texture_t** textures;
    /// </remarks>
    public texture_t** textures;
    /// <remarks>
    /// Original: byte* visdata;
    /// </remarks>
    public byte* visdata;
    /// <remarks>
    /// Original: color24* lightdata;
    /// </remarks>
    public color24* lightdata;
    /// <remarks>
    /// Original: char* entities;
    /// </remarks>
    public NChar* entities;
    /// <summary>
    /// only access through Mod_Extradata
    /// </summary>
    /// <remarks>
    /// Original: cache_user_t cache; // only access through Mod_Extradata
    /// </remarks>
    public cache_user_t cache;
}

