// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: struct msurface_s { int visframe; // should be drawn when node is crossed int dlightframe; // last frame the surface was checked by an animated light int dlightbits;	 // dynamically generated. Indicates if the surface illumination // is ...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct msurface_t
{
    /// <summary>
    /// should be drawn when node is crossed
    /// </summary>
    /// <remarks>
    /// Original: int visframe; // should be drawn when node is crossed
    /// </remarks>
    public int visframe;
    /// <summary>
    /// last frame the surface was checked by an animated light
    /// </summary>
    /// <remarks>
    /// Original: int dlightframe; // last frame the surface was checked by an animated light
    /// </remarks>
    public int dlightframe;
    /// <summary>
    /// dynamically generated. Indicates if the surface illumination
    /// </summary>
    /// <remarks>
    /// Original: int dlightbits;	 // dynamically generated. Indicates if the surface illumination
    /// </remarks>
    public int dlightbits;
    /// <summary>
    /// pointer to shared plane
    /// </summary>
    /// <remarks>
    /// Original: mplane_t* plane; // pointer to shared plane
    /// </remarks>
    public mplane_t* plane;
    /// <summary>
    /// see SURF_ #defines
    /// </summary>
    /// <remarks>
    /// Original: int flags;		 // see SURF_ #defines
    /// </remarks>
    public int flags;
    /// <summary>
    /// look up in model-&gt;surfedges[], negative numbers
    /// </summary>
    /// <remarks>
    /// Original: int firstedge; // look up in model-&gt;surfedges[], negative numbers
    /// </remarks>
    public int firstedge;
    /// <summary>
    /// are backwards edges
    /// </summary>
    /// <remarks>
    /// Original: int numedges;  // are backwards edges
    /// </remarks>
    public int numedges;
    /// <summary>
    /// surface generation data
    /// </summary>
    /// <remarks>
    /// Original: struct surfcache_s* cachespots[MIPLEVELS];
    /// </remarks>
    public InlineArray4<surfcache_s_ptr> cachespots;
    /// <summary>
    /// smallest s/t position on the surface.
    /// </summary>
    /// <remarks>
    /// Original: short texturemins[2]; // smallest s/t position on the surface.
    /// </remarks>
    public InlineArray2<short> texturemins;
    /// <summary>
    /// ?? s/t texture size, 1..256 for all non-sky surfaces
    /// </summary>
    /// <remarks>
    /// Original: short extents[2];	  // ?? s/t texture size, 1..256 for all non-sky surfaces
    /// </remarks>
    public InlineArray2<short> extents;
    /// <remarks>
    /// Original: mtexinfo_t* texinfo;
    /// </remarks>
    public mtexinfo_t* texinfo;
    /// <summary>
    /// index into d_lightstylevalue[] for animated lights
    /// </summary>
    /// <remarks>
    /// Original: byte styles[MAXLIGHTMAPS]; // index into d_lightstylevalue[] for animated lights
    /// </remarks>
    public InlineArray4<byte> styles;
    /// <summary>
    /// no one surface can be effected by more than 4
    /// animated lights.
    /// </summary>
    /// <remarks>
    /// Original: color24* samples;
    /// </remarks>
    public color24* samples;
    /// <remarks>
    /// Original: decal_t* pdecals;
    /// </remarks>
    public decal_t* pdecals;
}

