// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct texture_s { char name[16]; unsigned width, height; int anim_total;					   // total tenths in sequence ( 0 = no) int anim_min, anim_max;			   // time for this frame min &lt;=time&lt; max struct texture_s* anim_next;	   // in the ...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct texture_t
{
    /// <remarks>
    /// Original: char name[16];
    /// </remarks>
    public InlineArray16<NChar> name;
    /// <remarks>
    /// Original: unsigned width, height;
    /// </remarks>
    public uint width;
    /// <remarks>
    /// Original: unsigned width, height;
    /// </remarks>
    public uint height;
    /// <summary>
    /// total tenths in sequence ( 0 = no)
    /// </summary>
    /// <remarks>
    /// Original: int anim_total;					   // total tenths in sequence ( 0 = no)
    /// </remarks>
    public int anim_total;
    /// <summary>
    /// time for this frame min
    /// &lt;
    /// =time
    /// &lt;
    /// max
    /// </summary>
    /// <remarks>
    /// Original: int anim_min, anim_max;			   // time for this frame min &lt;=time&lt; max
    /// </remarks>
    public int anim_min;
    /// <summary>
    /// time for this frame min
    /// &lt;
    /// =time
    /// &lt;
    /// max
    /// </summary>
    /// <remarks>
    /// Original: int anim_min, anim_max;			   // time for this frame min &lt;=time&lt; max
    /// </remarks>
    public int anim_max;
    /// <summary>
    /// in the animation sequence
    /// </summary>
    /// <remarks>
    /// Original: struct texture_s* anim_next;	   // in the animation sequence
    /// </remarks>
    public texture_t* anim_next;
    /// <summary>
    /// bmodels in frame 1 use these
    /// </summary>
    /// <remarks>
    /// Original: struct texture_s* alternate_anims; // bmodels in frame 1 use these
    /// </remarks>
    public texture_t* alternate_anims;
    /// <summary>
    /// four mip maps stored
    /// </summary>
    /// <remarks>
    /// Original: unsigned offsets[MIPLEVELS];	   // four mip maps stored
    /// </remarks>
    public InlineArray4<uint> offsets;
    /// <remarks>
    /// Original: unsigned paloffset;
    /// </remarks>
    public uint paloffset;
}

