// <auto-generated/>
using System.Runtime.CompilerServices;

namespace NativeInterop;

[InlineArray(600)] 
public unsafe struct InlineArray600<T> : IInlineArrayUnmanaged<T> where T : unmanaged
{
    public T Element0;
}

