// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct engine_studio_api_s { // Allocate number*size bytes and zero it void* (*Mem_Calloc)(int number, size_t size); // Check to see if pointer is in the cache void* (*Cache_Check)(struct cache_user_s* c); // Load file into cache...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct engine_studio_api_t
{
    /// <summary>
    /// Allocate number*size bytes and zero it
    /// </summary>
    /// <remarks>
    /// Original: void* (*Mem_Calloc)(int number, size_t size);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, uint, void*> Mem_Calloc;
    /// <summary>
    /// Check to see if pointer is in the cache
    /// </summary>
    /// <remarks>
    /// Original: void* (*Cache_Check)(struct cache_user_s* c);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<cache_user_t*, void*> Cache_Check;
    /// <summary>
    /// Load file into cache ( can be swapped out on demand )
    /// </summary>
    /// <remarks>
    /// Original: void (*LoadCacheFile)(char* path, struct cache_user_s* cu);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, cache_user_t*, void> LoadCacheFile;
    /// <summary>
    /// Retrieve model pointer for the named model
    /// </summary>
    /// <remarks>
    /// Original: struct model_s* (*Mod_ForName)(const char* name, int crash_if_missing);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int, model_t*> Mod_ForName;
    /// <summary>
    /// Retrieve pointer to studio model data block from a model
    /// </summary>
    /// <remarks>
    /// Original: void* (*Mod_Extradata)(struct model_s* mod);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<model_t*, void*> Mod_Extradata;
    /// <summary>
    /// Retrieve indexed model from client side model precache list
    /// </summary>
    /// <remarks>
    /// Original: struct model_s* (*GetModelByIndex)(int index);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, model_t*> GetModelByIndex;
    /// <summary>
    /// Get entity that is set for rendering
    /// </summary>
    /// <remarks>
    /// Original: struct cl_entity_s* (*GetCurrentEntity)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<cl_entity_t*> GetCurrentEntity;
    /// <summary>
    /// Get referenced player_info_t
    /// </summary>
    /// <remarks>
    /// Original: struct player_info_s* (*PlayerInfo)(int index);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, player_info_t*> PlayerInfo;
    /// <summary>
    /// Get most recently received player state data from network system
    /// </summary>
    /// <remarks>
    /// Original: struct entity_state_s* (*GetPlayerState)(int index);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, entity_state_t*> GetPlayerState;
    /// <summary>
    /// Get viewentity
    /// </summary>
    /// <remarks>
    /// Original: struct cl_entity_s* (*GetViewEntity)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<cl_entity_t*> GetViewEntity;
    /// <summary>
    /// Get current frame count, and last two timestampes on client
    /// </summary>
    /// <remarks>
    /// Original: void (*GetTimes)(int* framecount, double* current, double* old);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int*, double*, double*, void> GetTimes;
    /// <summary>
    /// Get a pointer to a cvar by name
    /// </summary>
    /// <remarks>
    /// Original: struct cvar_s* (*GetCvar)(const char* name);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, cvar_t*> GetCvar;
    /// <summary>
    /// Get current render origin and view vectors ( up, right and vpn )
    /// </summary>
    /// <remarks>
    /// Original: void (*GetViewInfo)(float* origin, float* upv, float* rightv, float* vpnv);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, float*, float*, void> GetViewInfo;
    /// <summary>
    /// Get sprite model used for applying chrome effect
    /// </summary>
    /// <remarks>
    /// Original: struct model_s* (*GetChromeSprite)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<model_t*> GetChromeSprite;
    /// <summary>
    /// Get model counters so we can incement instrumentation
    /// </summary>
    /// <remarks>
    /// Original: void (*GetModelCounters)(int** s, int** a);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int**, int**, void> GetModelCounters;
    /// <summary>
    /// Get software scaling coefficients
    /// </summary>
    /// <remarks>
    /// Original: void (*GetAliasScale)(float* x, float* y);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, void> GetAliasScale;
    /// <summary>
    /// Get bone, light, alias, and rotation matrices
    /// </summary>
    /// <remarks>
    /// Original: float**** (*StudioGetBoneTransform)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float****> StudioGetBoneTransform;
    /// <remarks>
    /// Original: float**** (*StudioGetLightTransform)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float****> StudioGetLightTransform;
    /// <remarks>
    /// Original: float*** (*StudioGetAliasTransform)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float***> StudioGetAliasTransform;
    /// <remarks>
    /// Original: float*** (*StudioGetRotationMatrix)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float***> StudioGetRotationMatrix;
    /// <summary>
    /// Set up body part, and get submodel pointers
    /// </summary>
    /// <remarks>
    /// Original: void (*StudioSetupModel)(int bodypart, void** ppbodypart, void** ppsubmodel);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, void**, void**, void> StudioSetupModel;
    /// <summary>
    /// Check if entity's bbox is in the view frustum
    /// </summary>
    /// <remarks>
    /// Original: int (*StudioCheckBBox)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> StudioCheckBBox;
    /// <summary>
    /// Apply lighting effects to model
    /// </summary>
    /// <remarks>
    /// Original: void (*StudioDynamicLight)(struct cl_entity_s* ent, struct alight_s* plight);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<cl_entity_t*, alight_t*, void> StudioDynamicLight;
    /// <remarks>
    /// Original: void (*StudioEntityLight)(struct alight_s* plight);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<alight_t*, void> StudioEntityLight;
    /// <remarks>
    /// Original: void (*StudioSetupLighting)(struct alight_s* plighting);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<alight_t*, void> StudioSetupLighting;
    /// <summary>
    /// Draw mesh vertices
    /// </summary>
    /// <remarks>
    /// Original: void (*StudioDrawPoints)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> StudioDrawPoints;
    /// <summary>
    /// Draw hulls around bones
    /// </summary>
    /// <remarks>
    /// Original: void (*StudioDrawHulls)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> StudioDrawHulls;
    /// <summary>
    /// Draw bbox around studio models
    /// </summary>
    /// <remarks>
    /// Original: void (*StudioDrawAbsBBox)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> StudioDrawAbsBBox;
    /// <summary>
    /// Draws bones
    /// </summary>
    /// <remarks>
    /// Original: void (*StudioDrawBones)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> StudioDrawBones;
    /// <summary>
    /// Loads in appropriate texture for model
    /// </summary>
    /// <remarks>
    /// Original: void (*StudioSetupSkin)(void* ptexturehdr, int index);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void*, int, void> StudioSetupSkin;
    /// <summary>
    /// Sets up for remapped colors
    /// </summary>
    /// <remarks>
    /// Original: void (*StudioSetRemapColors)(int top, int bottom);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, void> StudioSetRemapColors;
    /// <summary>
    /// Set's player model and returns model pointer
    /// </summary>
    /// <remarks>
    /// Original: struct model_s* (*SetupPlayerModel)(int index);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, model_t*> SetupPlayerModel;
    /// <summary>
    /// Fires any events embedded in animation
    /// </summary>
    /// <remarks>
    /// Original: void (*StudioClientEvents)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> StudioClientEvents;
    /// <summary>
    /// Retrieve/set forced render effects flags
    /// </summary>
    /// <remarks>
    /// Original: int (*GetForceFaceFlags)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> GetForceFaceFlags;
    /// <remarks>
    /// Original: void (*SetForceFaceFlags)(int flags);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, void> SetForceFaceFlags;
    /// <summary>
    /// Tell engine the value of the studio model header
    /// </summary>
    /// <remarks>
    /// Original: void (*StudioSetHeader)(void* header);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void*, void> StudioSetHeader;
    /// <summary>
    /// Tell engine which model_t * is being renderered
    /// </summary>
    /// <remarks>
    /// Original: void (*SetRenderModel)(struct model_s* model);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<model_t*, void> SetRenderModel;
    /// <summary>
    /// Final state setup and restore for rendering
    /// </summary>
    /// <remarks>
    /// Original: void (*SetupRenderer)(int rendermode);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, void> SetupRenderer;
    /// <remarks>
    /// Original: void (*RestoreRenderer)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> RestoreRenderer;
    /// <summary>
    /// Set render origin for applying chrome effect
    /// </summary>
    /// <remarks>
    /// Original: void (*SetChromeOrigin)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> SetChromeOrigin;
    /// <summary>
    /// True if using D3D/OpenGL
    /// </summary>
    /// <remarks>
    /// Original: int (*IsHardware)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> IsHardware;
    /// <summary>
    /// Only called by hardware interface
    /// </summary>
    /// <remarks>
    /// Original: void (*GL_StudioDrawShadow)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> GL_StudioDrawShadow;
    /// <remarks>
    /// Original: void (*GL_SetRenderMode)(int mode);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, void> GL_SetRenderMode;
    /// <remarks>
    /// Original: void (*StudioSetRenderamt)(int iRenderamt); //!!!CZERO added for rendering glass on viewmodels
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, void> StudioSetRenderamt;
    /// <summary>
    /// !!CZERO added for rendering glass on viewmodels
    /// </summary>
    /// <remarks>
    /// Original: void (*StudioSetCullState)(int iCull);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, void> StudioSetCullState;
    /// <remarks>
    /// Original: void (*StudioRenderShadow)(int iSprite, float* p1, float* p2, float* p3, float* p4);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, float*, float*, float*, float*, void> StudioRenderShadow;
}

