// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// client blending
/// </summary>
/// <remarks>
/// Original: typedef struct r_studio_interface_s { int version; int (*StudioDrawModel)(int flags); int (*StudioDrawPlayer)(int flags, struct entity_state_s* pplayer); } r_studio_interface_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct r_studio_interface_t
{
    /// <remarks>
    /// Original: int version;
    /// </remarks>
    public int version;
    /// <remarks>
    /// Original: int (*StudioDrawModel)(int flags);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int> StudioDrawModel;
    /// <remarks>
    /// Original: int (*StudioDrawPlayer)(int flags, struct entity_state_s* pplayer);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, entity_state_t*, int> StudioDrawPlayer;
}

