// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct server_studio_api_s { // Allocate number*size bytes and zero it void* (*Mem_Calloc)(int number, size_t size); // Check to see if pointer is in the cache void* (*Cache_Check)(struct cache_user_s* c); // Load file into cache...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct server_studio_api_t
{
    /// <summary>
    /// Allocate number*size bytes and zero it
    /// </summary>
    /// <remarks>
    /// Original: void* (*Mem_Calloc)(int number, size_t size);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, uint, void*> Mem_Calloc;
    /// <summary>
    /// Check to see if pointer is in the cache
    /// </summary>
    /// <remarks>
    /// Original: void* (*Cache_Check)(struct cache_user_s* c);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<cache_user_t*, void*> Cache_Check;
    /// <summary>
    /// Load file into cache ( can be swapped out on demand )
    /// </summary>
    /// <remarks>
    /// Original: void (*LoadCacheFile)(char* path, struct cache_user_s* cu);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, cache_user_t*, void> LoadCacheFile;
    /// <summary>
    /// Retrieve pointer to studio model data block from a model
    /// </summary>
    /// <remarks>
    /// Original: void* (*Mod_Extradata)(struct model_s* mod);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<model_t*, void*> Mod_Extradata;
}

