// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct sv_blending_interface_s { int version; void (*SV_StudioSetupBones)(struct model_s* pModel, float frame, int sequence, const Vector angles, const Vector origin, const byte* pcontroller, const byte* pblending, int iBone, con...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct sv_blending_interface_t
{
    /// <remarks>
    /// Original: int version;
    /// </remarks>
    public int version;
    /// <remarks>
    /// Original: void (*SV_StudioSetupBones)(struct model_s* pModel, float frame, int sequence, const Vector angles, const Vector origin, const byte* pcontroller, const byte* pblending, int iBone, const edict_t* pEdict);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<model_t*, float, int, Vector3, Vector3, byte*, byte*, int, edict_t*, void> SV_StudioSetupBones;
}

