// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct alight_s { int ambientlight; // clip at 128 int shadelight;	  // clip at 192 - ambientlight Vector color; float* plightvec; } alight_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct alight_t
{
    /// <summary>
    /// clip at 128
    /// </summary>
    /// <remarks>
    /// Original: int ambientlight; // clip at 128
    /// </remarks>
    public int ambientlight;
    /// <summary>
    /// clip at 192 - ambientlight
    /// </summary>
    /// <remarks>
    /// Original: int shadelight;	  // clip at 192 - ambientlight
    /// </remarks>
    public int shadelight;
    /// <remarks>
    /// Original: Vector color;
    /// </remarks>
    public Vector3 color;
    /// <remarks>
    /// Original: float* plightvec;
    /// </remarks>
    public float* plightvec;
}

