// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct cache_user_s { void* data; } cache_user_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct cache_user_t
{
    /// <remarks>
    /// Original: void* data;
    /// </remarks>
    public void* data;
}

