// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct { int planenum; short children[2]; // negative numbers are contents } dclipnode_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct dclipnode_t
{
    /// <remarks>
    /// Original: int planenum;
    /// </remarks>
    public int planenum;
    /// <summary>
    /// negative numbers are contents
    /// </summary>
    /// <remarks>
    /// Original: short children[2]; // negative numbers are contents
    /// </remarks>
    public InlineArray2<short> children;
}

