// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// JAY: Compress this as much as possible
/// </summary>
/// <remarks>
/// Original: struct decal_s { decal_t* pnext;		  // linked list for each surface msurface_t* psurface; // Surface id for persistence / unlinking short dx;			  // Offsets into surface texture (in texture coordinates, so we don't need floats) short dy;...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct decal_t
{
    /// <summary>
    /// linked list for each surface
    /// </summary>
    /// <remarks>
    /// Original: decal_t* pnext;		  // linked list for each surface
    /// </remarks>
    public decal_t* pnext;
    /// <summary>
    /// Surface id for persistence / unlinking
    /// </summary>
    /// <remarks>
    /// Original: msurface_t* psurface; // Surface id for persistence / unlinking
    /// </remarks>
    public msurface_t* psurface;
    /// <summary>
    /// Offsets into surface texture (in texture coordinates, so we don't need floats)
    /// </summary>
    /// <remarks>
    /// Original: short dx;			  // Offsets into surface texture (in texture coordinates, so we don't need floats)
    /// </remarks>
    public short dx;
    /// <remarks>
    /// Original: short dy;
    /// </remarks>
    public short dy;
    /// <summary>
    /// Decal texture
    /// </summary>
    /// <remarks>
    /// Original: short texture; // Decal texture
    /// </remarks>
    public short texture;
    /// <summary>
    /// Pixel scale
    /// </summary>
    /// <remarks>
    /// Original: byte scale;	   // Pixel scale
    /// </remarks>
    public byte scale;
    /// <summary>
    /// Decal flags
    /// </summary>
    /// <remarks>
    /// Original: byte flags;	   // Decal flags
    /// </remarks>
    public byte flags;
    /// <summary>
    /// Entity this is attached to
    /// </summary>
    /// <remarks>
    /// Original: short entityIndex; // Entity this is attached to
    /// </remarks>
    public short entityIndex;
}

