// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct { float mins[3], maxs[3]; float origin[3]; int headnode[MAX_MAP_HULLS]; int visleafs; // not including the solid leaf 0 int firstface, numfaces; } dmodel_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct dmodel_t
{
    /// <remarks>
    /// Original: float mins[3], maxs[3];
    /// </remarks>
    public InlineArray3<float> mins;
    /// <remarks>
    /// Original: float mins[3], maxs[3];
    /// </remarks>
    public InlineArray3<float> maxs;
    /// <remarks>
    /// Original: float origin[3];
    /// </remarks>
    public InlineArray3<float> origin;
    /// <remarks>
    /// Original: int headnode[MAX_MAP_HULLS];
    /// </remarks>
    public InlineArray4<int> headnode;
    /// <summary>
    /// not including the solid leaf 0
    /// </summary>
    /// <remarks>
    /// Original: int visleafs; // not including the solid leaf 0
    /// </remarks>
    public int visleafs;
    /// <remarks>
    /// Original: int firstface, numfaces;
    /// </remarks>
    public int firstface;
    /// <remarks>
    /// Original: int firstface, numfaces;
    /// </remarks>
    public int numfaces;
}

