// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct hull_s { dclipnode_t* clipnodes; mplane_t* planes; int firstclipnode; int lastclipnode; Vector clip_mins; Vector clip_maxs; } hull_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct hull_t
{
    /// <remarks>
    /// Original: dclipnode_t* clipnodes;
    /// </remarks>
    public dclipnode_t* clipnodes;
    /// <remarks>
    /// Original: mplane_t* planes;
    /// </remarks>
    public mplane_t* planes;
    /// <remarks>
    /// Original: int firstclipnode;
    /// </remarks>
    public int firstclipnode;
    /// <remarks>
    /// Original: int lastclipnode;
    /// </remarks>
    public int lastclipnode;
    /// <remarks>
    /// Original: Vector clip_mins;
    /// </remarks>
    public Vector3 clip_mins;
    /// <remarks>
    /// Original: Vector clip_maxs;
    /// </remarks>
    public Vector3 clip_maxs;
}

