// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct { unsigned short v[2]; unsigned int cachededgeoffset; } medge_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct medge_t
{
    /// <remarks>
    /// Original: unsigned short v[2];
    /// </remarks>
    public InlineArray2<ushort> v;
    /// <remarks>
    /// Original: unsigned int cachededgeoffset;
    /// </remarks>
    public uint cachededgeoffset;
}

