// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct mleaf_s { // common with node int contents; // wil be a negative contents number int visframe; // node needs to be traversed if current short minmaxs[6]; // for bounding box culling struct mnode_s* parent; // leaf specific...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct mleaf_t
{
    /// <summary>
    /// wil be a negative contents number
    /// </summary>
    /// <remarks>
    /// Original: int contents; // wil be a negative contents number
    /// </remarks>
    public int contents;
    /// <summary>
    /// node needs to be traversed if current
    /// </summary>
    /// <remarks>
    /// Original: int visframe; // node needs to be traversed if current
    /// </remarks>
    public int visframe;
    /// <summary>
    /// for bounding box culling
    /// </summary>
    /// <remarks>
    /// Original: short minmaxs[6]; // for bounding box culling
    /// </remarks>
    public InlineArray6<short> minmaxs;
    /// <remarks>
    /// Original: struct mnode_s* parent;
    /// </remarks>
    public mnode_t* parent;
    /// <summary>
    /// leaf specific
    /// </summary>
    /// <remarks>
    /// Original: byte* compressed_vis;
    /// </remarks>
    public byte* compressed_vis;
    /// <remarks>
    /// Original: struct efrag_s* efrags;
    /// </remarks>
    public efrag_t* efrags;
    /// <remarks>
    /// Original: msurface_t** firstmarksurface;
    /// </remarks>
    public msurface_t** firstmarksurface;
    /// <remarks>
    /// Original: int nummarksurfaces;
    /// </remarks>
    public int nummarksurfaces;
    /// <summary>
    /// BSP sequence number for leaf's contents
    /// </summary>
    /// <remarks>
    /// Original: int key; // BSP sequence number for leaf's contents
    /// </remarks>
    public int key;
    /// <remarks>
    /// Original: byte ambient_sound_level[NUM_AMBIENTS];
    /// </remarks>
    public InlineArray4<byte> ambient_sound_level;
}

