// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct mnode_s { // common with leaf int contents; // 0, to differentiate from leafs int visframe; // node needs to be traversed if current short minmaxs[6]; // for bounding box culling struct mnode_s* parent; // node specific mp...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct mnode_t
{
    /// <summary>
    /// 0, to differentiate from leafs
    /// </summary>
    /// <remarks>
    /// Original: int contents; // 0, to differentiate from leafs
    /// </remarks>
    public int contents;
    /// <summary>
    /// node needs to be traversed if current
    /// </summary>
    /// <remarks>
    /// Original: int visframe; // node needs to be traversed if current
    /// </remarks>
    public int visframe;
    /// <summary>
    /// for bounding box culling
    /// </summary>
    /// <remarks>
    /// Original: short minmaxs[6]; // for bounding box culling
    /// </remarks>
    public InlineArray6<short> minmaxs;
    /// <remarks>
    /// Original: struct mnode_s* parent;
    /// </remarks>
    public mnode_t* parent;
    /// <summary>
    /// node specific
    /// </summary>
    /// <remarks>
    /// Original: mplane_t* plane;
    /// </remarks>
    public mplane_t* plane;
    /// <remarks>
    /// Original: struct mnode_s* children[2];
    /// </remarks>
    public InlineArray2<mnode_t_ptr> children;
    /// <remarks>
    /// Original: unsigned short firstsurface;
    /// </remarks>
    public ushort firstsurface;
    /// <remarks>
    /// Original: unsigned short numsurfaces;
    /// </remarks>
    public ushort numsurfaces;
}

