// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef enum { mod_brush, mod_sprite, mod_alias, mod_studio } modtype_t;
/// </remarks>
public enum modtype_t
{
    mod_brush = 0,
    mod_sprite = 1,
    mod_alias = 2,
    mod_studio = 3,
}

