// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// plane_t structure
/// </summary>
/// <remarks>
/// Original: typedef struct mplane_s { Vector normal; // surface normal float dist;	   // closest appoach to origin byte type;	   // for texture axis selection and fast side tests byte signbits; // signx + signy&lt;&lt;1 + signz&lt;&lt;1 byte pad[2]; } mplane_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct mplane_t
{
    /// <summary>
    /// surface normal
    /// </summary>
    /// <remarks>
    /// Original: Vector normal; // surface normal
    /// </remarks>
    public Vector3 normal;
    /// <summary>
    /// closest appoach to origin
    /// </summary>
    /// <remarks>
    /// Original: float dist;	   // closest appoach to origin
    /// </remarks>
    public float dist;
    /// <summary>
    /// for texture axis selection and fast side tests
    /// </summary>
    /// <remarks>
    /// Original: byte type;	   // for texture axis selection and fast side tests
    /// </remarks>
    public byte type;
    /// <summary>
    /// signx + signy
    /// &lt;
    /// &lt;
    /// 1 + signz
    /// &lt;
    /// &lt;
    /// 1
    /// </summary>
    /// <remarks>
    /// Original: byte signbits; // signx + signy&lt;&lt;1 + signz&lt;&lt;1
    /// </remarks>
    public byte signbits;
    /// <remarks>
    /// Original: byte pad[2];
    /// </remarks>
    public InlineArray2<byte> pad;
}

