// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct { float vecs[2][4]; // [s/t] unit vectors in world space. // [i][3] is the s/t offset relative to the origin. // s or t = dot(3Dpoint,vecs[i])+vecs[i][3] float mipadjust;  // ?? mipmap limits for very small surfaces textur...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct mtexinfo_t
{
    /// <summary>
    /// [s/t] unit vectors in world space.
    /// </summary>
    /// <remarks>
    /// Original: float vecs[2][4]; // [s/t] unit vectors in world space.
    /// </remarks>
    public InlineArray2<InlineArray4<float>> vecs;
    /// <summary>
    /// ?? mipmap limits for very small surfaces
    /// </summary>
    /// <remarks>
    /// Original: float mipadjust;  // ?? mipmap limits for very small surfaces
    /// </remarks>
    public float mipadjust;
    /// <remarks>
    /// Original: texture_t* texture;
    /// </remarks>
    public texture_t* texture;
    /// <summary>
    /// sky or slime, no lightmap or 256 subdivision
    /// </summary>
    /// <remarks>
    /// Original: int flags; // sky or slime, no lightmap or 256 subdivision
    /// </remarks>
    public int flags;
}

