// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct { Vector position; } mvertex_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct mvertex_t
{
    /// <remarks>
    /// Original: Vector position;
    /// </remarks>
    public Vector3 position;
}

