// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct player_info_s { // User id on server int userid; // User info string char userinfo[MAX_INFO_STRING]; // Name char name[MAX_SCOREBOARDNAME]; // Spectator or not, unused int spectator; int ping; int packet_loss; // skin info...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct player_info_t
{
    /// <summary>
    /// User id on server
    /// </summary>
    /// <remarks>
    /// Original: int userid;
    /// </remarks>
    public int userid;
    /// <summary>
    /// User info string
    /// </summary>
    /// <remarks>
    /// Original: char userinfo[MAX_INFO_STRING];
    /// </remarks>
    public InlineArray256<NChar> userinfo;
    /// <summary>
    /// Name
    /// </summary>
    /// <remarks>
    /// Original: char name[MAX_SCOREBOARDNAME];
    /// </remarks>
    public InlineArray32<NChar> name;
    /// <summary>
    /// Spectator or not, unused
    /// </summary>
    /// <remarks>
    /// Original: int spectator;
    /// </remarks>
    public int spectator;
    /// <remarks>
    /// Original: int ping;
    /// </remarks>
    public int ping;
    /// <remarks>
    /// Original: int packet_loss;
    /// </remarks>
    public int packet_loss;
    /// <summary>
    /// skin information
    /// </summary>
    /// <remarks>
    /// Original: char model[MAX_QPATH];
    /// </remarks>
    public InlineArray64<NChar> model;
    /// <remarks>
    /// Original: int topcolor;
    /// </remarks>
    public int topcolor;
    /// <remarks>
    /// Original: int bottomcolor;
    /// </remarks>
    public int bottomcolor;
    /// <summary>
    /// last frame rendered
    /// </summary>
    /// <remarks>
    /// Original: int renderframe;
    /// </remarks>
    public int renderframe;
    /// <summary>
    /// Gait frame estimation
    /// </summary>
    /// <remarks>
    /// Original: int gaitsequence;
    /// </remarks>
    public int gaitsequence;
    /// <remarks>
    /// Original: float gaitframe;
    /// </remarks>
    public float gaitframe;
    /// <remarks>
    /// Original: float gaityaw;
    /// </remarks>
    public float gaityaw;
    /// <remarks>
    /// Original: Vector prevgaitorigin;
    /// </remarks>
    public Vector3 prevgaitorigin;
    /// <remarks>
    /// Original: customization_t customdata;
    /// </remarks>
    public customization_t customdata;
    /// <remarks>
    /// Original: char hashedcdkey[16];
    /// </remarks>
    public InlineArray16<NChar> hashedcdkey;
    /// <remarks>
    /// Original: uint64 m_nSteamID;
    /// </remarks>
    public ulong m_nSteamID;
}

