// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef enum { ST_SYNC = 0, ST_RAND } synctype_t;
/// </remarks>
public enum synctype_t
{
    ST_SYNC = 0,
    ST_RAND = 1,
}

