// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct local_state_s { entity_state_t playerstate; clientdata_t client; weapon_data_t weapondata[64]; } local_state_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct local_state_t
{
    /// <remarks>
    /// Original: entity_state_t playerstate;
    /// </remarks>
    public entity_state_t playerstate;
    /// <remarks>
    /// Original: clientdata_t client;
    /// </remarks>
    public clientdata_t client;
    /// <remarks>
    /// Original: weapon_data_t weapondata[64];
    /// </remarks>
    public InlineArray64<weapon_data_t> weapondata;
}

