// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: struct efx_api_s { particle_t* (*R_AllocParticle)(void (*callback)(struct particle_s* particle, float frametime)); void (*R_BlobExplosion)(float* org); void (*R_Blood)(float* org, float* dir, int pcolor, int speed); void (*R_BloodSprite)...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct efx_api_t
{
    /// <remarks>
    /// Original: particle_t* (*R_AllocParticle)(void (*callback)(struct particle_s* particle, float frametime));
    /// </remarks>
    public delegate* unmanaged[Cdecl]<delegate* unmanaged[Cdecl]<particle_t*, float, void>, particle_t*> R_AllocParticle;
    /// <remarks>
    /// Original: void (*R_BlobExplosion)(float* org);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, void> R_BlobExplosion;
    /// <remarks>
    /// Original: void (*R_Blood)(float* org, float* dir, int pcolor, int speed);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, int, int, void> R_Blood;
    /// <remarks>
    /// Original: void (*R_BloodSprite)(float* org, int colorindex, int modelIndex, int modelIndex2, float size);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, int, int, int, float, void> R_BloodSprite;
    /// <remarks>
    /// Original: void (*R_BloodStream)(float* org, float* dir, int pcolor, int speed);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, int, int, void> R_BloodStream;
    /// <remarks>
    /// Original: void (*R_BreakModel)(float* pos, float* size, float* dir, float random, float life, int count, int modelIndex, char flags);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, float*, float, float, int, int, NChar, void> R_BreakModel;
    /// <remarks>
    /// Original: void (*R_Bubbles)(float* mins, float* maxs, float height, int modelIndex, int count, float speed);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, float, int, int, float, void> R_Bubbles;
    /// <remarks>
    /// Original: void (*R_BubbleTrail)(float* start, float* end, float height, int modelIndex, int count, float speed);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, float, int, int, float, void> R_BubbleTrail;
    /// <remarks>
    /// Original: void (*R_BulletImpactParticles)(float* pos);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, void> R_BulletImpactParticles;
    /// <remarks>
    /// Original: void (*R_EntityParticles)(struct cl_entity_s* ent);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<cl_entity_t*, void> R_EntityParticles;
    /// <remarks>
    /// Original: void (*R_Explosion)(float* pos, int model, float scale, float framerate, int flags);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, int, float, float, int, void> R_Explosion;
    /// <remarks>
    /// Original: void (*R_FizzEffect)(struct cl_entity_s* pent, int modelIndex, int density);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<cl_entity_t*, int, int, void> R_FizzEffect;
    /// <remarks>
    /// Original: void (*R_FireField)(float* org, int radius, int modelIndex, int count, int flags, float life);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, int, int, int, int, float, void> R_FireField;
    /// <remarks>
    /// Original: void (*R_FlickerParticles)(float* org);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, void> R_FlickerParticles;
    /// <remarks>
    /// Original: void (*R_FunnelSprite)(float* org, int modelIndex, int reverse);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, int, int, void> R_FunnelSprite;
    /// <remarks>
    /// Original: void (*R_Implosion)(float* end, float radius, int count, float life);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float, int, float, void> R_Implosion;
    /// <remarks>
    /// Original: void (*R_LargeFunnel)(float* org, int reverse);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, int, void> R_LargeFunnel;
    /// <remarks>
    /// Original: void (*R_LavaSplash)(float* org);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, void> R_LavaSplash;
    /// <remarks>
    /// Original: void (*R_MultiGunshot)(float* org, float* dir, float* noise, int count, int decalCount, int* decalIndices);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, float*, int, int, int*, void> R_MultiGunshot;
    /// <remarks>
    /// Original: void (*R_MuzzleFlash)(float* pos1, int type);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, int, void> R_MuzzleFlash;
    /// <remarks>
    /// Original: void (*R_ParticleBox)(float* mins, float* maxs, unsigned char r, unsigned char g, unsigned char b, float life);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, byte, byte, byte, float, void> R_ParticleBox;
    /// <remarks>
    /// Original: void (*R_ParticleBurst)(float* pos, int size, int color, float life);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, int, int, float, void> R_ParticleBurst;
    /// <remarks>
    /// Original: void (*R_ParticleExplosion)(float* org);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, void> R_ParticleExplosion;
    /// <remarks>
    /// Original: void (*R_ParticleExplosion2)(float* org, int colorStart, int colorLength);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, int, int, void> R_ParticleExplosion2;
    /// <remarks>
    /// Original: void (*R_ParticleLine)(float* start, float* end, unsigned char r, unsigned char g, unsigned char b, float life);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, byte, byte, byte, float, void> R_ParticleLine;
    /// <remarks>
    /// Original: void (*R_PlayerSprites)(int client, int modelIndex, int count, int size);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, int, int, void> R_PlayerSprites;
    /// <remarks>
    /// Original: void (*R_Projectile)(float* origin, float* velocity, int modelIndex, int life, int owner, void (*hitcallback)(struct tempent_s* ent, struct pmtrace_s* ptr));
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, int, int, int, delegate* unmanaged[Cdecl]<TEMPENTITY*, pmtrace_t*, void>, void> R_Projectile;
    /// <remarks>
    /// Original: void (*R_RicochetSound)(float* pos);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, void> R_RicochetSound;
    /// <remarks>
    /// Original: void (*R_RicochetSprite)(float* pos, struct model_s* pmodel, float duration, float scale);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, model_t*, float, float, void> R_RicochetSprite;
    /// <remarks>
    /// Original: void (*R_RocketFlare)(float* pos);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, void> R_RocketFlare;
    /// <remarks>
    /// Original: void (*R_RocketTrail)(float* start, float* end, int type);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, int, void> R_RocketTrail;
    /// <remarks>
    /// Original: void (*R_RunParticleEffect)(float* org, float* dir, int color, int count);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, int, int, void> R_RunParticleEffect;
    /// <remarks>
    /// Original: void (*R_ShowLine)(float* start, float* end);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, void> R_ShowLine;
    /// <remarks>
    /// Original: void (*R_SparkEffect)(float* pos, int count, int velocityMin, int velocityMax);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, int, int, int, void> R_SparkEffect;
    /// <remarks>
    /// Original: void (*R_SparkShower)(float* pos);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, void> R_SparkShower;
    /// <remarks>
    /// Original: void (*R_SparkStreaks)(float* pos, int count, int velocityMin, int velocityMax);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, int, int, int, void> R_SparkStreaks;
    /// <remarks>
    /// Original: void (*R_Spray)(float* pos, float* dir, int modelIndex, int count, int speed, int spread, int rendermode);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, int, int, int, int, int, void> R_Spray;
    /// <remarks>
    /// Original: void (*R_Sprite_Explode)(TEMPENTITY* pTemp, float scale, int flags);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<TEMPENTITY*, float, int, void> R_Sprite_Explode;
    /// <remarks>
    /// Original: void (*R_Sprite_Smoke)(TEMPENTITY* pTemp, float scale);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<TEMPENTITY*, float, void> R_Sprite_Smoke;
    /// <remarks>
    /// Original: void (*R_Sprite_Spray)(float* pos, float* dir, int modelIndex, int count, int speed, int iRand);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, int, int, int, int, void> R_Sprite_Spray;
    /// <remarks>
    /// Original: void (*R_Sprite_Trail)(int type, float* start, float* end, int modelIndex, int count, float life, float size, float amplitude, int renderamt, float speed);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, float*, float*, int, int, float, float, float, int, float, void> R_Sprite_Trail;
    /// <remarks>
    /// Original: void (*R_Sprite_WallPuff)(TEMPENTITY* pTemp, float scale);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<TEMPENTITY*, float, void> R_Sprite_WallPuff;
    /// <remarks>
    /// Original: void (*R_StreakSplash)(float* pos, float* dir, int color, int count, float speed, int velocityMin, int velocityMax);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, int, int, float, int, int, void> R_StreakSplash;
    /// <remarks>
    /// Original: void (*R_TracerEffect)(float* start, float* end);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, void> R_TracerEffect;
    /// <remarks>
    /// Original: void (*R_UserTracerParticle)(float* org, float* vel, float life, int colorIndex, float length, unsigned char deathcontext, void (*deathfunc)(struct particle_s* particle));
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, float, int, float, byte, delegate* unmanaged[Cdecl]<particle_t*, void>, void> R_UserTracerParticle;
    /// <remarks>
    /// Original: particle_t* (*R_TracerParticles)(float* org, float* vel, float life);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, float, particle_t*> R_TracerParticles;
    /// <remarks>
    /// Original: void (*R_TeleportSplash)(float* org);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, void> R_TeleportSplash;
    /// <remarks>
    /// Original: void (*R_TempSphereModel)(float* pos, float speed, float life, int count, int modelIndex);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float, float, int, int, void> R_TempSphereModel;
    /// <remarks>
    /// Original: TEMPENTITY* (*R_TempModel)(float* pos, float* dir, float* angles, float life, int modelIndex, int soundtype);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, float*, float, int, int, TEMPENTITY*> R_TempModel;
    /// <remarks>
    /// Original: TEMPENTITY* (*R_DefaultSprite)(float* pos, int spriteIndex, float framerate);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, int, float, TEMPENTITY*> R_DefaultSprite;
    /// <remarks>
    /// Original: TEMPENTITY* (*R_TempSprite)(float* pos, const float* dir, float scale, int modelIndex, int rendermode, int renderfx, float a, float life, int flags);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, float, int, int, int, float, float, int, TEMPENTITY*> R_TempSprite;
    /// <remarks>
    /// Original: int (*Draw_DecalIndex)(int id);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int> Draw_DecalIndex;
    /// <remarks>
    /// Original: int (*Draw_DecalIndexFromName)(char* name);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int> Draw_DecalIndexFromName;
    /// <remarks>
    /// Original: void (*R_DecalShoot)(int textureIndex, int entity, int modelIndex, float* position, int flags);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, int, float*, int, void> R_DecalShoot;
    /// <remarks>
    /// Original: void (*R_AttachTentToPlayer)(int client, int modelIndex, float zoffset, float life);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, float, float, void> R_AttachTentToPlayer;
    /// <remarks>
    /// Original: void (*R_KillAttachedTents)(int client);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, void> R_KillAttachedTents;
    /// <remarks>
    /// Original: BEAM* (*R_BeamCirclePoints)(int type, float* start, float* end, int modelIndex, float life, float width, float amplitude, float brightness, float speed, int startFrame, float framerate, float r, float g, float b);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, float*, float*, int, float, float, float, float, float, int, float, float, float, float, BEAM*> R_BeamCirclePoints;
    /// <remarks>
    /// Original: BEAM* (*R_BeamEntPoint)(int startEnt, float* end, int modelIndex, float life, float width, float amplitude, float brightness, float speed, int startFrame, float framerate, float r, float g, float b);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, float*, int, float, float, float, float, float, int, float, float, float, float, BEAM*> R_BeamEntPoint;
    /// <remarks>
    /// Original: BEAM* (*R_BeamEnts)(int startEnt, int endEnt, int modelIndex, float life, float width, float amplitude, float brightness, float speed, int startFrame, float framerate, float r, float g, float b);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, int, float, float, float, float, float, int, float, float, float, float, BEAM*> R_BeamEnts;
    /// <remarks>
    /// Original: BEAM* (*R_BeamFollow)(int startEnt, int modelIndex, float life, float width, float r, float g, float b, float brightness);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, float, float, float, float, float, float, BEAM*> R_BeamFollow;
    /// <remarks>
    /// Original: void (*R_BeamKill)(int deadEntity);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, void> R_BeamKill;
    /// <remarks>
    /// Original: BEAM* (*R_BeamLightning)(float* start, float* end, int modelIndex, float life, float width, float amplitude, float brightness, float speed);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, int, float, float, float, float, float, BEAM*> R_BeamLightning;
    /// <remarks>
    /// Original: BEAM* (*R_BeamPoints)(float* start, float* end, int modelIndex, float life, float width, float amplitude, float brightness, float speed, int startFrame, float framerate, float r, float g, float b);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, int, float, float, float, float, float, int, float, float, float, float, BEAM*> R_BeamPoints;
    /// <remarks>
    /// Original: BEAM* (*R_BeamRing)(int startEnt, int endEnt, int modelIndex, float life, float width, float amplitude, float brightness, float speed, int startFrame, float framerate, float r, float g, float b);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, int, float, float, float, float, float, int, float, float, float, float, BEAM*> R_BeamRing;
    /// <remarks>
    /// Original: dlight_t* (*CL_AllocDlight)(int key);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, dlight_t*> CL_AllocDlight;
    /// <remarks>
    /// Original: dlight_t* (*CL_AllocElight)(int key);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, dlight_t*> CL_AllocElight;
    /// <remarks>
    /// Original: TEMPENTITY* (*CL_TempEntAlloc)(float* org, struct model_s* model);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, model_t*, TEMPENTITY*> CL_TempEntAlloc;
    /// <remarks>
    /// Original: TEMPENTITY* (*CL_TempEntAllocNoModel)(float* org);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, TEMPENTITY*> CL_TempEntAllocNoModel;
    /// <remarks>
    /// Original: TEMPENTITY* (*CL_TempEntAllocHigh)(float* org, struct model_s* model);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, model_t*, TEMPENTITY*> CL_TempEntAllocHigh;
    /// <remarks>
    /// Original: TEMPENTITY* (*CL_TentEntAllocCustom)(float* origin, struct model_s* model, int high, void (*callback)(struct tempent_s* ent, float frametime, float currenttime));
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, model_t*, int, delegate* unmanaged[Cdecl]<TEMPENTITY*, float, float, void>, TEMPENTITY*> CL_TentEntAllocCustom;
    /// <remarks>
    /// Original: void (*R_GetPackedColor)(short* packed, short color);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<short*, short, void> R_GetPackedColor;
    /// <remarks>
    /// Original: short (*R_LookupColor)(unsigned char r, unsigned char g, unsigned char b);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<byte, byte, byte, short> R_LookupColor;
    /// <summary>
    /// textureIndex points to the decal index in the array, not the actual texture index.
    /// </summary>
    /// <remarks>
    /// Original: void (*R_DecalRemoveAll)(int textureIndex); //textureIndex points to the decal index in the array, not the actual texture index.
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, void> R_DecalRemoveAll;
    /// <remarks>
    /// Original: void (*R_FireCustomDecal)(int textureIndex, int entity, int modelIndex, float* position, int flags, float scale);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, int, float*, int, float, void> R_FireCustomDecal;
}

