// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct tempent_s { int flags; float die; float frameMax; float x; float y; float z; float fadeSpeed; float bounceFactor; int hitSound; void (*hitcallback)(struct tempent_s* ent, struct pmtrace_s* ptr); void (*callback)(struct tem...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct TEMPENTITY
{
    /// <remarks>
    /// Original: int flags;
    /// </remarks>
    public int flags;
    /// <remarks>
    /// Original: float die;
    /// </remarks>
    public float die;
    /// <remarks>
    /// Original: float frameMax;
    /// </remarks>
    public float frameMax;
    /// <remarks>
    /// Original: float x;
    /// </remarks>
    public float x;
    /// <remarks>
    /// Original: float y;
    /// </remarks>
    public float y;
    /// <remarks>
    /// Original: float z;
    /// </remarks>
    public float z;
    /// <remarks>
    /// Original: float fadeSpeed;
    /// </remarks>
    public float fadeSpeed;
    /// <remarks>
    /// Original: float bounceFactor;
    /// </remarks>
    public float bounceFactor;
    /// <remarks>
    /// Original: int hitSound;
    /// </remarks>
    public int hitSound;
    /// <remarks>
    /// Original: void (*hitcallback)(struct tempent_s* ent, struct pmtrace_s* ptr);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<TEMPENTITY*, pmtrace_t*, void> hitcallback;
    /// <remarks>
    /// Original: void (*callback)(struct tempent_s* ent, float frametime, float currenttime);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<TEMPENTITY*, float, float, void> callback;
    /// <remarks>
    /// Original: struct tempent_s* next;
    /// </remarks>
    public TEMPENTITY* next;
    /// <remarks>
    /// Original: int priority;
    /// </remarks>
    public int priority;
    /// <summary>
    /// if attached, this is the index of the client to stick to
    /// </summary>
    /// <remarks>
    /// Original: short clientIndex; // if attached, this is the index of the client to stick to
    /// </remarks>
    public short clientIndex;
    /// <summary>
    /// if attached, client origin + tentOffset = tent origin.
    /// </summary>
    /// <remarks>
    /// Original: Vector tentOffset; // if attached, client origin + tentOffset = tent origin.
    /// </remarks>
    public Vector3 tentOffset;
    /// <remarks>
    /// Original: cl_entity_t entity;
    /// </remarks>
    public cl_entity_t entity;
}

