// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct client_data_s { // fields that cannot be modified  (ie. have no effect if changed) Vector origin; // fields that can be changed by the cldll Vector viewangles; int iWeaponBits; //	int		iAccessoryBits; float fov; // field o...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct client_data_t
{
    /// <summary>
    /// fields that cannot be modified  (ie. have no effect if changed)
    /// </summary>
    /// <remarks>
    /// Original: Vector origin;
    /// </remarks>
    public Vector3 origin;
    /// <summary>
    /// fields that can be changed by the cldll
    /// </summary>
    /// <remarks>
    /// Original: Vector viewangles;
    /// </remarks>
    public Vector3 viewangles;
    /// <remarks>
    /// Original: int iWeaponBits;
    /// </remarks>
    public int iWeaponBits;
    /// <summary>
    /// field of view
    /// </summary>
    /// <remarks>
    /// Original: float fov; // field of view
    /// </remarks>
    public float fov;
}

