// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct client_sprite_s { char szName[64]; char szSprite[64]; int hspr; int iRes; Rect rc; } client_sprite_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct client_sprite_t
{
    /// <remarks>
    /// Original: char szName[64];
    /// </remarks>
    public InlineArray64<NChar> szName;
    /// <remarks>
    /// Original: char szSprite[64];
    /// </remarks>
    public InlineArray64<NChar> szSprite;
    /// <remarks>
    /// Original: int hspr;
    /// </remarks>
    public int hspr;
    /// <remarks>
    /// Original: int iRes;
    /// </remarks>
    public int iRes;
    /// <remarks>
    /// Original: Rect rc;
    /// </remarks>
    public Rect rc;
}

