// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct hud_player_info_s { char* name; short ping; byte thisplayer; // true if this is the calling player byte spectator; byte packetloss; char* model; short topcolor; short bottomcolor; uint64 m_nSteamID; } hud_player_info_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct hud_player_info_t
{
    /// <remarks>
    /// Original: char* name;
    /// </remarks>
    public NChar* name;
    /// <remarks>
    /// Original: short ping;
    /// </remarks>
    public short ping;
    /// <summary>
    /// true if this is the calling player
    /// </summary>
    /// <remarks>
    /// Original: byte thisplayer; // true if this is the calling player
    /// </remarks>
    public byte thisplayer;
    /// <remarks>
    /// Original: byte spectator;
    /// </remarks>
    public byte spectator;
    /// <remarks>
    /// Original: byte packetloss;
    /// </remarks>
    public byte packetloss;
    /// <remarks>
    /// Original: char* model;
    /// </remarks>
    public NChar* model;
    /// <remarks>
    /// Original: short topcolor;
    /// </remarks>
    public short topcolor;
    /// <remarks>
    /// Original: short bottomcolor;
    /// </remarks>
    public short bottomcolor;
    /// <remarks>
    /// Original: uint64 m_nSteamID;
    /// </remarks>
    public ulong m_nSteamID;
}

