// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct SCREENINFO_s { int iSize; int iWidth; int iHeight; int iFlags; int iCharHeight; short charWidths[256]; } SCREENINFO;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct SCREENINFO
{
    /// <remarks>
    /// Original: int iSize;
    /// </remarks>
    public int iSize;
    /// <remarks>
    /// Original: int iWidth;
    /// </remarks>
    public int iWidth;
    /// <remarks>
    /// Original: int iHeight;
    /// </remarks>
    public int iHeight;
    /// <remarks>
    /// Original: int iFlags;
    /// </remarks>
    public int iFlags;
    /// <remarks>
    /// Original: int iCharHeight;
    /// </remarks>
    public int iCharHeight;
    /// <remarks>
    /// Original: short charWidths[256];
    /// </remarks>
    public InlineArray256<short> charWidths;
}

