// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: using qboolean = int;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct qboolean { public int Value; }

/// <summary>
/// this file is included by both the engine and the client-dll,
/// so make sure engine declarations aren't done twice
/// </summary>
/// <remarks>
/// Original: typedef int HSPRITE; // handle to a graphic
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct HSPRITE { public int Value; }

/// <remarks>
/// Original: using string_t = unsigned int;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct string_t { public uint Value; }

