// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct clientdata_s { Vector origin; Vector velocity; int viewmodel; Vector punchangle; int flags; int waterlevel; int watertype; Vector view_ofs; float health; int bInDuck; int weapons; // remove? int flTimeStepSound; int flDuck...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct clientdata_t
{
    /// <remarks>
    /// Original: Vector origin;
    /// </remarks>
    public Vector3 origin;
    /// <remarks>
    /// Original: Vector velocity;
    /// </remarks>
    public Vector3 velocity;
    /// <remarks>
    /// Original: int viewmodel;
    /// </remarks>
    public int viewmodel;
    /// <remarks>
    /// Original: Vector punchangle;
    /// </remarks>
    public Vector3 punchangle;
    /// <remarks>
    /// Original: int flags;
    /// </remarks>
    public int flags;
    /// <remarks>
    /// Original: int waterlevel;
    /// </remarks>
    public int waterlevel;
    /// <remarks>
    /// Original: int watertype;
    /// </remarks>
    public int watertype;
    /// <remarks>
    /// Original: Vector view_ofs;
    /// </remarks>
    public Vector3 view_ofs;
    /// <remarks>
    /// Original: float health;
    /// </remarks>
    public float health;
    /// <remarks>
    /// Original: int bInDuck;
    /// </remarks>
    public int bInDuck;
    /// <summary>
    /// remove?
    /// </summary>
    /// <remarks>
    /// Original: int weapons; // remove?
    /// </remarks>
    public int weapons;
    /// <remarks>
    /// Original: int flTimeStepSound;
    /// </remarks>
    public int flTimeStepSound;
    /// <remarks>
    /// Original: int flDuckTime;
    /// </remarks>
    public int flDuckTime;
    /// <remarks>
    /// Original: int flSwimTime;
    /// </remarks>
    public int flSwimTime;
    /// <remarks>
    /// Original: int waterjumptime;
    /// </remarks>
    public int waterjumptime;
    /// <remarks>
    /// Original: float maxspeed;
    /// </remarks>
    public float maxspeed;
    /// <remarks>
    /// Original: float fov;
    /// </remarks>
    public float fov;
    /// <remarks>
    /// Original: int weaponanim;
    /// </remarks>
    public int weaponanim;
    /// <remarks>
    /// Original: int m_iId;
    /// </remarks>
    public int m_iId;
    /// <remarks>
    /// Original: int ammo_shells;
    /// </remarks>
    public int ammo_shells;
    /// <remarks>
    /// Original: int ammo_nails;
    /// </remarks>
    public int ammo_nails;
    /// <remarks>
    /// Original: int ammo_cells;
    /// </remarks>
    public int ammo_cells;
    /// <remarks>
    /// Original: int ammo_rockets;
    /// </remarks>
    public int ammo_rockets;
    /// <remarks>
    /// Original: float m_flNextAttack;
    /// </remarks>
    public float m_flNextAttack;
    /// <remarks>
    /// Original: int tfstate;
    /// </remarks>
    public int tfstate;
    /// <remarks>
    /// Original: int pushmsec;
    /// </remarks>
    public int pushmsec;
    /// <remarks>
    /// Original: int deadflag;
    /// </remarks>
    public int deadflag;
    /// <remarks>
    /// Original: char physinfo[MAX_PHYSINFO_STRING];
    /// </remarks>
    public InlineArray256<NChar> physinfo;
    /// <summary>
    /// For mods
    /// </summary>
    /// <remarks>
    /// Original: int iuser1;
    /// </remarks>
    public int iuser1;
    /// <remarks>
    /// Original: int iuser2;
    /// </remarks>
    public int iuser2;
    /// <remarks>
    /// Original: int iuser3;
    /// </remarks>
    public int iuser3;
    /// <remarks>
    /// Original: int iuser4;
    /// </remarks>
    public int iuser4;
    /// <remarks>
    /// Original: float fuser1;
    /// </remarks>
    public float fuser1;
    /// <remarks>
    /// Original: float fuser2;
    /// </remarks>
    public float fuser2;
    /// <remarks>
    /// Original: float fuser3;
    /// </remarks>
    public float fuser3;
    /// <remarks>
    /// Original: float fuser4;
    /// </remarks>
    public float fuser4;
    /// <remarks>
    /// Original: Vector vuser1;
    /// </remarks>
    public Vector3 vuser1;
    /// <remarks>
    /// Original: Vector vuser2;
    /// </remarks>
    public Vector3 vuser2;
    /// <remarks>
    /// Original: Vector vuser3;
    /// </remarks>
    public Vector3 vuser3;
    /// <remarks>
    /// Original: Vector vuser4;
    /// </remarks>
    public Vector3 vuser4;
}

