// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: struct cl_entity_s { int index; // Index into cl_entities ( should match actual slot, but not necessarily ) qboolean player; // True if this entity is a "player" entity_state_t baseline;  // The original state from which to delta during ...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct cl_entity_t
{
    /// <summary>
    /// Index into cl_entities ( should match actual slot, but not necessarily )
    /// </summary>
    /// <remarks>
    /// Original: int index; // Index into cl_entities ( should match actual slot, but not necessarily )
    /// </remarks>
    public int index;
    /// <summary>
    /// True if this entity is a "player"
    /// </summary>
    /// <remarks>
    /// Original: qboolean player; // True if this entity is a "player"
    /// </remarks>
    public qboolean player;
    /// <summary>
    /// The original state from which to delta during an uncompressed message
    /// </summary>
    /// <remarks>
    /// Original: entity_state_t baseline;  // The original state from which to delta during an uncompressed message
    /// </remarks>
    public entity_state_t baseline;
    /// <summary>
    /// The state information from the penultimate message received from the server
    /// </summary>
    /// <remarks>
    /// Original: entity_state_t prevstate; // The state information from the penultimate message received from the server
    /// </remarks>
    public entity_state_t prevstate;
    /// <summary>
    /// The state information from the last message received from server
    /// </summary>
    /// <remarks>
    /// Original: entity_state_t curstate;  // The state information from the last message received from server
    /// </remarks>
    public entity_state_t curstate;
    /// <summary>
    /// Last received history update index
    /// </summary>
    /// <remarks>
    /// Original: int current_position;				// Last received history update index
    /// </remarks>
    public int current_position;
    /// <summary>
    /// History of position and angle updates for this player
    /// </summary>
    /// <remarks>
    /// Original: position_history_t ph[HISTORY_MAX]; // History of position and angle updates for this player
    /// </remarks>
    public InlineArray64<position_history_t> ph;
    /// <summary>
    /// For synchronizing mouth movements.
    /// </summary>
    /// <remarks>
    /// Original: mouth_t mouth; // For synchronizing mouth movements.
    /// </remarks>
    public mouth_t mouth;
    /// <summary>
    /// Variables used by studio model rendering routines
    /// </summary>
    /// <remarks>
    /// Original: latchedvars_t latched; // Variables used by studio model rendering routines
    /// </remarks>
    public latchedvars_t latched;
    /// <summary>
    /// Information based on interplocation, extrapolation, prediction, or just copied from last msg received.
    /// </summary>
    /// <remarks>
    /// Original: float lastmove;
    /// </remarks>
    public float lastmove;
    /// <summary>
    /// Actual render position and angles
    /// </summary>
    /// <remarks>
    /// Original: Vector origin;
    /// </remarks>
    public Vector3 origin;
    /// <remarks>
    /// Original: Vector angles;
    /// </remarks>
    public Vector3 angles;
    /// <summary>
    /// Attachment points
    /// </summary>
    /// <remarks>
    /// Original: Vector attachment[4];
    /// </remarks>
    public InlineArray4<Vector3> attachment;
    /// <summary>
    /// Other entity local information
    /// </summary>
    /// <remarks>
    /// Original: int trivial_accept;
    /// </remarks>
    public int trivial_accept;
    /// <summary>
    /// cl.model_precache[ curstate.modelindes ];  all visible entities have a model
    /// </summary>
    /// <remarks>
    /// Original: struct model_s* model;	 // cl.model_precache[ curstate.modelindes ];  all visible entities have a model
    /// </remarks>
    public model_t* model;
    /// <summary>
    /// linked list of efrags
    /// </summary>
    /// <remarks>
    /// Original: struct efrag_s* efrag;	 // linked list of efrags
    /// </remarks>
    public efrag_t* efrag;
    /// <summary>
    /// for bmodels, first world node that splits bmodel, or NULL if not split
    /// </summary>
    /// <remarks>
    /// Original: struct mnode_s* topnode; // for bmodels, first world node that splits bmodel, or NULL if not split
    /// </remarks>
    public mnode_t* topnode;
    /// <summary>
    /// for client-side animations -- used by obsolete alias animation system, remove?
    /// </summary>
    /// <remarks>
    /// Original: float syncbase; // for client-side animations -- used by obsolete alias animation system, remove?
    /// </remarks>
    public float syncbase;
    /// <summary>
    /// last frame this entity was found in an active leaf
    /// </summary>
    /// <remarks>
    /// Original: int visframe;	// last frame this entity was found in an active leaf
    /// </remarks>
    public int visframe;
    /// <remarks>
    /// Original: colorVec cvFloorColor;
    /// </remarks>
    public colorVec cvFloorColor;
}

