// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct ref_params_s { // Output float vieworg[3]; float viewangles[3]; float forward[3]; float right[3]; float up[3]; // Client frametime; float frametime; // Client time float time; // Misc int intermission; int paused; int spec...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct ref_params_t
{
    /// <summary>
    /// Output
    /// </summary>
    /// <remarks>
    /// Original: float vieworg[3];
    /// </remarks>
    public Vector3 vieworg;
    /// <remarks>
    /// Original: float viewangles[3];
    /// </remarks>
    public Vector3 viewangles;
    /// <remarks>
    /// Original: float forward[3];
    /// </remarks>
    public Vector3 forward;
    /// <remarks>
    /// Original: float right[3];
    /// </remarks>
    public Vector3 right;
    /// <remarks>
    /// Original: float up[3];
    /// </remarks>
    public Vector3 up;
    /// <summary>
    /// Client frametime;
    /// </summary>
    /// <remarks>
    /// Original: float frametime;
    /// </remarks>
    public float frametime;
    /// <summary>
    /// Client time
    /// </summary>
    /// <remarks>
    /// Original: float time;
    /// </remarks>
    public float time;
    /// <summary>
    /// Misc
    /// </summary>
    /// <remarks>
    /// Original: int intermission;
    /// </remarks>
    public int intermission;
    /// <remarks>
    /// Original: int paused;
    /// </remarks>
    public int paused;
    /// <remarks>
    /// Original: int spectator;
    /// </remarks>
    public int spectator;
    /// <remarks>
    /// Original: int onground;
    /// </remarks>
    public int onground;
    /// <remarks>
    /// Original: int waterlevel;
    /// </remarks>
    public int waterlevel;
    /// <remarks>
    /// Original: float simvel[3];
    /// </remarks>
    public InlineArray3<float> simvel;
    /// <remarks>
    /// Original: float simorg[3];
    /// </remarks>
    public InlineArray3<float> simorg;
    /// <remarks>
    /// Original: float viewheight[3];
    /// </remarks>
    public InlineArray3<float> viewheight;
    /// <remarks>
    /// Original: float idealpitch;
    /// </remarks>
    public float idealpitch;
    /// <remarks>
    /// Original: float cl_viewangles[3];
    /// </remarks>
    public InlineArray3<float> cl_viewangles;
    /// <remarks>
    /// Original: int health;
    /// </remarks>
    public int health;
    /// <remarks>
    /// Original: float crosshairangle[3];
    /// </remarks>
    public InlineArray3<float> crosshairangle;
    /// <remarks>
    /// Original: float viewsize;
    /// </remarks>
    public float viewsize;
    /// <remarks>
    /// Original: float punchangle[3];
    /// </remarks>
    public InlineArray3<float> punchangle;
    /// <remarks>
    /// Original: int maxclients;
    /// </remarks>
    public int maxclients;
    /// <remarks>
    /// Original: int viewentity;
    /// </remarks>
    public int viewentity;
    /// <remarks>
    /// Original: int playernum;
    /// </remarks>
    public int playernum;
    /// <remarks>
    /// Original: int max_entities;
    /// </remarks>
    public int max_entities;
    /// <remarks>
    /// Original: int demoplayback;
    /// </remarks>
    public int demoplayback;
    /// <remarks>
    /// Original: int hardware;
    /// </remarks>
    public int hardware;
    /// <remarks>
    /// Original: int smoothing;
    /// </remarks>
    public int smoothing;
    /// <summary>
    /// Last issued usercmd
    /// </summary>
    /// <remarks>
    /// Original: struct usercmd_s* cmd;
    /// </remarks>
    public usercmd_t* cmd;
    /// <summary>
    /// Movevars
    /// </summary>
    /// <remarks>
    /// Original: struct movevars_s* movevars;
    /// </remarks>
    public movevars_t* movevars;
    /// <summary>
    /// the viewport coordinates x ,y , width, height
    /// </summary>
    /// <remarks>
    /// Original: int viewport[4]; // the viewport coordinates x ,y , width, height
    /// </remarks>
    public InlineArray4<int> viewport;
    /// <summary>
    /// the renderer calls ClientDLL_CalcRefdef() and Renderview
    /// </summary>
    /// <remarks>
    /// Original: int nextView;		// the renderer calls ClientDLL_CalcRefdef() and Renderview
    /// </remarks>
    public int nextView;
    /// <summary>
    /// if !=0 nothing is drawn by the engine except clientDraw functions
    /// </summary>
    /// <remarks>
    /// Original: int onlyClientDraw; // if !=0 nothing is drawn by the engine except clientDraw functions
    /// </remarks>
    public int onlyClientDraw;
}

