// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct screenfade_s { float fadeSpeed;					 // How fast to fade (tics / second) (+ fade in, - fade out) float fadeEnd;						 // When the fading hits maximum float fadeTotalEnd;					 // Total End Time of the fade (used for FFADE_O...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct screenfade_t
{
    /// <summary>
    /// How fast to fade (tics / second) (+ fade in, - fade out)
    /// </summary>
    /// <remarks>
    /// Original: float fadeSpeed;					 // How fast to fade (tics / second) (+ fade in, - fade out)
    /// </remarks>
    public float fadeSpeed;
    /// <summary>
    /// When the fading hits maximum
    /// </summary>
    /// <remarks>
    /// Original: float fadeEnd;						 // When the fading hits maximum
    /// </remarks>
    public float fadeEnd;
    /// <summary>
    /// Total End Time of the fade (used for FFADE_OUT)
    /// </summary>
    /// <remarks>
    /// Original: float fadeTotalEnd;					 // Total End Time of the fade (used for FFADE_OUT)
    /// </remarks>
    public float fadeTotalEnd;
    /// <summary>
    /// When to reset to not fading (for fadeout and hold)
    /// </summary>
    /// <remarks>
    /// Original: float fadeReset;					 // When to reset to not fading (for fadeout and hold)
    /// </remarks>
    public float fadeReset;
    /// <summary>
    /// Fade color
    /// </summary>
    /// <remarks>
    /// Original: byte fader, fadeg, fadeb, fadealpha; // Fade color
    /// </remarks>
    public byte fader;
    /// <summary>
    /// Fade color
    /// </summary>
    /// <remarks>
    /// Original: byte fader, fadeg, fadeb, fadealpha; // Fade color
    /// </remarks>
    public byte fadeg;
    /// <summary>
    /// Fade color
    /// </summary>
    /// <remarks>
    /// Original: byte fader, fadeg, fadeb, fadealpha; // Fade color
    /// </remarks>
    public byte fadeb;
    /// <summary>
    /// Fade color
    /// </summary>
    /// <remarks>
    /// Original: byte fader, fadeg, fadeb, fadealpha; // Fade color
    /// </remarks>
    public byte fadealpha;
    /// <summary>
    /// Fading flags
    /// </summary>
    /// <remarks>
    /// Original: int fadeFlags;						 // Fading flags
    /// </remarks>
    public int fadeFlags;
}

