// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct con_nprint_s { int index;			// Row # float time_to_live; // # of seconds before it dissappears float color[3];		// RGB colors ( 0.0 -&gt; 1.0 scale ) } con_nprint_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct con_nprint_t
{
    /// <summary>
    /// Row #
    /// </summary>
    /// <remarks>
    /// Original: int index;			// Row #
    /// </remarks>
    public int index;
    /// <summary>
    /// # of seconds before it dissappears
    /// </summary>
    /// <remarks>
    /// Original: float time_to_live; // # of seconds before it dissappears
    /// </remarks>
    public float time_to_live;
    /// <summary>
    /// RGB colors ( 0.0 -&gt; 1.0 scale )
    /// </summary>
    /// <remarks>
    /// Original: float color[3];		// RGB colors ( 0.0 -&gt; 1.0 scale )
    /// </remarks>
    public InlineArray3<float> color;
}

