// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct IVoiceTweak_s { // These turn voice tweak mode on and off. While in voice tweak mode, the user's voice is echoed back // without sending to the server. int (*StartVoiceTweakMode)(); // Returns 0 on error. void (*EndVoiceTw...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct IVoiceTweak
{
    /// <summary>
    /// Returns 0 on error.
    /// </summary>
    /// <remarks>
    /// Original: int (*StartVoiceTweakMode)(); // Returns 0 on error.
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> StartVoiceTweakMode;
    /// <remarks>
    /// Original: void (*EndVoiceTweakMode)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> EndVoiceTweakMode;
    /// <summary>
    /// Get/set control values.
    /// </summary>
    /// <remarks>
    /// Original: void (*SetControlFloat)(VoiceTweakControl iControl, float value);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<VoiceTweakControl, float, void> SetControlFloat;
    /// <remarks>
    /// Original: float (*GetControlFloat)(VoiceTweakControl iControl);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<VoiceTweakControl, float> GetControlFloat;
    /// <remarks>
    /// Original: int (*GetSpeakingVolume)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> GetSpeakingVolume;
}

