// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// These provide access to the voice controls.
/// </summary>
/// <remarks>
/// Original: typedef enum { MicrophoneVolume = 0, // values 0-1. OtherSpeakerScale,	  // values 0-1. Scales how loud other players are. MicBoost,			  // 20 db gain to voice input } VoiceTweakControl;
/// </remarks>
public enum VoiceTweakControl
{
    MicrophoneVolume = 0,
    OtherSpeakerScale = 1,
    MicBoost = 2,
}

