// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: struct edict_s { qboolean free; int serialnumber; link_t area; // linked to a division node or leaf int headnode; // -1 to use normal leaf check int num_leafs; short leafnums[MAX_ENT_LEAFS]; float freetime; // sv.time when the object was...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct edict_t
{
    /// <remarks>
    /// Original: qboolean free;
    /// </remarks>
    public qboolean free;
    /// <remarks>
    /// Original: int serialnumber;
    /// </remarks>
    public int serialnumber;
    /// <summary>
    /// linked to a division node or leaf
    /// </summary>
    /// <remarks>
    /// Original: link_t area; // linked to a division node or leaf
    /// </remarks>
    public link_t area;
    /// <summary>
    /// -1 to use normal leaf check
    /// </summary>
    /// <remarks>
    /// Original: int headnode; // -1 to use normal leaf check
    /// </remarks>
    public int headnode;
    /// <remarks>
    /// Original: int num_leafs;
    /// </remarks>
    public int num_leafs;
    /// <remarks>
    /// Original: short leafnums[MAX_ENT_LEAFS];
    /// </remarks>
    public InlineArray48<short> leafnums;
    /// <summary>
    /// sv.time when the object was freed
    /// </summary>
    /// <remarks>
    /// Original: float freetime; // sv.time when the object was freed
    /// </remarks>
    public float freetime;
    /// <summary>
    /// Alloced and freed by engine, used by DLLs
    /// </summary>
    /// <remarks>
    /// Original: void* pvPrivateData; // Alloced and freed by engine, used by DLLs
    /// </remarks>
    public void* pvPrivateData;
    /// <summary>
    /// C exported fields from progs
    /// </summary>
    /// <remarks>
    /// Original: entvars_t v; // C exported fields from progs
    /// </remarks>
    public entvars_t v;
}

