// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: struct entity_state_s { // Fields which are filled in by routines outside of delta compression int entityType; // Index into cl_entities array for this entity. int number; float msg_time; // Message number last time the player/entity sta...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct entity_state_t
{
    /// <summary>
    /// Fields which are filled in by routines outside of delta compression
    /// </summary>
    /// <remarks>
    /// Original: int entityType;
    /// </remarks>
    public int entityType;
    /// <summary>
    /// Index into cl_entities array for this entity.
    /// </summary>
    /// <remarks>
    /// Original: int number;
    /// </remarks>
    public int number;
    /// <remarks>
    /// Original: float msg_time;
    /// </remarks>
    public float msg_time;
    /// <summary>
    /// Message number last time the player/entity state was updated.
    /// </summary>
    /// <remarks>
    /// Original: int messagenum;
    /// </remarks>
    public int messagenum;
    /// <summary>
    /// Fields which can be transitted and reconstructed over the network stream
    /// </summary>
    /// <remarks>
    /// Original: Vector origin;
    /// </remarks>
    public Vector3 origin;
    /// <remarks>
    /// Original: Vector angles;
    /// </remarks>
    public Vector3 angles;
    /// <remarks>
    /// Original: int modelindex;
    /// </remarks>
    public int modelindex;
    /// <remarks>
    /// Original: int sequence;
    /// </remarks>
    public int sequence;
    /// <remarks>
    /// Original: float frame;
    /// </remarks>
    public float frame;
    /// <remarks>
    /// Original: int colormap;
    /// </remarks>
    public int colormap;
    /// <remarks>
    /// Original: short skin;
    /// </remarks>
    public short skin;
    /// <remarks>
    /// Original: short solid;
    /// </remarks>
    public short solid;
    /// <remarks>
    /// Original: int effects;
    /// </remarks>
    public int effects;
    /// <remarks>
    /// Original: float scale;
    /// </remarks>
    public float scale;
    /// <remarks>
    /// Original: byte eflags;
    /// </remarks>
    public byte eflags;
    /// <summary>
    /// Render information
    /// </summary>
    /// <remarks>
    /// Original: int rendermode;
    /// </remarks>
    public int rendermode;
    /// <remarks>
    /// Original: int renderamt;
    /// </remarks>
    public int renderamt;
    /// <remarks>
    /// Original: color24 rendercolor;
    /// </remarks>
    public color24 rendercolor;
    /// <remarks>
    /// Original: int renderfx;
    /// </remarks>
    public int renderfx;
    /// <remarks>
    /// Original: int movetype;
    /// </remarks>
    public int movetype;
    /// <remarks>
    /// Original: float animtime;
    /// </remarks>
    public float animtime;
    /// <remarks>
    /// Original: float framerate;
    /// </remarks>
    public float framerate;
    /// <remarks>
    /// Original: int body;
    /// </remarks>
    public int body;
    /// <remarks>
    /// Original: byte controller[4];
    /// </remarks>
    public InlineArray4<byte> controller;
    /// <remarks>
    /// Original: byte blending[4];
    /// </remarks>
    public InlineArray4<byte> blending;
    /// <remarks>
    /// Original: Vector velocity;
    /// </remarks>
    public Vector3 velocity;
    /// <summary>
    /// Send bbox down to client for use during prediction.
    /// </summary>
    /// <remarks>
    /// Original: Vector mins;
    /// </remarks>
    public Vector3 mins;
    /// <remarks>
    /// Original: Vector maxs;
    /// </remarks>
    public Vector3 maxs;
    /// <remarks>
    /// Original: int aiment;
    /// </remarks>
    public int aiment;
    /// <summary>
    /// If owned by a player, the index of that player ( for projectiles ).
    /// </summary>
    /// <remarks>
    /// Original: int owner;
    /// </remarks>
    public int owner;
    /// <summary>
    /// Friction, for prediction.
    /// </summary>
    /// <remarks>
    /// Original: float friction;
    /// </remarks>
    public float friction;
    /// <summary>
    /// Gravity multiplier
    /// </summary>
    /// <remarks>
    /// Original: float gravity;
    /// </remarks>
    public float gravity;
    /// <summary>
    /// PLAYER SPECIFIC
    /// </summary>
    /// <remarks>
    /// Original: int team;
    /// </remarks>
    public int team;
    /// <remarks>
    /// Original: int playerclass;
    /// </remarks>
    public int playerclass;
    /// <remarks>
    /// Original: int health;
    /// </remarks>
    public int health;
    /// <remarks>
    /// Original: qboolean spectator;
    /// </remarks>
    public qboolean spectator;
    /// <remarks>
    /// Original: int weaponmodel;
    /// </remarks>
    public int weaponmodel;
    /// <remarks>
    /// Original: int gaitsequence;
    /// </remarks>
    public int gaitsequence;
    /// <summary>
    /// If standing on conveyor, e.g.
    /// </summary>
    /// <remarks>
    /// Original: Vector basevelocity;
    /// </remarks>
    public Vector3 basevelocity;
    /// <summary>
    /// Use the crouched hull, or the regular player hull.
    /// </summary>
    /// <remarks>
    /// Original: int usehull;
    /// </remarks>
    public int usehull;
    /// <summary>
    /// Latched buttons last time state updated.
    /// </summary>
    /// <remarks>
    /// Original: int oldbuttons;
    /// </remarks>
    public int oldbuttons;
    /// <summary>
    /// -1 = in air, else pmove entity number
    /// </summary>
    /// <remarks>
    /// Original: int onground;
    /// </remarks>
    public int onground;
    /// <remarks>
    /// Original: int iStepLeft;
    /// </remarks>
    public int iStepLeft;
    /// <summary>
    /// How fast we are falling
    /// </summary>
    /// <remarks>
    /// Original: float flFallVelocity;
    /// </remarks>
    public float flFallVelocity;
    /// <remarks>
    /// Original: float fov;
    /// </remarks>
    public float fov;
    /// <remarks>
    /// Original: int weaponanim;
    /// </remarks>
    public int weaponanim;
    /// <summary>
    /// Parametric movement overrides
    /// </summary>
    /// <remarks>
    /// Original: Vector startpos;
    /// </remarks>
    public Vector3 startpos;
    /// <remarks>
    /// Original: Vector endpos;
    /// </remarks>
    public Vector3 endpos;
    /// <remarks>
    /// Original: float impacttime;
    /// </remarks>
    public float impacttime;
    /// <remarks>
    /// Original: float starttime;
    /// </remarks>
    public float starttime;
    /// <summary>
    /// For mods
    /// </summary>
    /// <remarks>
    /// Original: int iuser1;
    /// </remarks>
    public int iuser1;
    /// <remarks>
    /// Original: int iuser2;
    /// </remarks>
    public int iuser2;
    /// <remarks>
    /// Original: int iuser3;
    /// </remarks>
    public int iuser3;
    /// <remarks>
    /// Original: int iuser4;
    /// </remarks>
    public int iuser4;
    /// <remarks>
    /// Original: float fuser1;
    /// </remarks>
    public float fuser1;
    /// <remarks>
    /// Original: float fuser2;
    /// </remarks>
    public float fuser2;
    /// <remarks>
    /// Original: float fuser3;
    /// </remarks>
    public float fuser3;
    /// <remarks>
    /// Original: float fuser4;
    /// </remarks>
    public float fuser4;
    /// <remarks>
    /// Original: Vector vuser1;
    /// </remarks>
    public Vector3 vuser1;
    /// <remarks>
    /// Original: Vector vuser2;
    /// </remarks>
    public Vector3 vuser2;
    /// <remarks>
    /// Original: Vector vuser3;
    /// </remarks>
    public Vector3 vuser3;
    /// <remarks>
    /// Original: Vector vuser4;
    /// </remarks>
    public Vector3 vuser4;
}

