// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct entvars_s { string_t classname; string_t globalname; Vector origin; Vector oldorigin; Vector velocity; Vector basevelocity; Vector clbasevelocity; // Base velocity that was passed in to server physics so //  client can pre...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct entvars_t
{
    /// <remarks>
    /// Original: string_t classname;
    /// </remarks>
    public string_t classname;
    /// <remarks>
    /// Original: string_t globalname;
    /// </remarks>
    public string_t globalname;
    /// <remarks>
    /// Original: Vector origin;
    /// </remarks>
    public Vector3 origin;
    /// <remarks>
    /// Original: Vector oldorigin;
    /// </remarks>
    public Vector3 oldorigin;
    /// <remarks>
    /// Original: Vector velocity;
    /// </remarks>
    public Vector3 velocity;
    /// <remarks>
    /// Original: Vector basevelocity;
    /// </remarks>
    public Vector3 basevelocity;
    /// <summary>
    /// Base velocity that was passed in to server physics so
    /// </summary>
    /// <remarks>
    /// Original: Vector clbasevelocity; // Base velocity that was passed in to server physics so
    /// </remarks>
    public Vector3 clbasevelocity;
    /// <summary>
    /// client can predict conveyors correctly.  Server zeroes it, so we need to store here, too.
    /// </summary>
    /// <remarks>
    /// Original: Vector movedir;
    /// </remarks>
    public Vector3 movedir;
    /// <summary>
    /// Model angles
    /// </summary>
    /// <remarks>
    /// Original: Vector angles;	   // Model angles
    /// </remarks>
    public Vector3 angles;
    /// <summary>
    /// angle velocity (degrees per second)
    /// </summary>
    /// <remarks>
    /// Original: Vector avelocity;  // angle velocity (degrees per second)
    /// </remarks>
    public Vector3 avelocity;
    /// <summary>
    /// auto-decaying view angle adjustment
    /// </summary>
    /// <remarks>
    /// Original: Vector punchangle; // auto-decaying view angle adjustment
    /// </remarks>
    public Vector3 punchangle;
    /// <summary>
    /// Viewing angle (player only)
    /// </summary>
    /// <remarks>
    /// Original: Vector v_angle;	   // Viewing angle (player only)
    /// </remarks>
    public Vector3 v_angle;
    /// <summary>
    /// For parametric entities
    /// </summary>
    /// <remarks>
    /// Original: Vector endpos;
    /// </remarks>
    public Vector3 endpos;
    /// <remarks>
    /// Original: Vector startpos;
    /// </remarks>
    public Vector3 startpos;
    /// <remarks>
    /// Original: float impacttime;
    /// </remarks>
    public float impacttime;
    /// <remarks>
    /// Original: float starttime;
    /// </remarks>
    public float starttime;
    /// <summary>
    /// 0:nothing, 1:force view angles, 2:add avelocity
    /// </summary>
    /// <remarks>
    /// Original: int fixangle; // 0:nothing, 1:force view angles, 2:add avelocity
    /// </remarks>
    public int fixangle;
    /// <remarks>
    /// Original: float idealpitch;
    /// </remarks>
    public float idealpitch;
    /// <remarks>
    /// Original: float pitch_speed;
    /// </remarks>
    public float pitch_speed;
    /// <remarks>
    /// Original: float ideal_yaw;
    /// </remarks>
    public float ideal_yaw;
    /// <remarks>
    /// Original: float yaw_speed;
    /// </remarks>
    public float yaw_speed;
    /// <remarks>
    /// Original: int modelindex;
    /// </remarks>
    public int modelindex;
    /// <remarks>
    /// Original: string_t model;
    /// </remarks>
    public string_t model;
    /// <summary>
    /// player's viewmodel
    /// </summary>
    /// <remarks>
    /// Original: int viewmodel;	 // player's viewmodel
    /// </remarks>
    public int viewmodel;
    /// <summary>
    /// what other players see
    /// </summary>
    /// <remarks>
    /// Original: int weaponmodel; // what other players see
    /// </remarks>
    public int weaponmodel;
    /// <summary>
    /// BB max translated to world coord
    /// </summary>
    /// <remarks>
    /// Original: Vector absmin; // BB max translated to world coord
    /// </remarks>
    public Vector3 absmin;
    /// <summary>
    /// BB max translated to world coord
    /// </summary>
    /// <remarks>
    /// Original: Vector absmax; // BB max translated to world coord
    /// </remarks>
    public Vector3 absmax;
    /// <summary>
    /// local BB min
    /// </summary>
    /// <remarks>
    /// Original: Vector mins;   // local BB min
    /// </remarks>
    public Vector3 mins;
    /// <summary>
    /// local BB max
    /// </summary>
    /// <remarks>
    /// Original: Vector maxs;   // local BB max
    /// </remarks>
    public Vector3 maxs;
    /// <summary>
    /// maxs - mins
    /// </summary>
    /// <remarks>
    /// Original: Vector size;   // maxs - mins
    /// </remarks>
    public Vector3 size;
    /// <remarks>
    /// Original: float ltime;
    /// </remarks>
    public float ltime;
    /// <remarks>
    /// Original: float nextthink;
    /// </remarks>
    public float nextthink;
    /// <remarks>
    /// Original: int movetype;
    /// </remarks>
    public int movetype;
    /// <remarks>
    /// Original: int solid;
    /// </remarks>
    public int solid;
    /// <remarks>
    /// Original: int skin;
    /// </remarks>
    public int skin;
    /// <summary>
    /// sub-model selection for studiomodels
    /// </summary>
    /// <remarks>
    /// Original: int body; // sub-model selection for studiomodels
    /// </remarks>
    public int body;
    /// <remarks>
    /// Original: int effects;
    /// </remarks>
    public int effects;
    /// <summary>
    /// % of "normal" gravity
    /// </summary>
    /// <remarks>
    /// Original: float gravity;	// % of "normal" gravity
    /// </remarks>
    public float gravity;
    /// <summary>
    /// inverse elasticity of MOVETYPE_BOUNCE
    /// </summary>
    /// <remarks>
    /// Original: float friction; // inverse elasticity of MOVETYPE_BOUNCE
    /// </remarks>
    public float friction;
    /// <remarks>
    /// Original: int light_level;
    /// </remarks>
    public int light_level;
    /// <summary>
    /// animation sequence
    /// </summary>
    /// <remarks>
    /// Original: int sequence;							// animation sequence
    /// </remarks>
    public int sequence;
    /// <summary>
    /// movement animation sequence for player (0 for none)
    /// </summary>
    /// <remarks>
    /// Original: int gaitsequence;						// movement animation sequence for player (0 for none)
    /// </remarks>
    public int gaitsequence;
    /// <summary>
    /// % playback position in animation sequences (0..255)
    /// </summary>
    /// <remarks>
    /// Original: float frame;							// % playback position in animation sequences (0..255)
    /// </remarks>
    public float frame;
    /// <summary>
    /// world time when frame was set
    /// </summary>
    /// <remarks>
    /// Original: float animtime;							// world time when frame was set
    /// </remarks>
    public float animtime;
    /// <summary>
    /// animation playback rate (-8x to 8x)
    /// </summary>
    /// <remarks>
    /// Original: float framerate;						// animation playback rate (-8x to 8x)
    /// </remarks>
    public float framerate;
    /// <summary>
    /// bone controller setting (0..255)
    /// </summary>
    /// <remarks>
    /// Original: byte controller[NUM_ENT_CONTROLLERS];	// bone controller setting (0..255)
    /// </remarks>
    public InlineArray4<byte> controller;
    /// <summary>
    /// blending amount between sub-sequences (0..255)
    /// </summary>
    /// <remarks>
    /// Original: byte blending[NUM_ENT_BLENDERS];		// blending amount between sub-sequences (0..255)
    /// </remarks>
    public InlineArray2<byte> blending;
    /// <summary>
    /// sprite rendering scale (0..255)
    /// </summary>
    /// <remarks>
    /// Original: float scale; // sprite rendering scale (0..255)
    /// </remarks>
    public float scale;
    /// <remarks>
    /// Original: int rendermode;
    /// </remarks>
    public int rendermode;
    /// <remarks>
    /// Original: float renderamt;
    /// </remarks>
    public float renderamt;
    /// <remarks>
    /// Original: Vector rendercolor;
    /// </remarks>
    public Vector3 rendercolor;
    /// <remarks>
    /// Original: int renderfx;
    /// </remarks>
    public int renderfx;
    /// <remarks>
    /// Original: float health;
    /// </remarks>
    public float health;
    /// <remarks>
    /// Original: float frags;
    /// </remarks>
    public float frags;
    /// <summary>
    /// bit mask for available weapons
    /// </summary>
    /// <remarks>
    /// Original: int weapons; // bit mask for available weapons
    /// </remarks>
    public int weapons;
    /// <remarks>
    /// Original: float takedamage;
    /// </remarks>
    public float takedamage;
    /// <remarks>
    /// Original: int deadflag;
    /// </remarks>
    public int deadflag;
    /// <summary>
    /// eye position
    /// </summary>
    /// <remarks>
    /// Original: Vector view_ofs; // eye position
    /// </remarks>
    public Vector3 view_ofs;
    /// <remarks>
    /// Original: int button;
    /// </remarks>
    public int button;
    /// <remarks>
    /// Original: int impulse;
    /// </remarks>
    public int impulse;
    /// <summary>
    /// Entity pointer when linked into a linked list
    /// </summary>
    /// <remarks>
    /// Original: edict_t* chain; // Entity pointer when linked into a linked list
    /// </remarks>
    public edict_t* chain;
    /// <remarks>
    /// Original: edict_t* dmg_inflictor;
    /// </remarks>
    public edict_t* dmg_inflictor;
    /// <remarks>
    /// Original: edict_t* enemy;
    /// </remarks>
    public edict_t* enemy;
    /// <summary>
    /// entity pointer when MOVETYPE_FOLLOW
    /// </summary>
    /// <remarks>
    /// Original: edict_t* aiment; // entity pointer when MOVETYPE_FOLLOW
    /// </remarks>
    public edict_t* aiment;
    /// <remarks>
    /// Original: edict_t* owner;
    /// </remarks>
    public edict_t* owner;
    /// <remarks>
    /// Original: edict_t* groundentity;
    /// </remarks>
    public edict_t* groundentity;
    /// <remarks>
    /// Original: int spawnflags;
    /// </remarks>
    public int spawnflags;
    /// <remarks>
    /// Original: int flags;
    /// </remarks>
    public int flags;
    /// <summary>
    /// lowbyte topcolor, highbyte bottomcolor
    /// </summary>
    /// <remarks>
    /// Original: int colormap; // lowbyte topcolor, highbyte bottomcolor
    /// </remarks>
    public int colormap;
    /// <remarks>
    /// Original: int team;
    /// </remarks>
    public int team;
    /// <remarks>
    /// Original: float max_health;
    /// </remarks>
    public float max_health;
    /// <remarks>
    /// Original: float teleport_time;
    /// </remarks>
    public float teleport_time;
    /// <remarks>
    /// Original: float armortype;
    /// </remarks>
    public float armortype;
    /// <remarks>
    /// Original: float armorvalue;
    /// </remarks>
    public float armorvalue;
    /// <remarks>
    /// Original: int waterlevel;
    /// </remarks>
    public int waterlevel;
    /// <remarks>
    /// Original: int watertype;
    /// </remarks>
    public int watertype;
    /// <remarks>
    /// Original: string_t target;
    /// </remarks>
    public string_t target;
    /// <remarks>
    /// Original: string_t targetname;
    /// </remarks>
    public string_t targetname;
    /// <remarks>
    /// Original: string_t netname;
    /// </remarks>
    public string_t netname;
    /// <remarks>
    /// Original: string_t message;
    /// </remarks>
    public string_t message;
    /// <remarks>
    /// Original: float dmg_take;
    /// </remarks>
    public float dmg_take;
    /// <remarks>
    /// Original: float dmg_save;
    /// </remarks>
    public float dmg_save;
    /// <remarks>
    /// Original: float dmg;
    /// </remarks>
    public float dmg;
    /// <remarks>
    /// Original: float dmgtime;
    /// </remarks>
    public float dmgtime;
    /// <remarks>
    /// Original: string_t noise;
    /// </remarks>
    public string_t noise;
    /// <remarks>
    /// Original: string_t noise1;
    /// </remarks>
    public string_t noise1;
    /// <remarks>
    /// Original: string_t noise2;
    /// </remarks>
    public string_t noise2;
    /// <remarks>
    /// Original: string_t noise3;
    /// </remarks>
    public string_t noise3;
    /// <remarks>
    /// Original: float speed;
    /// </remarks>
    public float speed;
    /// <remarks>
    /// Original: float air_finished;
    /// </remarks>
    public float air_finished;
    /// <remarks>
    /// Original: float pain_finished;
    /// </remarks>
    public float pain_finished;
    /// <remarks>
    /// Original: float radsuit_finished;
    /// </remarks>
    public float radsuit_finished;
    /// <remarks>
    /// Original: edict_t* pContainingEntity;
    /// </remarks>
    public edict_t* pContainingEntity;
    /// <remarks>
    /// Original: int playerclass;
    /// </remarks>
    public int playerclass;
    /// <remarks>
    /// Original: float maxspeed;
    /// </remarks>
    public float maxspeed;
    /// <remarks>
    /// Original: float fov;
    /// </remarks>
    public float fov;
    /// <remarks>
    /// Original: int weaponanim;
    /// </remarks>
    public int weaponanim;
    /// <remarks>
    /// Original: int pushmsec;
    /// </remarks>
    public int pushmsec;
    /// <remarks>
    /// Original: int bInDuck;
    /// </remarks>
    public int bInDuck;
    /// <remarks>
    /// Original: int flTimeStepSound;
    /// </remarks>
    public int flTimeStepSound;
    /// <remarks>
    /// Original: int flSwimTime;
    /// </remarks>
    public int flSwimTime;
    /// <remarks>
    /// Original: int flDuckTime;
    /// </remarks>
    public int flDuckTime;
    /// <remarks>
    /// Original: int iStepLeft;
    /// </remarks>
    public int iStepLeft;
    /// <remarks>
    /// Original: float flFallVelocity;
    /// </remarks>
    public float flFallVelocity;
    /// <remarks>
    /// Original: int gamestate;
    /// </remarks>
    public int gamestate;
    /// <remarks>
    /// Original: int oldbuttons;
    /// </remarks>
    public int oldbuttons;
    /// <remarks>
    /// Original: int groupinfo;
    /// </remarks>
    public int groupinfo;
    /// <summary>
    /// For mods
    /// </summary>
    /// <remarks>
    /// Original: int iuser1;
    /// </remarks>
    public int iuser1;
    /// <remarks>
    /// Original: int iuser2;
    /// </remarks>
    public int iuser2;
    /// <remarks>
    /// Original: int iuser3;
    /// </remarks>
    public int iuser3;
    /// <remarks>
    /// Original: int iuser4;
    /// </remarks>
    public int iuser4;
    /// <remarks>
    /// Original: float fuser1;
    /// </remarks>
    public float fuser1;
    /// <remarks>
    /// Original: float fuser2;
    /// </remarks>
    public float fuser2;
    /// <remarks>
    /// Original: float fuser3;
    /// </remarks>
    public float fuser3;
    /// <remarks>
    /// Original: float fuser4;
    /// </remarks>
    public float fuser4;
    /// <remarks>
    /// Original: Vector vuser1;
    /// </remarks>
    public Vector3 vuser1;
    /// <remarks>
    /// Original: Vector vuser2;
    /// </remarks>
    public Vector3 vuser2;
    /// <remarks>
    /// Original: Vector vuser3;
    /// </remarks>
    public Vector3 vuser3;
    /// <remarks>
    /// Original: Vector vuser4;
    /// </remarks>
    public Vector3 vuser4;
    /// <remarks>
    /// Original: edict_t* euser1;
    /// </remarks>
    public edict_t* euser1;
    /// <remarks>
    /// Original: edict_t* euser2;
    /// </remarks>
    public edict_t* euser2;
    /// <remarks>
    /// Original: edict_t* euser3;
    /// </remarks>
    public edict_t* euser3;
    /// <remarks>
    /// Original: edict_t* euser4;
    /// </remarks>
    public edict_t* euser4;
}

