// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// Passed to pfnKeyValue
/// </summary>
/// <remarks>
/// Original: typedef struct KeyValueData_s { const char* szClassName; // in: entity classname const char* szKeyName;	 // in: name of key const char* szValue;	 // in: value of key int32 fHandled;			 // out: DLL sets to true if key-value pair was under...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct KeyValueData
{
    /// <summary>
    /// in: entity classname
    /// </summary>
    /// <remarks>
    /// Original: const char* szClassName; // in: entity classname
    /// </remarks>
    public NChar* szClassName;
    /// <summary>
    /// in: name of key
    /// </summary>
    /// <remarks>
    /// Original: const char* szKeyName;	 // in: name of key
    /// </remarks>
    public NChar* szKeyName;
    /// <summary>
    /// in: value of key
    /// </summary>
    /// <remarks>
    /// Original: const char* szValue;	 // in: value of key
    /// </remarks>
    public NChar* szValue;
    /// <summary>
    /// out: DLL sets to true if key-value pair was understood
    /// </summary>
    /// <remarks>
    /// Original: int32 fHandled;			 // out: DLL sets to true if key-value pair was understood
    /// </remarks>
    public int fHandled;
}

