// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct { unsigned r, g, b, a; } colorVec;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct colorVec
{
    /// <remarks>
    /// Original: unsigned r, g, b, a;
    /// </remarks>
    public uint r;
    /// <remarks>
    /// Original: unsigned r, g, b, a;
    /// </remarks>
    public uint g;
    /// <remarks>
    /// Original: unsigned r, g, b, a;
    /// </remarks>
    public uint b;
    /// <remarks>
    /// Original: unsigned r, g, b, a;
    /// </remarks>
    public uint a;
}

