// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct { byte r, g, b; } color24;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct color24
{
    /// <remarks>
    /// Original: byte r, g, b;
    /// </remarks>
    public byte r;
    /// <remarks>
    /// Original: byte r, g, b;
    /// </remarks>
    public byte g;
    /// <remarks>
    /// Original: byte r, g, b;
    /// </remarks>
    public byte b;
}

