// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct link_s { struct link_s *prev, *next; } link_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct link_t
{
    /// <remarks>
    /// Original: struct link_s *prev, *next;
    /// </remarks>
    public link_t* prev;
    /// <remarks>
    /// Original: struct link_s *prev, *next;
    /// </remarks>
    public link_t* next;
}

