// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct { qboolean allsolid;	 // if true, plane is not valid qboolean startsolid; // if true, the initial point was in a solid area qboolean inopen, inwater; float fraction; // time completed, 1.0 = didn't hit anything Vector endp...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct trace_t
{
    /// <summary>
    /// if true, plane is not valid
    /// </summary>
    /// <remarks>
    /// Original: qboolean allsolid;	 // if true, plane is not valid
    /// </remarks>
    public qboolean allsolid;
    /// <summary>
    /// if true, the initial point was in a solid area
    /// </summary>
    /// <remarks>
    /// Original: qboolean startsolid; // if true, the initial point was in a solid area
    /// </remarks>
    public qboolean startsolid;
    /// <remarks>
    /// Original: qboolean inopen, inwater;
    /// </remarks>
    public qboolean inopen;
    /// <remarks>
    /// Original: qboolean inopen, inwater;
    /// </remarks>
    public qboolean inwater;
    /// <summary>
    /// time completed, 1.0 = didn't hit anything
    /// </summary>
    /// <remarks>
    /// Original: float fraction; // time completed, 1.0 = didn't hit anything
    /// </remarks>
    public float fraction;
    /// <summary>
    /// final position
    /// </summary>
    /// <remarks>
    /// Original: Vector endpos;	// final position
    /// </remarks>
    public Vector3 endpos;
    /// <summary>
    /// surface normal at impact
    /// </summary>
    /// <remarks>
    /// Original: plane_t plane;	// surface normal at impact
    /// </remarks>
    public plane_t plane;
    /// <summary>
    /// entity the surface is on
    /// </summary>
    /// <remarks>
    /// Original: edict_t* ent;	// entity the surface is on
    /// </remarks>
    public edict_t* ent;
    /// <summary>
    /// 0 == generic, non zero is specific body part
    /// </summary>
    /// <remarks>
    /// Original: int hitgroup;	// 0 == generic, non zero is specific body part
    /// </remarks>
    public int hitgroup;
}

