// <auto-generated/>
// Temporary source-compatibility aliases for older framework code while formal
// Humanizer types replace handwritten native definitions.
global using StudioConstants = GoldsrcFramework.Engine.Native.Deprecation.StudioConstants;
global using StudioMotionFlags = GoldsrcFramework.Engine.Native.Deprecation.StudioMotionFlags;
global using StudioSequenceFlags = GoldsrcFramework.Engine.Native.Deprecation.StudioSequenceFlags;
global using StudioNormalFlags = GoldsrcFramework.Engine.Native.Deprecation.StudioNormalFlags;
global using RenderMode = GoldsrcFramework.Engine.Native.Deprecation.RenderMode;
global using RenderFx = GoldsrcFramework.Engine.Native.Deprecation.RenderFx;

