// <auto-generated/>
// Temporary source-compatibility aliases for older framework code while formal
// Humanizer types replace handwritten native definitions.
global using cl_enginefunc_t = GoldsrcFramework.Engine.Native.ClientEngineFuncs;
global using client_data_t = GoldsrcFramework.Engine.Native.client_data_t;
global using playermove_s = GoldsrcFramework.Engine.Native.playermove_t;
global using usercmd_s = GoldsrcFramework.Engine.Native.usercmd_t;
global using kbutton_s = GoldsrcFramework.Engine.Native.kbutton_t;
global using ref_params_s = GoldsrcFramework.Engine.Native.ref_params_t;
global using cl_entity_s = GoldsrcFramework.Engine.Native.cl_entity_t;
global using mstudioevent_s = GoldsrcFramework.Engine.Native.mstudioevent_t;
global using local_state_s = GoldsrcFramework.Engine.Native.local_state_t;
global using entity_state_s = GoldsrcFramework.Engine.Native.entity_state_t;
global using clientdata_s = GoldsrcFramework.Engine.Native.clientdata_t;
global using weapon_data_s = GoldsrcFramework.Engine.Native.weapon_data_t;
global using netadr_s = GoldsrcFramework.Engine.Native.netadr_t;
global using tempent_s = GoldsrcFramework.Engine.Native.TEMPENTITY;
global using r_studio_interface_s = GoldsrcFramework.Engine.Native.r_studio_interface_t;
global using engine_studio_api_s = GoldsrcFramework.Engine.Native.engine_studio_api_t;
global using customization_t = GoldsrcFramework.Engine.Native.customization_t;
global using qboolean = GoldsrcFramework.Engine.Native.qboolean;
global using HSPRITE = GoldsrcFramework.Engine.Native.HSPRITE;
global using string_t = GoldsrcFramework.Engine.Native.string_t;
global using enginefuncs_s = GoldsrcFramework.Engine.Native.ServerEngineFuncs;
global using globalvars_t = GoldsrcFramework.Engine.Native.Deprecation.globalvars_t;
global using cvar_s = GoldsrcFramework.Engine.Native.cvar_t;
global using model_s = GoldsrcFramework.Engine.Native.model_t;
global using player_info_s = GoldsrcFramework.Engine.Native.player_info_t;
global using server_studio_api_s = GoldsrcFramework.Engine.Native.server_studio_api_t;
global using sv_blending_interface_s = GoldsrcFramework.Engine.Native.sv_blending_interface_t;
global using cache_user_s = GoldsrcFramework.Engine.Native.cache_user_t;
global using alight_s = GoldsrcFramework.Engine.Native.alight_t;
global using StudioConstants = GoldsrcFramework.Engine.Native.Deprecation.StudioConstants;
global using StudioMotionFlags = GoldsrcFramework.Engine.Native.Deprecation.StudioMotionFlags;
global using StudioSequenceFlags = GoldsrcFramework.Engine.Native.Deprecation.StudioSequenceFlags;
global using StudioNormalFlags = GoldsrcFramework.Engine.Native.Deprecation.StudioNormalFlags;
global using RenderMode = GoldsrcFramework.Engine.Native.Deprecation.RenderMode;
global using RenderFx = GoldsrcFramework.Engine.Native.Deprecation.RenderFx;

