// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// Common data types
/// </summary>
/// <remarks>
/// Original: struct Point { int x = 0; int y = 0; };
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct Point
{
    /// <remarks>
    /// Original: int x = 0;
    /// </remarks>
    public int x;
    /// <remarks>
    /// Original: int y = 0;
    /// </remarks>
    public int y;
}

