// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: struct Rect { int left = 0; int right = 0; int top = 0; int bottom = 0; };
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct Rect
{
    /// <remarks>
    /// Original: int left = 0;
    /// </remarks>
    public int left;
    /// <remarks>
    /// Original: int right = 0;
    /// </remarks>
    public int right;
    /// <remarks>
    /// Original: int top = 0;
    /// </remarks>
    public int top;
    /// <remarks>
    /// Original: int bottom = 0;
    /// </remarks>
    public int bottom;
}

