// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// JoshA: Unfortunately netadr_s is passed to clients for connectionless packets.
/// No Valve mod uses them, but custom mods *might*, so not changing the start of this struct layout.
/// It's very unlikely they touch this, but I'd like to play as safe as possible with all ABI etc for mod compat.
/// If we want to add IPv6 someday, bung it at the end of netadr_s and leave ip + ipx alone.
/// </summary>
/// <remarks>
/// Original: typedef enum { NA_UNUSED, NA_LOOPBACK, NA_BROADCAST, NA_IP, NA_IPX, // deprecated NA_BROADCAST_IPX, // deprecated } netadrtype_t;
/// </remarks>
public enum netadrtype_t
{
    NA_UNUSED = 0,
    NA_LOOPBACK = 1,
    NA_BROADCAST = 2,
    NA_IP = 3,
    NA_IPX = 4,
    NA_BROADCAST_IPX = 5,
}

