// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct netadr_s { netadrtype_t type; unsigned char ip[4]; unsigned char ipx[10]; // deprecated unsigned short port; } netadr_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct netadr_t
{
    /// <remarks>
    /// Original: netadrtype_t type;
    /// </remarks>
    public netadrtype_t type;
    /// <remarks>
    /// Original: unsigned char ip[4];
    /// </remarks>
    public InlineArray4<byte> ip;
    /// <summary>
    /// deprecated
    /// </summary>
    /// <remarks>
    /// Original: unsigned char ipx[10]; // deprecated
    /// </remarks>
    public InlineArray10<byte> ipx;
    /// <remarks>
    /// Original: unsigned short port;
    /// </remarks>
    public ushort port;
}

