// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct cvar_s { const char* name; //Technically this should be non-const but that only matters to engine code const char* string; int flags; float value; struct cvar_s* next; } cvar_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct cvar_t
{
    /// <remarks>
    /// Original: const char* name;
    /// </remarks>
    public NChar* name;
    /// <summary>
    /// Technically this should be non-const but that only matters to engine code
    /// </summary>
    /// <remarks>
    /// Original: const char* string;
    /// </remarks>
    public NChar* @string;
    /// <remarks>
    /// Original: int flags;
    /// </remarks>
    public int flags;
    /// <remarks>
    /// Original: float value;
    /// </remarks>
    public float value;
    /// <remarks>
    /// Original: struct cvar_s* next;
    /// </remarks>
    public cvar_t* next;
}

