// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct saverestore_s { char* pBaseData;							// Start of all entity save data char* pCurrentData;							// Current buffer pointer for sequential access int size;									// Current data size int bufferSize;								// Total space...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct SAVERESTOREDATA
{
    /// <summary>
    /// Start of all entity save data
    /// </summary>
    /// <remarks>
    /// Original: char* pBaseData;							// Start of all entity save data
    /// </remarks>
    public NChar* pBaseData;
    /// <summary>
    /// Current buffer pointer for sequential access
    /// </summary>
    /// <remarks>
    /// Original: char* pCurrentData;							// Current buffer pointer for sequential access
    /// </remarks>
    public NChar* pCurrentData;
    /// <summary>
    /// Current data size
    /// </summary>
    /// <remarks>
    /// Original: int size;									// Current data size
    /// </remarks>
    public int size;
    /// <summary>
    /// Total space for data
    /// </summary>
    /// <remarks>
    /// Original: int bufferSize;								// Total space for data
    /// </remarks>
    public int bufferSize;
    /// <summary>
    /// Size of the linear list of tokens
    /// </summary>
    /// <remarks>
    /// Original: int tokenSize;								// Size of the linear list of tokens
    /// </remarks>
    public int tokenSize;
    /// <summary>
    /// Number of elements in the pTokens table
    /// </summary>
    /// <remarks>
    /// Original: int tokenCount;								// Number of elements in the pTokens table
    /// </remarks>
    public int tokenCount;
    /// <summary>
    /// Hash table of entity strings (sparse)
    /// </summary>
    /// <remarks>
    /// Original: char** pTokens;								// Hash table of entity strings (sparse)
    /// </remarks>
    public NChar** pTokens;
    /// <summary>
    /// Holds a global entity table ID
    /// </summary>
    /// <remarks>
    /// Original: int currentIndex;							// Holds a global entity table ID
    /// </remarks>
    public int currentIndex;
    /// <summary>
    /// Number of elements in the entity table
    /// </summary>
    /// <remarks>
    /// Original: int tableCount;								// Number of elements in the entity table
    /// </remarks>
    public int tableCount;
    /// <summary>
    /// Number of elements in the levelList[]
    /// </summary>
    /// <remarks>
    /// Original: int connectionCount;						// Number of elements in the levelList[]
    /// </remarks>
    public int connectionCount;
    /// <summary>
    /// Array of ENTITYTABLE elements (1 for each entity)
    /// </summary>
    /// <remarks>
    /// Original: ENTITYTABLE* pTable;						// Array of ENTITYTABLE elements (1 for each entity)
    /// </remarks>
    public ENTITYTABLE* pTable;
    /// <summary>
    /// List of connections from this level
    /// </summary>
    /// <remarks>
    /// Original: LEVELLIST levelList[MAX_LEVEL_CONNECTIONS]; // List of connections from this level
    /// </remarks>
    public InlineArray16<LEVELLIST> levelList;
    /// <summary>
    /// smooth transition
    /// </summary>
    /// <remarks>
    /// Original: int fUseLandmark;
    /// </remarks>
    public int fUseLandmark;
    /// <summary>
    /// landmark we'll spawn near in next level
    /// </summary>
    /// <remarks>
    /// Original: char szLandmarkName[20];  // landmark we'll spawn near in next level
    /// </remarks>
    public InlineArray20<NChar> szLandmarkName;
    /// <summary>
    /// for landmark transitions
    /// </summary>
    /// <remarks>
    /// Original: Vector vecLandmarkOffset; // for landmark transitions
    /// </remarks>
    public Vector3 vecLandmarkOffset;
    /// <remarks>
    /// Original: float time;
    /// </remarks>
    public float time;
    /// <summary>
    /// To check global entities
    /// </summary>
    /// <remarks>
    /// Original: char szCurrentMapName[32]; // To check global entities
    /// </remarks>
    public InlineArray32<NChar> szCurrentMapName;
}

