// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct { FIELDTYPE fieldType; const char* fieldName; int fieldOffset; short fieldSize; short flags; } TYPEDESCRIPTION;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct TYPEDESCRIPTION
{
    /// <remarks>
    /// Original: FIELDTYPE fieldType;
    /// </remarks>
    public FIELDTYPE fieldType;
    /// <remarks>
    /// Original: const char* fieldName;
    /// </remarks>
    public NChar* fieldName;
    /// <remarks>
    /// Original: int fieldOffset;
    /// </remarks>
    public int fieldOffset;
    /// <remarks>
    /// Original: short fieldSize;
    /// </remarks>
    public short fieldSize;
    /// <remarks>
    /// Original: short flags;
    /// </remarks>
    public short flags;
}

