// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: struct movevars_s { float gravity;	 // Gravity for map float stopspeed; // Deceleration when not moving float maxspeed;	 // Max allowed speed float spectatormaxspeed; float accelerate;	   // Acceleration factor float airaccelerate;   // ...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct movevars_t
{
    /// <summary>
    /// Gravity for map
    /// </summary>
    /// <remarks>
    /// Original: float gravity;	 // Gravity for map
    /// </remarks>
    public float gravity;
    /// <summary>
    /// Deceleration when not moving
    /// </summary>
    /// <remarks>
    /// Original: float stopspeed; // Deceleration when not moving
    /// </remarks>
    public float stopspeed;
    /// <summary>
    /// Max allowed speed
    /// </summary>
    /// <remarks>
    /// Original: float maxspeed;	 // Max allowed speed
    /// </remarks>
    public float maxspeed;
    /// <remarks>
    /// Original: float spectatormaxspeed;
    /// </remarks>
    public float spectatormaxspeed;
    /// <summary>
    /// Acceleration factor
    /// </summary>
    /// <remarks>
    /// Original: float accelerate;	   // Acceleration factor
    /// </remarks>
    public float accelerate;
    /// <summary>
    /// Same for when in open air
    /// </summary>
    /// <remarks>
    /// Original: float airaccelerate;   // Same for when in open air
    /// </remarks>
    public float airaccelerate;
    /// <summary>
    /// Same for when in water
    /// </summary>
    /// <remarks>
    /// Original: float wateraccelerate; // Same for when in water
    /// </remarks>
    public float wateraccelerate;
    /// <remarks>
    /// Original: float friction;
    /// </remarks>
    public float friction;
    /// <summary>
    /// Extra friction near dropofs
    /// </summary>
    /// <remarks>
    /// Original: float edgefriction;	 // Extra friction near dropofs
    /// </remarks>
    public float edgefriction;
    /// <summary>
    /// Less in water
    /// </summary>
    /// <remarks>
    /// Original: float waterfriction; // Less in water
    /// </remarks>
    public float waterfriction;
    /// <summary>
    /// 1.0
    /// </summary>
    /// <remarks>
    /// Original: float entgravity;	 // 1.0
    /// </remarks>
    public float entgravity;
    /// <summary>
    /// Wall bounce value. 1.0
    /// </summary>
    /// <remarks>
    /// Original: float bounce;		 // Wall bounce value. 1.0
    /// </remarks>
    public float bounce;
    /// <summary>
    /// sv_stepsize;
    /// </summary>
    /// <remarks>
    /// Original: float stepsize;		 // sv_stepsize;
    /// </remarks>
    public float stepsize;
    /// <summary>
    /// maximum server velocity.
    /// </summary>
    /// <remarks>
    /// Original: float maxvelocity;	 // maximum server velocity.
    /// </remarks>
    public float maxvelocity;
    /// <summary>
    /// Max z-buffer range (for GL)
    /// </summary>
    /// <remarks>
    /// Original: float zmax;			 // Max z-buffer range (for GL)
    /// </remarks>
    public float zmax;
    /// <summary>
    /// Water wave height (for GL)
    /// </summary>
    /// <remarks>
    /// Original: float waveHeight;	 // Water wave height (for GL)
    /// </remarks>
    public float waveHeight;
    /// <summary>
    /// Play footstep sounds
    /// </summary>
    /// <remarks>
    /// Original: qboolean footsteps;	 // Play footstep sounds
    /// </remarks>
    public qboolean footsteps;
    /// <summary>
    /// Name of the sky map
    /// </summary>
    /// <remarks>
    /// Original: char skyName[32];	 // Name of the sky map
    /// </remarks>
    public InlineArray32<NChar> skyName;
    /// <remarks>
    /// Original: float rollangle;
    /// </remarks>
    public float rollangle;
    /// <remarks>
    /// Original: float rollspeed;
    /// </remarks>
    public float rollspeed;
    /// <summary>
    /// Sky color
    /// </summary>
    /// <remarks>
    /// Original: float skycolor_r; // Sky color
    /// </remarks>
    public float skycolor_r;
    /// <remarks>
    /// Original: float skycolor_g; //
    /// </remarks>
    public float skycolor_g;
    /// <remarks>
    /// Original: float skycolor_b; //
    /// </remarks>
    public float skycolor_b;
    /// <summary>
    /// Sky vector
    /// </summary>
    /// <remarks>
    /// Original: float skyvec_x;	  // Sky vector
    /// </remarks>
    public float skyvec_x;
    /// <remarks>
    /// Original: float skyvec_y;	  //
    /// </remarks>
    public float skyvec_y;
    /// <remarks>
    /// Original: float skyvec_z;	  //
    /// </remarks>
    public float skyvec_z;
}

