// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// physent_t
/// </summary>
/// <remarks>
/// Original: typedef struct physent_s { char name[32]; // Name of model, or "player" or "world". int player; Vector origin;		  // Model's origin in world coordinates. model_t* model;		  // only for bsp models model_t* studiomodel; // SOLID_BBOX, but ...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct physent_t
{
    /// <summary>
    /// Name of model, or "player" or "world".
    /// </summary>
    /// <remarks>
    /// Original: char name[32]; // Name of model, or "player" or "world".
    /// </remarks>
    public InlineArray32<NChar> name;
    /// <remarks>
    /// Original: int player;
    /// </remarks>
    public int player;
    /// <summary>
    /// Model's origin in world coordinates.
    /// </summary>
    /// <remarks>
    /// Original: Vector origin;		  // Model's origin in world coordinates.
    /// </remarks>
    public Vector3 origin;
    /// <summary>
    /// only for bsp models
    /// </summary>
    /// <remarks>
    /// Original: model_t* model;		  // only for bsp models
    /// </remarks>
    public model_t* model;
    /// <summary>
    /// SOLID_BBOX, but studio clip intersections.
    /// </summary>
    /// <remarks>
    /// Original: model_t* studiomodel; // SOLID_BBOX, but studio clip intersections.
    /// </remarks>
    public model_t* studiomodel;
    /// <summary>
    /// only for non-bsp models
    /// </summary>
    /// <remarks>
    /// Original: Vector mins, maxs;	  // only for non-bsp models
    /// </remarks>
    public Vector3 mins;
    /// <summary>
    /// only for non-bsp models
    /// </summary>
    /// <remarks>
    /// Original: Vector mins, maxs;	  // only for non-bsp models
    /// </remarks>
    public Vector3 maxs;
    /// <summary>
    /// For client or server to use to identify (index into edicts or cl_entities)
    /// </summary>
    /// <remarks>
    /// Original: int info;			  // For client or server to use to identify (index into edicts or cl_entities)
    /// </remarks>
    public int info;
    /// <summary>
    /// rotated entities need this info for hull testing to work.
    /// </summary>
    /// <remarks>
    /// Original: Vector angles;		  // rotated entities need this info for hull testing to work.
    /// </remarks>
    public Vector3 angles;
    /// <summary>
    /// Triggers and func_door type WATER brushes are SOLID_NOT
    /// </summary>
    /// <remarks>
    /// Original: int solid;		// Triggers and func_door type WATER brushes are SOLID_NOT
    /// </remarks>
    public int solid;
    /// <summary>
    /// BSP Contents for such things like fun_door water brushes.
    /// </summary>
    /// <remarks>
    /// Original: int skin;		// BSP Contents for such things like fun_door water brushes.
    /// </remarks>
    public int skin;
    /// <summary>
    /// So we can ignore glass
    /// </summary>
    /// <remarks>
    /// Original: int rendermode; // So we can ignore glass
    /// </remarks>
    public int rendermode;
    /// <summary>
    /// Complex collision detection.
    /// </summary>
    /// <remarks>
    /// Original: float frame;
    /// </remarks>
    public float frame;
    /// <remarks>
    /// Original: int sequence;
    /// </remarks>
    public int sequence;
    /// <remarks>
    /// Original: byte controller[4];
    /// </remarks>
    public InlineArray4<byte> controller;
    /// <remarks>
    /// Original: byte blending[2];
    /// </remarks>
    public InlineArray2<byte> blending;
    /// <remarks>
    /// Original: int movetype;
    /// </remarks>
    public int movetype;
    /// <remarks>
    /// Original: int takedamage;
    /// </remarks>
    public int takedamage;
    /// <remarks>
    /// Original: int blooddecal;
    /// </remarks>
    public int blooddecal;
    /// <remarks>
    /// Original: int team;
    /// </remarks>
    public int team;
    /// <remarks>
    /// Original: int classnumber;
    /// </remarks>
    public int classnumber;
    /// <summary>
    /// For mods
    /// </summary>
    /// <remarks>
    /// Original: int iuser1;
    /// </remarks>
    public int iuser1;
    /// <remarks>
    /// Original: int iuser2;
    /// </remarks>
    public int iuser2;
    /// <remarks>
    /// Original: int iuser3;
    /// </remarks>
    public int iuser3;
    /// <remarks>
    /// Original: int iuser4;
    /// </remarks>
    public int iuser4;
    /// <remarks>
    /// Original: float fuser1;
    /// </remarks>
    public float fuser1;
    /// <remarks>
    /// Original: float fuser2;
    /// </remarks>
    public float fuser2;
    /// <remarks>
    /// Original: float fuser3;
    /// </remarks>
    public float fuser3;
    /// <remarks>
    /// Original: float fuser4;
    /// </remarks>
    public float fuser4;
    /// <remarks>
    /// Original: Vector vuser1;
    /// </remarks>
    public Vector3 vuser1;
    /// <remarks>
    /// Original: Vector vuser2;
    /// </remarks>
    public Vector3 vuser2;
    /// <remarks>
    /// Original: Vector vuser3;
    /// </remarks>
    public Vector3 vuser3;
    /// <remarks>
    /// Original: Vector vuser4;
    /// </remarks>
    public Vector3 vuser4;
}

