// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: struct pmtrace_s { qboolean allsolid;		  // if true, plane is not valid qboolean startsolid;	  // if true, the initial point was in a solid area qboolean inopen, inwater; // End point is in empty space or in water float fraction;			  // ...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct pmtrace_t
{
    /// <summary>
    /// if true, plane is not valid
    /// </summary>
    /// <remarks>
    /// Original: qboolean allsolid;		  // if true, plane is not valid
    /// </remarks>
    public qboolean allsolid;
    /// <summary>
    /// if true, the initial point was in a solid area
    /// </summary>
    /// <remarks>
    /// Original: qboolean startsolid;	  // if true, the initial point was in a solid area
    /// </remarks>
    public qboolean startsolid;
    /// <summary>
    /// End point is in empty space or in water
    /// </summary>
    /// <remarks>
    /// Original: qboolean inopen, inwater; // End point is in empty space or in water
    /// </remarks>
    public qboolean inopen;
    /// <summary>
    /// End point is in empty space or in water
    /// </summary>
    /// <remarks>
    /// Original: qboolean inopen, inwater; // End point is in empty space or in water
    /// </remarks>
    public qboolean inwater;
    /// <summary>
    /// time completed, 1.0 = didn't hit anything
    /// </summary>
    /// <remarks>
    /// Original: float fraction;			  // time completed, 1.0 = didn't hit anything
    /// </remarks>
    public float fraction;
    /// <summary>
    /// final position
    /// </summary>
    /// <remarks>
    /// Original: Vector endpos;			  // final position
    /// </remarks>
    public Vector3 endpos;
    /// <summary>
    /// surface normal at impact
    /// </summary>
    /// <remarks>
    /// Original: pmplane_t plane;		  // surface normal at impact
    /// </remarks>
    public pmplane_t plane;
    /// <summary>
    /// entity at impact
    /// </summary>
    /// <remarks>
    /// Original: int ent;				  // entity at impact
    /// </remarks>
    public int ent;
    /// <summary>
    /// Change in player's velocity caused by impact.
    /// </summary>
    /// <remarks>
    /// Original: Vector deltavelocity;	  // Change in player's velocity caused by impact.
    /// </remarks>
    public Vector3 deltavelocity;
    /// <summary>
    /// Only run on server.
    /// </summary>
    /// <remarks>
    /// Original: int hitgroup;
    /// </remarks>
    public int hitgroup;
}

