// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// Info about weapons player might have in his/her possession
/// </summary>
/// <remarks>
/// Original: typedef struct weapon_data_s { int m_iId; int m_iClip; float m_flNextPrimaryAttack; float m_flNextSecondaryAttack; float m_flTimeWeaponIdle; int m_fInReload; int m_fInSpecialReload; float m_flNextReload; float m_flPumpTime; float m_fRelo...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct weapon_data_t
{
    /// <remarks>
    /// Original: int m_iId;
    /// </remarks>
    public int m_iId;
    /// <remarks>
    /// Original: int m_iClip;
    /// </remarks>
    public int m_iClip;
    /// <remarks>
    /// Original: float m_flNextPrimaryAttack;
    /// </remarks>
    public float m_flNextPrimaryAttack;
    /// <remarks>
    /// Original: float m_flNextSecondaryAttack;
    /// </remarks>
    public float m_flNextSecondaryAttack;
    /// <remarks>
    /// Original: float m_flTimeWeaponIdle;
    /// </remarks>
    public float m_flTimeWeaponIdle;
    /// <remarks>
    /// Original: int m_fInReload;
    /// </remarks>
    public int m_fInReload;
    /// <remarks>
    /// Original: int m_fInSpecialReload;
    /// </remarks>
    public int m_fInSpecialReload;
    /// <remarks>
    /// Original: float m_flNextReload;
    /// </remarks>
    public float m_flNextReload;
    /// <remarks>
    /// Original: float m_flPumpTime;
    /// </remarks>
    public float m_flPumpTime;
    /// <remarks>
    /// Original: float m_fReloadTime;
    /// </remarks>
    public float m_fReloadTime;
    /// <remarks>
    /// Original: float m_fAimedDamage;
    /// </remarks>
    public float m_fAimedDamage;
    /// <remarks>
    /// Original: float m_fNextAimBonus;
    /// </remarks>
    public float m_fNextAimBonus;
    /// <remarks>
    /// Original: int m_fInZoom;
    /// </remarks>
    public int m_fInZoom;
    /// <remarks>
    /// Original: int m_iWeaponState;
    /// </remarks>
    public int m_iWeaponState;
    /// <remarks>
    /// Original: int iuser1;
    /// </remarks>
    public int iuser1;
    /// <remarks>
    /// Original: int iuser2;
    /// </remarks>
    public int iuser2;
    /// <remarks>
    /// Original: int iuser3;
    /// </remarks>
    public int iuser3;
    /// <remarks>
    /// Original: int iuser4;
    /// </remarks>
    public int iuser4;
    /// <remarks>
    /// Original: float fuser1;
    /// </remarks>
    public float fuser1;
    /// <remarks>
    /// Original: float fuser2;
    /// </remarks>
    public float fuser2;
    /// <remarks>
    /// Original: float fuser3;
    /// </remarks>
    public float fuser3;
    /// <remarks>
    /// Original: float fuser4;
    /// </remarks>
    public float fuser4;
}

