// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct demo_api_s { int (*IsRecording)(void); int (*IsPlayingback)(void); int (*IsTimeDemo)(void); void (*WriteBuffer)(int size, unsigned char* buffer); } demo_api_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct demo_api_t
{
    /// <remarks>
    /// Original: int (*IsRecording)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> IsRecording;
    /// <remarks>
    /// Original: int (*IsPlayingback)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> IsPlayingback;
    /// <remarks>
    /// Original: int (*IsTimeDemo)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> IsTimeDemo;
    /// <remarks>
    /// Original: void (*WriteBuffer)(int size, unsigned char* buffer);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, byte*, void> WriteBuffer;
}

