// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// Defines entity interface between engine and DLLs.
/// This header file included by engine files and DLL files.
/// Before including this header, DLLs must:
/// include progdefs.h
/// This is conveniently done for them in extdll.h
/// </summary>
/// <remarks>
/// Original: typedef enum { at_notice, at_console,	  // same as at_notice, but forces a ConPrintf, not a message box at_aiconsole, // same as at_console, but only shown if developer level is 2! at_warning, at_error, at_logged // Server print to conso...
/// </remarks>
public enum ALERT_TYPE
{
    at_notice = 0,
    at_console = 1,
    at_aiconsole = 2,
    at_warning = 3,
    at_error = 4,
    at_logged = 5,
}

