// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct { int id;		   // Ordinal ID of this entity (used for entity &lt;--&gt; pointer conversions) edict_t* pent; // Pointer to the in-game entity int location;		// Offset from the base data of this entity int size;			// Byte size of t...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct ENTITYTABLE
{
    /// <summary>
    /// Ordinal ID of this entity (used for entity
    /// &lt;
    /// --&gt; pointer conversions)
    /// </summary>
    /// <remarks>
    /// Original: int id;		   // Ordinal ID of this entity (used for entity &lt;--&gt; pointer conversions)
    /// </remarks>
    public int id;
    /// <summary>
    /// Pointer to the in-game entity
    /// </summary>
    /// <remarks>
    /// Original: edict_t* pent; // Pointer to the in-game entity
    /// </remarks>
    public edict_t* pent;
    /// <summary>
    /// Offset from the base data of this entity
    /// </summary>
    /// <remarks>
    /// Original: int location;		// Offset from the base data of this entity
    /// </remarks>
    public int location;
    /// <summary>
    /// Byte size of this entity's data
    /// </summary>
    /// <remarks>
    /// Original: int size;			// Byte size of this entity's data
    /// </remarks>
    public int size;
    /// <summary>
    /// This could be a short -- bit mask of transitions that this entity is in the PVS of
    /// </summary>
    /// <remarks>
    /// Original: int flags;			// This could be a short -- bit mask of transitions that this entity is in the PVS of
    /// </remarks>
    public int flags;
    /// <summary>
    /// entity class name
    /// </summary>
    /// <remarks>
    /// Original: string_t classname; // entity class name
    /// </remarks>
    public string_t classname;
}

