// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef enum _fieldtypes { FIELD_FLOAT = 0,	   // Any floating point value FIELD_STRING,		   // A string ID (return from ALLOC_STRING) FIELD_ENTITY,		   // An entity offset (EOFFSET) FIELD_CLASSPTR,		   // CBaseEntity * FIELD_EHANDLE,		 ...
/// </remarks>
public enum FIELDTYPE
{
    FIELD_FLOAT = 0,
    FIELD_STRING = 1,
    FIELD_ENTITY = 2,
    FIELD_CLASSPTR = 3,
    FIELD_EHANDLE = 4,
    FIELD_EVARS = 5,
    FIELD_EDICT = 6,
    FIELD_VECTOR = 7,
    FIELD_POSITION_VECTOR = 8,
    FIELD_POINTER = 9,
    FIELD_INTEGER = 10,
    FIELD_FUNCTION = 11,
    FIELD_BOOLEAN = 12,
    FIELD_SHORT = 13,
    FIELD_CHARACTER = 14,
    FIELD_TIME = 15,
    FIELD_MODELNAME = 16,
    FIELD_SOUNDNAME = 17,
    FIELD_ENGINETYPECOUNT = 18,
    FIELD_INT64 = 18,
    FIELD_TYPECOUNT = 19,
}

