// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// For integrity checking of content on clients
/// </summary>
/// <remarks>
/// Original: typedef enum { force_exactfile,					// File on client must exactly match server's file force_model_samebounds,				// For model files only, the geometry must fit in the same bbox force_model_specifybounds,			// For model files only, the g...
/// </remarks>
public enum FORCE_TYPE
{
    force_exactfile = 0,
    force_model_samebounds = 1,
    force_model_specifybounds = 2,
    force_model_specifybounds_if_avail = 3,
}

