// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct { char mapName[32]; char landmarkName[32]; edict_t* pentLandmark; Vector vecLandmarkOrigin; } LEVELLIST;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct LEVELLIST
{
    /// <remarks>
    /// Original: char mapName[32];
    /// </remarks>
    public InlineArray32<NChar> mapName;
    /// <remarks>
    /// Original: char landmarkName[32];
    /// </remarks>
    public InlineArray32<NChar> landmarkName;
    /// <remarks>
    /// Original: edict_t* pentLandmark;
    /// </remarks>
    public edict_t* pentLandmark;
    /// <remarks>
    /// Original: Vector vecLandmarkOrigin;
    /// </remarks>
    public Vector3 vecLandmarkOrigin;
}

