// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// 4-22-98  JOHN: added for use in pfnClientPrintf
/// </summary>
/// <remarks>
/// Original: typedef enum { print_console, print_center, print_chat, } PRINT_TYPE;
/// </remarks>
public enum PRINT_TYPE
{
    print_console = 0,
    print_center = 1,
    print_chat = 2,
}

