// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// Returned by TraceLine
/// </summary>
/// <remarks>
/// Original: typedef struct { int fAllSolid;	 // if true, plane is not valid int fStartSolid; // if true, the initial point was in a solid area int fInOpen; int fInWater; float flFraction; // time completed, 1.0 = didn't hit anything Vector vecEndPos...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct TraceResult
{
    /// <summary>
    /// if true, plane is not valid
    /// </summary>
    /// <remarks>
    /// Original: int fAllSolid;	 // if true, plane is not valid
    /// </remarks>
    public int fAllSolid;
    /// <summary>
    /// if true, the initial point was in a solid area
    /// </summary>
    /// <remarks>
    /// Original: int fStartSolid; // if true, the initial point was in a solid area
    /// </remarks>
    public int fStartSolid;
    /// <remarks>
    /// Original: int fInOpen;
    /// </remarks>
    public int fInOpen;
    /// <remarks>
    /// Original: int fInWater;
    /// </remarks>
    public int fInWater;
    /// <summary>
    /// time completed, 1.0 = didn't hit anything
    /// </summary>
    /// <remarks>
    /// Original: float flFraction; // time completed, 1.0 = didn't hit anything
    /// </remarks>
    public float flFraction;
    /// <summary>
    /// final position
    /// </summary>
    /// <remarks>
    /// Original: Vector vecEndPos; // final position
    /// </remarks>
    public Vector3 vecEndPos;
    /// <remarks>
    /// Original: float flPlaneDist;
    /// </remarks>
    public float flPlaneDist;
    /// <summary>
    /// surface normal at impact
    /// </summary>
    /// <remarks>
    /// Original: Vector vecPlaneNormal; // surface normal at impact
    /// </remarks>
    public Vector3 vecPlaneNormal;
    /// <summary>
    /// entity the surface is on
    /// </summary>
    /// <remarks>
    /// Original: edict_t* pHit;		   // entity the surface is on
    /// </remarks>
    public edict_t* pHit;
    /// <summary>
    /// 0 == generic, non zero is specific body part
    /// </summary>
    /// <remarks>
    /// Original: int iHitgroup;		   // 0 == generic, non zero is specific body part
    /// </remarks>
    public int iHitgroup;
}

