// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct dlight_s { Vector origin; float radius; color24 color; float die;		// stop lighting after this time float decay;	// drop this each second float minlight; // don't add when contributing less int key; qboolean dark; // subtr...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct dlight_t
{
    /// <remarks>
    /// Original: Vector origin;
    /// </remarks>
    public Vector3 origin;
    /// <remarks>
    /// Original: float radius;
    /// </remarks>
    public float radius;
    /// <remarks>
    /// Original: color24 color;
    /// </remarks>
    public color24 color;
    /// <summary>
    /// stop lighting after this time
    /// </summary>
    /// <remarks>
    /// Original: float die;		// stop lighting after this time
    /// </remarks>
    public float die;
    /// <summary>
    /// drop this each second
    /// </summary>
    /// <remarks>
    /// Original: float decay;	// drop this each second
    /// </remarks>
    public float decay;
    /// <summary>
    /// don't add when contributing less
    /// </summary>
    /// <remarks>
    /// Original: float minlight; // don't add when contributing less
    /// </remarks>
    public float minlight;
    /// <remarks>
    /// Original: int key;
    /// </remarks>
    public int key;
    /// <summary>
    /// subtracts light instead of adding
    /// </summary>
    /// <remarks>
    /// Original: qboolean dark; // subtracts light instead of adding
    /// </remarks>
    public qboolean dark;
}

