// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct resource_s { char szFileName[MAX_QPATH]; // File name to download/precache. resourcetype_t type;		// t_sound, t_skin, t_model, t_decal. int nIndex;					// For t_decals int nDownloadSize;			// Size in Bytes if this must be ...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct resource_t
{
    /// <summary>
    /// File name to download/precache.
    /// </summary>
    /// <remarks>
    /// Original: char szFileName[MAX_QPATH]; // File name to download/precache.
    /// </remarks>
    public InlineArray64<NChar> szFileName;
    /// <summary>
    /// t_sound, t_skin, t_model, t_decal.
    /// </summary>
    /// <remarks>
    /// Original: resourcetype_t type;		// t_sound, t_skin, t_model, t_decal.
    /// </remarks>
    public resourcetype_t type;
    /// <summary>
    /// For t_decals
    /// </summary>
    /// <remarks>
    /// Original: int nIndex;					// For t_decals
    /// </remarks>
    public int nIndex;
    /// <summary>
    /// Size in Bytes if this must be downloaded.
    /// </summary>
    /// <remarks>
    /// Original: int nDownloadSize;			// Size in Bytes if this must be downloaded.
    /// </remarks>
    public int nDownloadSize;
    /// <remarks>
    /// Original: unsigned char ucFlags;
    /// </remarks>
    public byte ucFlags;
    /// <summary>
    /// To determine if we already have it.
    /// </summary>
    /// <remarks>
    /// Original: unsigned char rgucMD5_hash[16]; // To determine if we already have it.
    /// </remarks>
    public InlineArray16<byte> rgucMD5_hash;
    /// <summary>
    /// Which player index this resource is associated with, if it's a custom resource.
    /// </summary>
    /// <remarks>
    /// Original: unsigned char playernum;		// Which player index this resource is associated with, if it's a custom resource.
    /// </remarks>
    public byte playernum;
    /// <summary>
    /// For future expansion
    /// </summary>
    /// <remarks>
    /// Original: unsigned char rguc_reserved[32]; // For future expansion
    /// </remarks>
    public InlineArray32<byte> rguc_reserved;
    /// <summary>
    /// Next in chain.
    /// </summary>
    /// <remarks>
    /// Original: struct resource_s* pNext;		 // Next in chain.
    /// </remarks>
    public resource_t* pNext;
    /// <remarks>
    /// Original: struct resource_s* pPrev;
    /// </remarks>
    public resource_t* pPrev;
}

