// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct event_args_s { int flags; // Transmitted int entindex; float origin[3]; float angles[3]; float velocity[3]; int ducking; float fparam1; float fparam2; int iparam1; int iparam2; int bparam1; int bparam2; } event_args_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct event_args_t
{
    /// <remarks>
    /// Original: int flags;
    /// </remarks>
    public int flags;
    /// <summary>
    /// Transmitted
    /// </summary>
    /// <remarks>
    /// Original: int entindex;
    /// </remarks>
    public int entindex;
    /// <remarks>
    /// Original: float origin[3];
    /// </remarks>
    public InlineArray3<float> origin;
    /// <remarks>
    /// Original: float angles[3];
    /// </remarks>
    public InlineArray3<float> angles;
    /// <remarks>
    /// Original: float velocity[3];
    /// </remarks>
    public InlineArray3<float> velocity;
    /// <remarks>
    /// Original: int ducking;
    /// </remarks>
    public int ducking;
    /// <remarks>
    /// Original: float fparam1;
    /// </remarks>
    public float fparam1;
    /// <remarks>
    /// Original: float fparam2;
    /// </remarks>
    public float fparam2;
    /// <remarks>
    /// Original: int iparam1;
    /// </remarks>
    public int iparam1;
    /// <remarks>
    /// Original: int iparam2;
    /// </remarks>
    public int iparam2;
    /// <remarks>
    /// Original: int bparam1;
    /// </remarks>
    public int bparam1;
    /// <remarks>
    /// Original: int bparam2;
    /// </remarks>
    public int bparam2;
}

