// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct usercmd_s { short lerp_msec;   // Interpolation time on client byte msec;		   // Duration in ms of command Vector viewangles; // Command view angles. // intended velocities float forwardmove;		// Forward velocity. float si...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct usercmd_t
{
    /// <summary>
    /// Interpolation time on client
    /// </summary>
    /// <remarks>
    /// Original: short lerp_msec;   // Interpolation time on client
    /// </remarks>
    public short lerp_msec;
    /// <summary>
    /// Duration in ms of command
    /// </summary>
    /// <remarks>
    /// Original: byte msec;		   // Duration in ms of command
    /// </remarks>
    public byte msec;
    /// <summary>
    /// Command view angles.
    /// </summary>
    /// <remarks>
    /// Original: Vector viewangles; // Command view angles.
    /// </remarks>
    public Vector3 viewangles;
    /// <summary>
    /// Forward velocity.
    /// </summary>
    /// <remarks>
    /// Original: float forwardmove;		// Forward velocity.
    /// </remarks>
    public float forwardmove;
    /// <summary>
    /// Sideways velocity.
    /// </summary>
    /// <remarks>
    /// Original: float sidemove;			// Sideways velocity.
    /// </remarks>
    public float sidemove;
    /// <summary>
    /// Upward velocity.
    /// </summary>
    /// <remarks>
    /// Original: float upmove;			// Upward velocity.
    /// </remarks>
    public float upmove;
    /// <summary>
    /// Light level at spot where we are standing.
    /// </summary>
    /// <remarks>
    /// Original: byte lightlevel;		// Light level at spot where we are standing.
    /// </remarks>
    public byte lightlevel;
    /// <summary>
    /// Attack buttons
    /// </summary>
    /// <remarks>
    /// Original: unsigned short buttons; // Attack buttons
    /// </remarks>
    public ushort buttons;
    /// <summary>
    /// Impulse command issued.
    /// </summary>
    /// <remarks>
    /// Original: byte impulse;			// Impulse command issued.
    /// </remarks>
    public byte impulse;
    /// <summary>
    /// Current weapon id
    /// </summary>
    /// <remarks>
    /// Original: byte weaponselect;		// Current weapon id
    /// </remarks>
    public byte weaponselect;
    /// <summary>
    /// Experimental player impact stuff.
    /// </summary>
    /// <remarks>
    /// Original: int impact_index;
    /// </remarks>
    public int impact_index;
    /// <remarks>
    /// Original: Vector impact_position;
    /// </remarks>
    public Vector3 impact_position;
}

