// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// ---------------------------------------------------------------------------
/// client_textmessage_t
/// ---------------------------------------------------------------------------
/// </summary>
/// <remarks>
/// Original: typedef struct client_textmessage_s { int effect; byte r1, g1, b1, a1; // 2 colors for effects byte r2, g2, b2, a2; float x; float y; float fadein; float fadeout; float holdtime; float fxtime; const char* pName; const char* pMessage; } c...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct client_textmessage_t
{
    /// <remarks>
    /// Original: int effect;
    /// </remarks>
    public int effect;
    /// <summary>
    /// 2 colors for effects
    /// </summary>
    /// <remarks>
    /// Original: byte r1, g1, b1, a1; // 2 colors for effects
    /// </remarks>
    public byte r1;
    /// <summary>
    /// 2 colors for effects
    /// </summary>
    /// <remarks>
    /// Original: byte r1, g1, b1, a1; // 2 colors for effects
    /// </remarks>
    public byte g1;
    /// <summary>
    /// 2 colors for effects
    /// </summary>
    /// <remarks>
    /// Original: byte r1, g1, b1, a1; // 2 colors for effects
    /// </remarks>
    public byte b1;
    /// <summary>
    /// 2 colors for effects
    /// </summary>
    /// <remarks>
    /// Original: byte r1, g1, b1, a1; // 2 colors for effects
    /// </remarks>
    public byte a1;
    /// <remarks>
    /// Original: byte r2, g2, b2, a2;
    /// </remarks>
    public byte r2;
    /// <remarks>
    /// Original: byte r2, g2, b2, a2;
    /// </remarks>
    public byte g2;
    /// <remarks>
    /// Original: byte r2, g2, b2, a2;
    /// </remarks>
    public byte b2;
    /// <remarks>
    /// Original: byte r2, g2, b2, a2;
    /// </remarks>
    public byte a2;
    /// <remarks>
    /// Original: float x;
    /// </remarks>
    public float x;
    /// <remarks>
    /// Original: float y;
    /// </remarks>
    public float y;
    /// <remarks>
    /// Original: float fadein;
    /// </remarks>
    public float fadein;
    /// <remarks>
    /// Original: float fadeout;
    /// </remarks>
    public float fadeout;
    /// <remarks>
    /// Original: float holdtime;
    /// </remarks>
    public float holdtime;
    /// <remarks>
    /// Original: float fxtime;
    /// </remarks>
    public float fxtime;
    /// <remarks>
    /// Original: const char* pName;
    /// </remarks>
    public NChar* pName;
    /// <remarks>
    /// Original: const char* pMessage;
    /// </remarks>
    public NChar* pMessage;
}

