// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: struct sentenceEntry_ { char* data;					// sentence data (ie "We have hostiles" ) sentenceEntry_s* nextEntry; // Next loaded entry qboolean isGlobal;			// Is entry retained over level transitions? unsigned int index;			// this entry's po...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct sentenceEntry_s
{
    /// <summary>
    /// sentence data (ie "We have hostiles" )
    /// </summary>
    /// <remarks>
    /// Original: char* data;					// sentence data (ie "We have hostiles" )
    /// </remarks>
    public NChar* data;
    /// <summary>
    /// Next loaded entry
    /// </summary>
    /// <remarks>
    /// Original: sentenceEntry_s* nextEntry; // Next loaded entry
    /// </remarks>
    public sentenceEntry_s* nextEntry;
    /// <summary>
    /// Is entry retained over level transitions?
    /// </summary>
    /// <remarks>
    /// Original: qboolean isGlobal;			// Is entry retained over level transitions?
    /// </remarks>
    public qboolean isGlobal;
    /// <summary>
    /// this entry's position in the file.
    /// </summary>
    /// <remarks>
    /// Original: unsigned int index;			// this entry's position in the file.
    /// </remarks>
    public uint index;
}

