// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: struct sequenceEntry_ { char* fileName;						 // Name of sequence file without .SEQ extension char* entryName;					 // Name of entry label in file sequenceCommandLine_s* firstCommand; // Linked list of commands in entry sequenceEntry_s* ...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct sequenceEntry_s
{
    /// <summary>
    /// Name of sequence file without .SEQ extension
    /// </summary>
    /// <remarks>
    /// Original: char* fileName;						 // Name of sequence file without .SEQ extension
    /// </remarks>
    public NChar* fileName;
    /// <summary>
    /// Name of entry label in file
    /// </summary>
    /// <remarks>
    /// Original: char* entryName;					 // Name of entry label in file
    /// </remarks>
    public NChar* entryName;
    /// <summary>
    /// Linked list of commands in entry
    /// </summary>
    /// <remarks>
    /// Original: sequenceCommandLine_s* firstCommand; // Linked list of commands in entry
    /// </remarks>
    public sequenceCommandLine_s* firstCommand;
    /// <summary>
    /// Next loaded entry
    /// </summary>
    /// <remarks>
    /// Original: sequenceEntry_s* nextEntry;			 // Next loaded entry
    /// </remarks>
    public sequenceEntry_s* nextEntry;
    /// <summary>
    /// Is entry retained over level transitions?
    /// </summary>
    /// <remarks>
    /// Original: qboolean isGlobal;					 // Is entry retained over level transitions?
    /// </remarks>
    public qboolean isGlobal;
}

