// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct event_api_s { int version; void (*EV_PlaySound)(int ent, float* origin, int channel, const char* sample, float volume, float attenuation, int fFlags, int pitch); void (*EV_StopSound)(int ent, int channel, const char* sampl...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct event_api_t
{
    /// <remarks>
    /// Original: int version;
    /// </remarks>
    public int version;
    /// <remarks>
    /// Original: void (*EV_PlaySound)(int ent, float* origin, int channel, const char* sample, float volume, float attenuation, int fFlags, int pitch);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, float*, int, NChar*, float, float, int, int, void> EV_PlaySound;
    /// <remarks>
    /// Original: void (*EV_StopSound)(int ent, int channel, const char* sample);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, NChar*, void> EV_StopSound;
    /// <remarks>
    /// Original: int (*EV_FindModelIndex)(const char* pmodel);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int> EV_FindModelIndex;
    /// <remarks>
    /// Original: int (*EV_IsLocal)(int playernum);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int> EV_IsLocal;
    /// <remarks>
    /// Original: int (*EV_LocalPlayerDucking)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> EV_LocalPlayerDucking;
    /// <remarks>
    /// Original: void (*EV_LocalPlayerViewheight)(float*);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, void> EV_LocalPlayerViewheight;
    /// <remarks>
    /// Original: void (*EV_LocalPlayerBounds)(int hull, float* mins, float* maxs);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, float*, float*, void> EV_LocalPlayerBounds;
    /// <remarks>
    /// Original: int (*EV_IndexFromTrace)(struct pmtrace_s* pTrace);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<pmtrace_t*, int> EV_IndexFromTrace;
    /// <remarks>
    /// Original: struct physent_s* (*EV_GetPhysent)(int idx);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, physent_t*> EV_GetPhysent;
    /// <remarks>
    /// Original: void (*EV_SetUpPlayerPrediction)(int dopred, int bIncludeLocalClient);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, void> EV_SetUpPlayerPrediction;
    /// <remarks>
    /// Original: void (*EV_PushPMStates)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> EV_PushPMStates;
    /// <remarks>
    /// Original: void (*EV_PopPMStates)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> EV_PopPMStates;
    /// <remarks>
    /// Original: void (*EV_SetSolidPlayers)(int playernum);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, void> EV_SetSolidPlayers;
    /// <remarks>
    /// Original: void (*EV_SetTraceHull)(int hull);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, void> EV_SetTraceHull;
    /// <remarks>
    /// Original: void (*EV_PlayerTrace)(float* start, float* end, int traceFlags, int ignore_pe, struct pmtrace_s* tr);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, int, int, pmtrace_t*, void> EV_PlayerTrace;
    /// <remarks>
    /// Original: void (*EV_WeaponAnimation)(int sequence, int body);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, void> EV_WeaponAnimation;
    /// <remarks>
    /// Original: unsigned short (*EV_PrecacheEvent)(int type, const char* psz);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, NChar*, ushort> EV_PrecacheEvent;
    /// <remarks>
    /// Original: void (*EV_PlaybackEvent)(int flags, const struct edict_s* pInvoker, unsigned short eventindex, float delay, float* origin, float* angles, float fparam1, float fparam2, int iparam1, int iparam2, int bparam1, int bparam2);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, edict_t*, ushort, float, float*, float*, float, float, int, int, int, int, void> EV_PlaybackEvent;
    /// <remarks>
    /// Original: const char* (*EV_TraceTexture)(int ground, float* vstart, float* vend);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, float*, float*, NChar*> EV_TraceTexture;
    /// <remarks>
    /// Original: void (*EV_StopAllSounds)(int entnum, int entchannel);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, void> EV_StopAllSounds;
    /// <remarks>
    /// Original: void (*EV_KillEvents)(int entnum, const char* eventname);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, NChar*, void> EV_KillEvents;
}

