// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct customization_s { qboolean bInUse;			   // Is this customization in use; resource_t resource;		   // The resource_t for this customization qboolean bTranslated;		   // Has the raw data been translated into a useable format...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct customization_t
{
    /// <summary>
    /// Is this customization in use;
    /// </summary>
    /// <remarks>
    /// Original: qboolean bInUse;			   // Is this customization in use;
    /// </remarks>
    public qboolean bInUse;
    /// <summary>
    /// The resource_t for this customization
    /// </summary>
    /// <remarks>
    /// Original: resource_t resource;		   // The resource_t for this customization
    /// </remarks>
    public resource_t resource;
    /// <summary>
    /// Has the raw data been translated into a useable format?
    /// </summary>
    /// <remarks>
    /// Original: qboolean bTranslated;		   // Has the raw data been translated into a useable format?
    /// </remarks>
    public qboolean bTranslated;
    /// <summary>
    /// Customization specific data
    /// </summary>
    /// <remarks>
    /// Original: int nUserData1;				   // Customization specific data
    /// </remarks>
    public int nUserData1;
    /// <summary>
    /// Customization specific data
    /// </summary>
    /// <remarks>
    /// Original: int nUserData2;				   // Customization specific data
    /// </remarks>
    public int nUserData2;
    /// <summary>
    /// Buffer that holds the data structure that references the data (e.g., the cachewad_t)
    /// </summary>
    /// <remarks>
    /// Original: void* pInfo;				   // Buffer that holds the data structure that references the data (e.g., the cachewad_t)
    /// </remarks>
    public void* pInfo;
    /// <summary>
    /// Buffer that holds the data for the customization (the raw .wad data)
    /// </summary>
    /// <remarks>
    /// Original: void* pBuffer;				   // Buffer that holds the data for the customization (the raw .wad data)
    /// </remarks>
    public void* pBuffer;
    /// <summary>
    /// Next in chain
    /// </summary>
    /// <remarks>
    /// Original: struct customization_s* pNext; // Next in chain
    /// </remarks>
    public customization_t* pNext;
}

