// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// Customization
/// passed to pfnPlayerCustomization
/// For automatic downloading.
/// </summary>
/// <remarks>
/// Original: typedef enum { t_sound = 0, t_skin, t_model, t_decal, t_generic, t_eventscript, t_world, // Fake type for world, is really t_model } resourcetype_t;
/// </remarks>
public enum resourcetype_t
{
    t_sound = 0,
    t_skin = 1,
    t_model = 2,
    t_decal = 3,
    t_generic = 4,
    t_eventscript = 5,
    t_world = 6,
}

