// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// !!! if this is changed, it must be changed in d_ifacea.h too !!!
/// </summary>
/// <remarks>
/// Original: typedef struct particle_s { // driver-usable fields Vector org; short color; short packedColor; // drivers never touch the following fields struct particle_s* next; Vector vel; float ramp; float die; ptype_t type; void (*deathfunc)(struc...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct particle_t
{
    /// <summary>
    /// driver-usable fields
    /// </summary>
    /// <remarks>
    /// Original: Vector org;
    /// </remarks>
    public Vector3 org;
    /// <remarks>
    /// Original: short color;
    /// </remarks>
    public short color;
    /// <remarks>
    /// Original: short packedColor;
    /// </remarks>
    public short packedColor;
    /// <summary>
    /// drivers never touch the following fields
    /// </summary>
    /// <remarks>
    /// Original: struct particle_s* next;
    /// </remarks>
    public particle_t* next;
    /// <remarks>
    /// Original: Vector vel;
    /// </remarks>
    public Vector3 vel;
    /// <remarks>
    /// Original: float ramp;
    /// </remarks>
    public float ramp;
    /// <remarks>
    /// Original: float die;
    /// </remarks>
    public float die;
    /// <remarks>
    /// Original: ptype_t type;
    /// </remarks>
    public ptype_t type;
    /// <remarks>
    /// Original: void (*deathfunc)(struct particle_s* particle);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<particle_t*, void> deathfunc;
    /// <summary>
    /// for pt_clientcusttom, we'll call this function each frame
    /// </summary>
    /// <remarks>
    /// Original: void (*callback)(struct particle_s* particle, float frametime);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<particle_t*, float, void> callback;
    /// <summary>
    /// For deathfunc, etc.
    /// </summary>
    /// <remarks>
    /// Original: unsigned char context;
    /// </remarks>
    public byte context;
}

