// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef enum { pt_static, pt_grav, pt_slowgrav, pt_fire, pt_explode, pt_explode2, pt_blob, pt_blob2, pt_vox_slowgrav, pt_vox_grav, pt_clientcustom // Must have callback function specified } ptype_t;
/// </remarks>
public enum ptype_t
{
    pt_static = 0,
    pt_grav = 1,
    pt_slowgrav = 2,
    pt_fire = 3,
    pt_explode = 4,
    pt_explode2 = 5,
    pt_blob = 6,
    pt_blob2 = 7,
    pt_vox_slowgrav = 8,
    pt_vox_grav = 9,
    pt_clientcustom = 10,
}

