// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct { Vector normal; float dist; } pmplane_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct pmplane_t
{
    /// <remarks>
    /// Original: Vector normal;
    /// </remarks>
    public Vector3 normal;
    /// <remarks>
    /// Original: float dist;
    /// </remarks>
    public float dist;
}

