// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct { float time; float frametime; float force_retouch; string_t mapname; string_t startspot; float deathmatch; float coop; float teamplay; float serverflags; float found_secrets; Vector v_forward; Vector v_up; Vector v_right;...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct globalvars_t
{
    /// <remarks>
    /// Original: float time;
    /// </remarks>
    public float time;
    /// <remarks>
    /// Original: float frametime;
    /// </remarks>
    public float frametime;
    /// <remarks>
    /// Original: float force_retouch;
    /// </remarks>
    public float force_retouch;
    /// <remarks>
    /// Original: string_t mapname;
    /// </remarks>
    public string_t mapname;
    /// <remarks>
    /// Original: string_t startspot;
    /// </remarks>
    public string_t startspot;
    /// <remarks>
    /// Original: float deathmatch;
    /// </remarks>
    public float deathmatch;
    /// <remarks>
    /// Original: float coop;
    /// </remarks>
    public float coop;
    /// <remarks>
    /// Original: float teamplay;
    /// </remarks>
    public float teamplay;
    /// <remarks>
    /// Original: float serverflags;
    /// </remarks>
    public float serverflags;
    /// <remarks>
    /// Original: float found_secrets;
    /// </remarks>
    public float found_secrets;
    /// <remarks>
    /// Original: Vector v_forward;
    /// </remarks>
    public Vector3 v_forward;
    /// <remarks>
    /// Original: Vector v_up;
    /// </remarks>
    public Vector3 v_up;
    /// <remarks>
    /// Original: Vector v_right;
    /// </remarks>
    public Vector3 v_right;
    /// <remarks>
    /// Original: float trace_allsolid;
    /// </remarks>
    public float trace_allsolid;
    /// <remarks>
    /// Original: float trace_startsolid;
    /// </remarks>
    public float trace_startsolid;
    /// <remarks>
    /// Original: float trace_fraction;
    /// </remarks>
    public float trace_fraction;
    /// <remarks>
    /// Original: Vector trace_endpos;
    /// </remarks>
    public Vector3 trace_endpos;
    /// <remarks>
    /// Original: Vector trace_plane_normal;
    /// </remarks>
    public Vector3 trace_plane_normal;
    /// <remarks>
    /// Original: float trace_plane_dist;
    /// </remarks>
    public float trace_plane_dist;
    /// <remarks>
    /// Original: edict_t* trace_ent;
    /// </remarks>
    public edict_t* trace_ent;
    /// <remarks>
    /// Original: float trace_inopen;
    /// </remarks>
    public float trace_inopen;
    /// <remarks>
    /// Original: float trace_inwater;
    /// </remarks>
    public float trace_inwater;
    /// <remarks>
    /// Original: int trace_hitgroup;
    /// </remarks>
    public int trace_hitgroup;
    /// <remarks>
    /// Original: int trace_flags;
    /// </remarks>
    public int trace_flags;
    /// <remarks>
    /// Original: int msg_entity;
    /// </remarks>
    public int msg_entity;
    /// <remarks>
    /// Original: int cdAudioTrack;
    /// </remarks>
    public int cdAudioTrack;
    /// <remarks>
    /// Original: int maxClients;
    /// </remarks>
    public int maxClients;
    /// <remarks>
    /// Original: int maxEntities;
    /// </remarks>
    public int maxEntities;
    /// <remarks>
    /// Original: const char* pStringBase;
    /// </remarks>
    public NChar* pStringBase;
    /// <remarks>
    /// Original: void* pSaveData;
    /// </remarks>
    public void* pSaveData;
    /// <remarks>
    /// Original: Vector vecLandmarkOffset;
    /// </remarks>
    public Vector3 vecLandmarkOffset;
}

