// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct playermove_s { int player_index; // So we don't try to run the PM_CheckStuck nudging too quickly. qboolean server;  // For debugging, are we running physics code on server side? qboolean multiplayer; // 1 == multiplayer se...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct playermove_t
{
    /// <summary>
    /// So we don't try to run the PM_CheckStuck nudging too quickly.
    /// </summary>
    /// <remarks>
    /// Original: int player_index; // So we don't try to run the PM_CheckStuck nudging too quickly.
    /// </remarks>
    public int player_index;
    /// <summary>
    /// For debugging, are we running physics code on server side?
    /// </summary>
    /// <remarks>
    /// Original: qboolean server;  // For debugging, are we running physics code on server side?
    /// </remarks>
    public qboolean server;
    /// <summary>
    /// 1 == multiplayer server
    /// </summary>
    /// <remarks>
    /// Original: qboolean multiplayer; // 1 == multiplayer server
    /// </remarks>
    public qboolean multiplayer;
    /// <summary>
    /// realtime on host, for reckoning duck timing
    /// </summary>
    /// <remarks>
    /// Original: float time;			  // realtime on host, for reckoning duck timing
    /// </remarks>
    public float time;
    /// <summary>
    /// Duration of this frame
    /// </summary>
    /// <remarks>
    /// Original: float frametime;	  // Duration of this frame
    /// </remarks>
    public float frametime;
    /// <summary>
    /// Vectors for angles
    /// </summary>
    /// <remarks>
    /// Original: Vector forward, right, up; // Vectors for angles
    /// </remarks>
    public Vector3 forward;
    /// <summary>
    /// Vectors for angles
    /// </summary>
    /// <remarks>
    /// Original: Vector forward, right, up; // Vectors for angles
    /// </remarks>
    public Vector3 right;
    /// <summary>
    /// Vectors for angles
    /// </summary>
    /// <remarks>
    /// Original: Vector forward, right, up; // Vectors for angles
    /// </remarks>
    public Vector3 up;
    /// <summary>
    /// Movement origin.
    /// </summary>
    /// <remarks>
    /// Original: Vector origin;		 // Movement origin.
    /// </remarks>
    public Vector3 origin;
    /// <summary>
    /// Movement view angles.
    /// </summary>
    /// <remarks>
    /// Original: Vector angles;		 // Movement view angles.
    /// </remarks>
    public Vector3 angles;
    /// <summary>
    /// Angles before movement view angles were looked at.
    /// </summary>
    /// <remarks>
    /// Original: Vector oldangles;	 // Angles before movement view angles were looked at.
    /// </remarks>
    public Vector3 oldangles;
    /// <summary>
    /// Current movement direction.
    /// </summary>
    /// <remarks>
    /// Original: Vector velocity;	 // Current movement direction.
    /// </remarks>
    public Vector3 velocity;
    /// <summary>
    /// For waterjumping, a forced forward velocity so we can fly over lip of ledge.
    /// </summary>
    /// <remarks>
    /// Original: Vector movedir;		 // For waterjumping, a forced forward velocity so we can fly over lip of ledge.
    /// </remarks>
    public Vector3 movedir;
    /// <summary>
    /// Velocity of the conveyor we are standing, e.g.
    /// </summary>
    /// <remarks>
    /// Original: Vector basevelocity; // Velocity of the conveyor we are standing, e.g.
    /// </remarks>
    public Vector3 basevelocity;
    /// <summary>
    /// Our eye position.
    /// </summary>
    /// <remarks>
    /// Original: Vector view_ofs;  // Our eye position.
    /// </remarks>
    public Vector3 view_ofs;
    /// <summary>
    /// Time we started duck
    /// </summary>
    /// <remarks>
    /// Original: float flDuckTime; // Time we started duck
    /// </remarks>
    public float flDuckTime;
    /// <summary>
    /// In process of ducking or ducked already?
    /// </summary>
    /// <remarks>
    /// Original: qboolean bInDuck; // In process of ducking or ducked already?
    /// </remarks>
    public qboolean bInDuck;
    /// <summary>
    /// Next time we can play a step sound
    /// </summary>
    /// <remarks>
    /// Original: int flTimeStepSound; // Next time we can play a step sound
    /// </remarks>
    public int flTimeStepSound;
    /// <remarks>
    /// Original: int iStepLeft;
    /// </remarks>
    public int iStepLeft;
    /// <remarks>
    /// Original: float flFallVelocity;
    /// </remarks>
    public float flFallVelocity;
    /// <remarks>
    /// Original: Vector punchangle;
    /// </remarks>
    public Vector3 punchangle;
    /// <remarks>
    /// Original: float flSwimTime;
    /// </remarks>
    public float flSwimTime;
    /// <remarks>
    /// Original: float flNextPrimaryAttack;
    /// </remarks>
    public float flNextPrimaryAttack;
    /// <summary>
    /// MUZZLE FLASH, e.g.
    /// </summary>
    /// <remarks>
    /// Original: int effects; // MUZZLE FLASH, e.g.
    /// </remarks>
    public int effects;
    /// <summary>
    /// FL_ONGROUND, FL_DUCKING, etc.
    /// </summary>
    /// <remarks>
    /// Original: int flags;	   // FL_ONGROUND, FL_DUCKING, etc.
    /// </remarks>
    public int flags;
    /// <summary>
    /// 0 = regular player hull, 1 = ducked player hull, 2 = point hull
    /// </summary>
    /// <remarks>
    /// Original: int usehull;   // 0 = regular player hull, 1 = ducked player hull, 2 = point hull
    /// </remarks>
    public int usehull;
    /// <summary>
    /// Our current gravity and friction.
    /// </summary>
    /// <remarks>
    /// Original: float gravity; // Our current gravity and friction.
    /// </remarks>
    public float gravity;
    /// <remarks>
    /// Original: float friction;
    /// </remarks>
    public float friction;
    /// <summary>
    /// Buttons last usercmd
    /// </summary>
    /// <remarks>
    /// Original: int oldbuttons;		 // Buttons last usercmd
    /// </remarks>
    public int oldbuttons;
    /// <summary>
    /// Amount of time left in jumping out of water cycle.
    /// </summary>
    /// <remarks>
    /// Original: float waterjumptime; // Amount of time left in jumping out of water cycle.
    /// </remarks>
    public float waterjumptime;
    /// <summary>
    /// Are we a dead player?
    /// </summary>
    /// <remarks>
    /// Original: qboolean dead;		 // Are we a dead player?
    /// </remarks>
    public qboolean dead;
    /// <remarks>
    /// Original: int deadflag;
    /// </remarks>
    public int deadflag;
    /// <summary>
    /// Should we use spectator physics model?
    /// </summary>
    /// <remarks>
    /// Original: int spectator; // Should we use spectator physics model?
    /// </remarks>
    public int spectator;
    /// <summary>
    /// Our movement type, NOCLIP, WALK, FLY
    /// </summary>
    /// <remarks>
    /// Original: int movetype;  // Our movement type, NOCLIP, WALK, FLY
    /// </remarks>
    public int movetype;
    /// <remarks>
    /// Original: int onground;
    /// </remarks>
    public int onground;
    /// <remarks>
    /// Original: int waterlevel;
    /// </remarks>
    public int waterlevel;
    /// <remarks>
    /// Original: int watertype;
    /// </remarks>
    public int watertype;
    /// <remarks>
    /// Original: int oldwaterlevel;
    /// </remarks>
    public int oldwaterlevel;
    /// <remarks>
    /// Original: char sztexturename[256];
    /// </remarks>
    public InlineArray256<NChar> sztexturename;
    /// <remarks>
    /// Original: char chtexturetype;
    /// </remarks>
    public NChar chtexturetype;
    /// <remarks>
    /// Original: float maxspeed;
    /// </remarks>
    public float maxspeed;
    /// <summary>
    /// Player specific maxspeed
    /// </summary>
    /// <remarks>
    /// Original: float clientmaxspeed; // Player specific maxspeed
    /// </remarks>
    public float clientmaxspeed;
    /// <summary>
    /// For mods
    /// </summary>
    /// <remarks>
    /// Original: int iuser1;
    /// </remarks>
    public int iuser1;
    /// <remarks>
    /// Original: int iuser2;
    /// </remarks>
    public int iuser2;
    /// <remarks>
    /// Original: int iuser3;
    /// </remarks>
    public int iuser3;
    /// <remarks>
    /// Original: int iuser4;
    /// </remarks>
    public int iuser4;
    /// <remarks>
    /// Original: float fuser1;
    /// </remarks>
    public float fuser1;
    /// <remarks>
    /// Original: float fuser2;
    /// </remarks>
    public float fuser2;
    /// <remarks>
    /// Original: float fuser3;
    /// </remarks>
    public float fuser3;
    /// <remarks>
    /// Original: float fuser4;
    /// </remarks>
    public float fuser4;
    /// <remarks>
    /// Original: Vector vuser1;
    /// </remarks>
    public Vector3 vuser1;
    /// <remarks>
    /// Original: Vector vuser2;
    /// </remarks>
    public Vector3 vuser2;
    /// <remarks>
    /// Original: Vector vuser3;
    /// </remarks>
    public Vector3 vuser3;
    /// <remarks>
    /// Original: Vector vuser4;
    /// </remarks>
    public Vector3 vuser4;
    /// <summary>
    /// world state
    /// Number of entities to clip against.
    /// </summary>
    /// <remarks>
    /// Original: int numphysent;
    /// </remarks>
    public int numphysent;
    /// <remarks>
    /// Original: physent_t physents[MAX_PHYSENTS];
    /// </remarks>
    public InlineArray600<physent_t> physents;
    /// <summary>
    /// Number of momvement entities (ladders)
    /// </summary>
    /// <remarks>
    /// Original: int nummoveent;
    /// </remarks>
    public int nummoveent;
    /// <summary>
    /// just a list of ladders
    /// </summary>
    /// <remarks>
    /// Original: physent_t moveents[MAX_MOVEENTS];
    /// </remarks>
    public InlineArray64<physent_t> moveents;
    /// <summary>
    /// All things being rendered, for tracing against things you don't actually collide with
    /// </summary>
    /// <remarks>
    /// Original: int numvisent;
    /// </remarks>
    public int numvisent;
    /// <remarks>
    /// Original: physent_t visents[MAX_PHYSENTS];
    /// </remarks>
    public InlineArray600<physent_t> visents;
    /// <summary>
    /// input to run through physics.
    /// </summary>
    /// <remarks>
    /// Original: usercmd_t cmd;
    /// </remarks>
    public usercmd_t cmd;
    /// <summary>
    /// Trace results for objects we collided with.
    /// </summary>
    /// <remarks>
    /// Original: int numtouch;
    /// </remarks>
    public int numtouch;
    /// <remarks>
    /// Original: pmtrace_t touchindex[MAX_PHYSENTS];
    /// </remarks>
    public InlineArray600<pmtrace_t> touchindex;
    /// <summary>
    /// Physics info string
    /// </summary>
    /// <remarks>
    /// Original: char physinfo[MAX_PHYSINFO_STRING]; // Physics info string
    /// </remarks>
    public InlineArray256<NChar> physinfo;
    /// <remarks>
    /// Original: struct movevars_s* movevars;
    /// </remarks>
    public movevars_t* movevars;
    /// <remarks>
    /// Original: Vector player_mins[4];
    /// </remarks>
    public InlineArray4<Vector3> player_mins;
    /// <remarks>
    /// Original: Vector player_maxs[4];
    /// </remarks>
    public InlineArray4<Vector3> player_maxs;
    /// <summary>
    /// Common functions
    /// </summary>
    /// <remarks>
    /// Original: const char* (*PM_Info_ValueForKey)(const char* s, const char* key);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar*, NChar*> PM_Info_ValueForKey;
    /// <remarks>
    /// Original: void (*PM_Particle)(float* origin, int color, float life, int zpos, int zvel);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, int, float, int, int, void> PM_Particle;
    /// <remarks>
    /// Original: int (*PM_TestPlayerPosition)(float* pos, pmtrace_t* ptrace);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, pmtrace_t*, int> PM_TestPlayerPosition;
    /// <remarks>
    /// Original: void (*Con_NPrintf)(int idx, const char* fmt, ...);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, NChar*, void> Con_NPrintf;
    /// <remarks>
    /// Original: void (*Con_DPrintf)(const char* fmt, ...);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, void> Con_DPrintf;
    /// <remarks>
    /// Original: void (*Con_Printf)(const char* fmt, ...);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, void> Con_Printf;
    /// <remarks>
    /// Original: double (*Sys_FloatTime)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<double> Sys_FloatTime;
    /// <remarks>
    /// Original: void (*PM_StuckTouch)(int hitent, pmtrace_t* ptraceresult);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, pmtrace_t*, void> PM_StuckTouch;
    /// <summary>
    /// filled in if this is non-null
    /// </summary>
    /// <remarks>
    /// Original: int (*PM_PointContents)(float* p, int* truecontents /*filled in if this is non-null*/);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, int*, int> PM_PointContents;
    /// <remarks>
    /// Original: int (*PM_TruePointContents)(float* p);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, int> PM_TruePointContents;
    /// <remarks>
    /// Original: int (*PM_HullPointContents)(struct hull_s* hull, int num, float* p);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<hull_t*, int, float*, int> PM_HullPointContents;
    /// <remarks>
    /// Original: pmtrace_t (*PM_PlayerTrace)(float* start, float* end, int traceFlags, int ignore_pe);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, int, int, pmtrace_t> PM_PlayerTrace;
    /// <remarks>
    /// Original: struct pmtrace_s* (*PM_TraceLine)(float* start, float* end, int flags, int usehulll, int ignore_pe);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, int, int, int, pmtrace_t*> PM_TraceLine;
    /// <remarks>
    /// Original: int32 (*RandomLong)(int32 lLow, int32 lHigh);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, int> RandomLong;
    /// <remarks>
    /// Original: float (*RandomFloat)(float flLow, float flHigh);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float, float, float> RandomFloat;
    /// <remarks>
    /// Original: int (*PM_GetModelType)(model_t* mod);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<model_t*, int> PM_GetModelType;
    /// <remarks>
    /// Original: void (*PM_GetModelBounds)(model_t* mod, float* mins, float* maxs);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<model_t*, float*, float*, void> PM_GetModelBounds;
    /// <remarks>
    /// Original: void* (*PM_HullForBsp)(physent_t* pe, float* offset);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<physent_t*, float*, void*> PM_HullForBsp;
    /// <remarks>
    /// Original: float (*PM_TraceModel)(physent_t* pEnt, const float* start, const float* end, trace_t* trace);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<physent_t*, float*, float*, trace_t*, float> PM_TraceModel;
    /// <remarks>
    /// Original: int (*COM_FileSize)(const char* filename);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int> COM_FileSize;
    /// <remarks>
    /// Original: byte* (*COM_LoadFile)(const char* path, int usehunk, int* pLength);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int, int*, byte*> COM_LoadFile;
    /// <remarks>
    /// Original: void (*COM_FreeFile)(void* buffer);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void*, void> COM_FreeFile;
    /// <remarks>
    /// Original: char* (*memfgets)(byte* pMemFile, int fileSize, int* pFilePos, char* pBuffer, int bufferSize);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<byte*, int, int*, NChar*, int, NChar*> memfgets;
    /// <summary>
    /// Functions
    /// Run functions for this frame?
    /// </summary>
    /// <remarks>
    /// Original: qboolean runfuncs;
    /// </remarks>
    public qboolean runfuncs;
    /// <remarks>
    /// Original: void (*PM_PlaySound)(int channel, const char* sample, float volume, float attenuation, int fFlags, int pitch);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, NChar*, float, float, int, int, void> PM_PlaySound;
    /// <remarks>
    /// Original: const char* (*PM_TraceTexture)(int ground, float* vstart, float* vend);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, float*, float*, NChar*> PM_TraceTexture;
    /// <remarks>
    /// Original: void (*PM_PlaybackEventFull)(int flags, int clientindex, unsigned short eventindex, float delay, float* origin, float* angles, float fparam1, float fparam2, int iparam1, int iparam2, int bparam1, int bparam2);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, ushort, float, float*, float*, float, float, int, int, int, int, void> PM_PlaybackEventFull;
    /// <remarks>
    /// Original: pmtrace_t (*PM_PlayerTraceEx)(float* start, float* end, int traceFlags, int (*pfnIgnore)(physent_t* pe));
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, int, delegate* unmanaged[Cdecl]<physent_t*, int>, pmtrace_t> PM_PlayerTraceEx;
    /// <remarks>
    /// Original: int (*PM_TestPlayerPositionEx)(float* pos, pmtrace_t* ptrace, int (*pfnIgnore)(physent_t* pe));
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, pmtrace_t*, delegate* unmanaged[Cdecl]<physent_t*, int>, int> PM_TestPlayerPositionEx;
    /// <remarks>
    /// Original: struct pmtrace_s* (*PM_TraceLineEx)(float* start, float* end, int flags, int usehulll, int (*pfnIgnore)(physent_t* pe));
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, int, int, delegate* unmanaged[Cdecl]<physent_t*, int>, pmtrace_t*> PM_TraceLineEx;
}

