<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

	<PropertyGroup>
		<!-- Workaround for issue https://github.com/microsoft/ClangSharp/issues/129 -->
		<RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' AND '$(PackAsTool)' != 'true'">$(NETCoreSdkRuntimeIdentifier)</RuntimeIdentifier>
	</PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="CppAst" Version="0.25.0" />
  </ItemGroup>

</Project>
