using System.Text;

namespace GoldsrcFramework.CodeGen;

/// <summary>A single adjustable symbol discovered while generating the humanized layer.</summary>
internal sealed record HumanizerSymbol(string Kind, string Path, string RawName, string EmittedName, string Source, string Target);

/// <summary>
/// Collects every symbol the humanizer produced so the result can be reviewed as a
/// catalog: which symbols exist, what they were emitted as, and whether that value came
/// from a rule in humanizer.rules or from the default naming rules.
/// </summary>
internal sealed class HumanizerSymbolCatalog
{
    readonly List<HumanizerSymbol> _symbols = [];

    public IReadOnlyList<HumanizerSymbol> Symbols => _symbols;

    public void Add(string kind, string path, string rawName, string emittedName, string source, string target = "") =>
        _symbols.Add(new HumanizerSymbol(kind, path, rawName, emittedName, source, target));

    /// <summary>Number of symbols whose value came from an explicit rule.</summary>
    public int RuleDrivenCount => _symbols.Count(s => s.Source.StartsWith("humanizer.rules:", StringComparison.Ordinal));

    public string ToMarkdown(IEnumerable<HumanizerRule> unusedRules, int totalRuleCount)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# HLSDK Humanizer Symbol Catalog");
        sb.AppendLine();
        sb.AppendLine("Generated by GoldsrcFramework.CodeGen. Every symbol listed here can be adjusted");
        sb.AppendLine("in `src/GoldsrcFramework.CodeGen/humanizer.rules` using the path in the **Symbol** column.");
        sb.AppendLine();
        sb.AppendLine($"* Symbols: {_symbols.Count} ({RuleDrivenCount} driven by rules)");
        sb.AppendLine($"* Rules loaded: {totalRuleCount}");

        var unused = unusedRules.ToList();
        sb.AppendLine($"* Rules that matched nothing: {unused.Count}");
        sb.AppendLine();

        if (unused.Count > 0)
        {
            sb.AppendLine("## Rules that matched nothing");
            sb.AppendLine();
            sb.AppendLine("These entries are stale or misspelled - check the symbol path against the tables below.");
            sb.AppendLine();
            sb.AppendLine("| Rule | Section | Pattern |");
            sb.AppendLine("|---|---|---|");
            foreach (var rule in unused.OrderBy(r => r.Line))
                sb.Append("| `").Append(rule.Location).Append("` | ").Append(HumanizerRules.SectionName(rule.Section)).Append(" | `").Append(rule.Pattern).AppendLine("` |");
            sb.AppendLine();
        }

        sb.AppendLine("## Symbols");
        sb.AppendLine();
        sb.AppendLine("| Target | Kind | Symbol | Raw | Emitted | Source |");
        sb.AppendLine("|---|---|---|---|---|---|");
        foreach (var symbol in _symbols.OrderBy(s => s.Target, StringComparer.OrdinalIgnoreCase).ThenBy(s => s.Kind, StringComparer.Ordinal).ThenBy(s => s.Path, StringComparer.Ordinal))
        {
            sb.Append("| `").Append(symbol.Target.Replace('\\', '/')).Append("` | ").Append(symbol.Kind)
              .Append(" | `").Append(symbol.Path).Append("` | `").Append(symbol.RawName)
              .Append("` | `").Append(symbol.EmittedName).Append("` | ").Append(symbol.Source).AppendLine(" |");
        }

        return sb.ToString();
    }
}
