using CppAst;
using System.Text;

namespace GoldsrcFramework.CodeGen;

/// <summary>
/// Generates the raw ABI layer (HlsdkNative.generated.cs) by walking the type graph
/// rooted at the engine/client function tables and exported API entry points.
/// </summary>
internal sealed class RawAbiGenerator
{
    readonly CppCompilation _compilation;
    readonly HumanizerRules _rules;
    readonly IReadOnlyList<string> _rootStructs;
    readonly IReadOnlyList<string> _managedNativeApiRootTypes;

    readonly Queue<CppType> _queue = new();

    readonly HashSet<string> _seen = [];
    readonly HashSet<int> _inlineArraySizes = [];

    readonly List<CppType> _ordered = [];
    readonly Dictionary<string, string> _pointerWrappers = [];
    readonly HashSet<string> _opaqueTypes = [];
    readonly Dictionary<string, string[]> _sourceLineCache = new(StringComparer.OrdinalIgnoreCase);

    public TypeNameResolver Resolver { get; }

    public HumanizerRules Rules => _rules;

    /// <summary>Types in deterministic emission order.</summary>
    public IReadOnlyList<CppType> Ordered => _ordered;

    /// <summary>Pointer wrapper structs required by array-of-pointer fields.</summary>
    public IReadOnlyDictionary<string, string> PointerWrappers => _pointerWrappers;

    public IReadOnlyCollection<int> RequiredInlineArraySizes => _inlineArraySizes;

    public int GeneratedTypeCount => _ordered.Count;

    public RawAbiGenerator(CppCompilation compilation, HumanizerRules rules, IReadOnlyList<string> rootStructs, IReadOnlyList<string> managedNativeApiRootTypes)
    {
        _compilation = compilation;
        _rules = rules;
        _rootStructs = rootStructs;
        _managedNativeApiRootTypes = managedNativeApiRootTypes;
        Resolver = new TypeNameResolver(compilation, rules, _opaqueTypes);
    }

    public string Generate()
    {
        foreach (var root in _rootStructs) EnqueueRootType(root);
        foreach (var c in _compilation.Classes.Where(c => _managedNativeApiRootTypes.Contains(Resolver.Name(c, false)) || _managedNativeApiRootTypes.Contains(c.Name))) Enqueue(c);

        foreach (var f in _compilation.Functions.Where(f => Path.GetFileName(f.SourceFile).Equals("Exports.h", StringComparison.OrdinalIgnoreCase))) { Enqueue(f.ReturnType); foreach (var p in f.Parameters) Enqueue(p.Type); }
        while (_queue.TryDequeue(out var type)) Visit(type);
        var sb = new StringBuilder("// <auto-generated/>\nusing System;\nusing System.Runtime.InteropServices;\nusing GoldsrcFramework.LinearMath;\nusing NativeInterop;\n\nnamespace GoldsrcFramework.Engine.Native.Generated;\n\n");
        foreach (var type in _ordered) EmitType(sb, type);
        foreach (var wrapper in _pointerWrappers.OrderBy(x => x.Key)) sb.Append("[StructLayout(LayoutKind.Sequential)]\npublic unsafe struct ").Append(wrapper.Key).Append(" { public ").Append(wrapper.Value).AppendLine(" Value; }\n");
        foreach (var opaque in _opaqueTypes.Order()) sb.Append("[StructLayout(LayoutKind.Sequential)]\npublic unsafe struct ").Append(opaque).AppendLine(" { }\n");

        return sb.ToString();
    }

    public string CreateManifest(string output, string hlsdk)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"HLSDK={hlsdk}");
        sb.AppendLine($"Output={output}");
        sb.AppendLine($"GeneratedTypeCount={GeneratedTypeCount}");
        sb.AppendLine("Roots=" + string.Join(",", _rootStructs));
        sb.AppendLine("Mappings=" + string.Join(",", _rules.RulesOf(HumanizerSection.TypeAliases).Select(x => x.Pattern + "=>" + x.Value)));
        sb.AppendLine("PointerWrappers=" + string.Join(",", _pointerWrappers.Select(x => x.Key + "=>" + x.Value)));

        sb.AppendLine("Types=" + string.Join(",", _ordered.Select(t => CppAstHelpers.NativeName(t) ?? Resolver.Name(t, false))));
        sb.AppendLine("InlineArraySizes=" + string.Join(",", _inlineArraySizes.Order()));

        sb.AppendLine("OpaqueTypes=" + string.Join(",", _opaqueTypes.Order()));


        return sb.ToString();
    }

    /// <summary>
    /// Emits the missing InlineArrayUnmanaged&lt;T&gt; definitions for the sizes the
    /// generated code requires, skipping sizes that already exist in handwritten files.
    /// </summary>
    public static string CreateInlineArrayDefinitions(string engineDir, IReadOnlyCollection<int> requiredSizes)
    {
        var existingSizes = Directory.GetFiles(engineDir, "InlineArrayUnmanaged*.cs")
            .Where(f => !Path.GetFileName(f).Equals("InlineArrayUnmanaged.Generated.cs", StringComparison.OrdinalIgnoreCase))
            .SelectMany(File.ReadAllLines)
            .Select(line => System.Text.RegularExpressions.Regex.Match(line, @"\[InlineArray\((\d+)\)\]"))
            .Where(match => match.Success)
            .Select(match => int.Parse(match.Groups[1].Value))
            .ToHashSet();

        var missingSizes = requiredSizes.Where(size => !existingSizes.Contains(size)).Order().ToList();
        var sb = new StringBuilder("// <auto-generated/>\nusing System.Runtime.CompilerServices;\n\nnamespace NativeInterop;\n\n");
        foreach (var size in missingSizes)
        {
            sb.Append("[InlineArray(").Append(size).AppendLine(")] ");
            sb.Append("public unsafe struct InlineArray").Append(size).AppendLine("<T> : IInlineArrayUnmanaged<T> where T : unmanaged");
            sb.AppendLine("{");
            sb.AppendLine("    public T Element0;");
            sb.AppendLine("}\n");
        }

        return sb.ToString();
    }

    void EnqueueRootType(string name)
    {
        if (Resolver.Typedefs.TryGetValue(name, out var typedef))
        {
            Enqueue(typedef);
            return;
        }

        var cls = _compilation.Classes.FirstOrDefault(c => string.Equals(c.Name, name, StringComparison.OrdinalIgnoreCase))
            ?? _compilation.Classes.FirstOrDefault(c => string.Equals(Resolver.Name(c, false), name, StringComparison.OrdinalIgnoreCase));
        if (cls is not null)
        {
            Enqueue(cls);
            return;
        }

        if (Resolver.Enums.TryGetValue(name, out var en)) Enqueue(en);
    }

    void Enqueue(CppType? type)
    {
        type = CppAstHelpers.Strip(type);
        if (type is CppUnexposedType u)
        {
            if (Resolver.Typedefs.TryGetValue(u.Name, out var td)) type = td;
            else if (Resolver.Classes.TryGetValue(u.Name, out var cls)) type = cls;
            else if (Resolver.Enums.TryGetValue(u.Name, out var en)) type = en;
        }

        if (type is null || type is CppPrimitiveType || type is CppPointerType || type is CppFunctionType || type is CppArrayType) return;
        var name = CppAstHelpers.NativeName(type);
        if (Resolver.IsSubstituted(name) || !_seen.Add(Resolver.Name(type, false))) return;
        _queue.Enqueue(type);
    }

    void Visit(CppType type)
    {
        type = CppAstHelpers.Strip(type)!;
        if (type is CppUnexposedType ux)
        {
            if (Resolver.Typedefs.TryGetValue(ux.Name, out var uxTypedef)) { Visit(uxTypedef); return; }
            if (Resolver.Classes.TryGetValue(ux.Name, out var cls)) { Visit(cls); return; }
            if (Resolver.Enums.TryGetValue(ux.Name, out var en)) { Visit(en); return; }
        }

        if (type is CppTypedef alias && alias.ElementType is CppClass or CppEnum or CppUnexposedType)
        {
            var target = CppAstHelpers.Strip(alias.ElementType)!;
            if (target is CppUnexposedType aliasUx)
            {
                if (Resolver.Classes.TryGetValue(aliasUx.Name, out var cls)) target = cls;
                else if (Resolver.Enums.TryGetValue(aliasUx.Name, out var en)) target = en;
            }
            _ordered.Add(target);
            if (target is CppClass aliasClass) foreach (var f in aliasClass.Fields) Collect(f.Type);
            return;
        }

        if (type is CppTypedef td && CppAstHelpers.IsFunctionPointer(td.ElementType)) { Visit(CppAstHelpers.UnwrapFunctionPointer(td.ElementType)!); return; }
        _ordered.Add(type);
        if (type is CppTypedef t) Enqueue(t.ElementType);
        else if (type is CppClass c) foreach (var f in c.Fields) Collect(f.Type);
    }

    void Collect(CppType? type)
    {
        type = CppAstHelpers.Strip(type);
        switch (type)
        {
            case null or CppPrimitiveType: return;
            case CppPointerType p: Collect(p.ElementType); return;
            case CppArrayType a: Collect(a.ElementType); return;
            case CppFunctionType f: Collect(f.ReturnType); foreach (var p in f.Parameters) Collect(p.Type); return;
            case CppTypedef td when CppAstHelpers.IsFunctionPointer(td.ElementType): Collect(CppAstHelpers.UnwrapFunctionPointer(td.ElementType)); return;
            case CppUnexposedType u when Resolver.Typedefs.TryGetValue(u.Name, out var resolved): Collect(resolved); return;
            case CppUnexposedType u when Resolver.Classes.TryGetValue(u.Name, out var resolvedClass): Collect(resolvedClass); return;
            case CppUnexposedType u when Resolver.Enums.TryGetValue(u.Name, out var resolvedEnum): Collect(resolvedEnum); return;

            default: Enqueue(type); return;
        }
    }

    void EmitType(StringBuilder sb, CppType type)
    {
        type = CppAstHelpers.Strip(type)!;
        if (type is CppTypedef td && td.ElementType is CppPrimitiveType)
        {
            EmitDeclarationComments(sb, td, "");
            sb.AppendLine("[StructLayout(LayoutKind.Sequential)]").Append("public struct ").Append(td.Name).Append(" { public ").Append(Resolver.Name(td.ElementType, false)).AppendLine(" Value; }\n");
            return;
        }
        if (type is CppEnum e)
        {
            EmitDeclarationComments(sb, e, "");
            sb.Append("public enum ").AppendLine(Resolver.Name(e, false)).AppendLine("{");
            foreach (var item in e.Items) sb.Append("    ").Append(item.Name).Append(" = ").Append(item.Value).AppendLine(",");
            sb.AppendLine("}\n");
            return;
        }
        if (type is not CppClass c || !c.IsDefinition) return;
        EmitDeclarationComments(sb, c, "");
        sb.AppendLine("[StructLayout(LayoutKind.Sequential)]").Append("public unsafe struct ").AppendLine(Resolver.Name(c, false)).AppendLine("{");
        foreach (var f in c.Fields)
        {
            EmitDeclarationComments(sb, f, "    ");
            sb.Append("    public ").Append(FieldType(f.Type)).Append(' ').Append(CppAstHelpers.Safe(f.Name)).AppendLine(";");
        }
        sb.AppendLine("}\n");
    }

    internal void EmitDeclarationComments(StringBuilder sb, CppElement element, string indent)
    {
        foreach (var line in GetCommentLines(element)) sb.Append(indent).Append("// ").AppendLine(line);
        var original = GetOriginalDeclarationLine(element);
        if (!string.IsNullOrWhiteSpace(original)) sb.Append(indent).Append("// Original: ").AppendLine(original);
    }

    internal IEnumerable<string> GetCommentLines(CppElement element)
    {
        if (element is not ICppDeclaration declaration || declaration.Comment is null) yield break;
        var text = declaration.Comment.ToString().Replace("\r", string.Empty).Trim();
        foreach (var line in text.Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            var cleaned = line.Trim().TrimStart('/', '*').Trim();
            if (!string.IsNullOrWhiteSpace(cleaned)) yield return cleaned;
        }
    }

    internal string? GetOriginalDeclarationLine(CppElement element)
    {
        var span = element.Span;
        if (string.IsNullOrWhiteSpace(span.Start.File) || span.Start.Line <= 0) return null;
        if (!File.Exists(span.Start.File)) return null;
        if (!_sourceLineCache.TryGetValue(span.Start.File, out var lines))
        {
            lines = File.ReadAllLines(span.Start.File);
            _sourceLineCache[span.Start.File] = lines;
        }
        var start = Math.Max(1, span.Start.Line);
        var end = span.End.Line > 0 ? Math.Min(span.End.Line, lines.Length) : start;
        if (start > lines.Length) return null;

        var selected = lines.Skip(start - 1).Take(Math.Max(1, end - start + 1))
            .Select(line => line.Trim())
            .Where(line => line.Length > 0)
            .ToList();
        if (selected.Count == 0) return null;

        var original = string.Join(" ", selected);
        return original.Length <= 240 ? original : original[..237] + "...";
    }

    string FieldType(CppType type) => type is CppArrayType a ? ArrayType(a) : Resolver.Name(type, true);

    string ArrayType(CppArrayType a)
    {
        _inlineArraySizes.Add(a.Size);
        var element = CppAstHelpers.Strip(a.ElementType)!;
        if (element is CppArrayType nested) return $"InlineArray{a.Size}<{ArrayType(nested)}>";
        if (element is CppPointerType)
        {
            var pointerType = Resolver.Name(element, true);
            var wrapperName = CppAstHelpers.PointerWrapperName(pointerType);
            _pointerWrappers.TryAdd(wrapperName, pointerType);
            return $"InlineArray{a.Size}<{wrapperName}>";
        }
        return $"InlineArray{a.Size}<{Resolver.Name(element, false)}>";
    }
}
