// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct net_status_s { // Connected to remote server?  1 == yes, 0 otherwise int connected; // Client's IP address netadr_t local_address; // Address of remote server netadr_t remote_address; // Packet Loss ( as a percentage ) int...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct net_status_t
{
    /// <summary>
    /// Connected to remote server?  1 == yes, 0 otherwise
    /// </summary>
    /// <remarks>
    /// Original: int connected;
    /// </remarks>
    public int connected;
    /// <summary>
    /// Client's IP address
    /// </summary>
    /// <remarks>
    /// Original: netadr_t local_address;
    /// </remarks>
    public netadr_t local_address;
    /// <summary>
    /// Address of remote server
    /// </summary>
    /// <remarks>
    /// Original: netadr_t remote_address;
    /// </remarks>
    public netadr_t remote_address;
    /// <summary>
    /// Packet Loss ( as a percentage )
    /// </summary>
    /// <remarks>
    /// Original: int packet_loss;
    /// </remarks>
    public int packet_loss;
    /// <summary>
    /// Latency, in seconds ( multiply by 1000.0 to get milliseconds )
    /// </summary>
    /// <remarks>
    /// Original: double latency;
    /// </remarks>
    public double latency;
    /// <summary>
    /// Connection time, in seconds
    /// </summary>
    /// <remarks>
    /// Original: double connection_time;
    /// </remarks>
    public double connection_time;
    /// <summary>
    /// Rate setting ( for incoming data )
    /// </summary>
    /// <remarks>
    /// Original: double rate;
    /// </remarks>
    public double rate;
}

