// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct net_response_s { // NET_SUCCESS or an error code int error; // Context ID int context; // Type int type; // Server that is responding to the request netadr_t remote_address; // Response RTT ping time double ping; // Key/Va...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct net_response_t
{
    /// <summary>
    /// NET_SUCCESS or an error code
    /// </summary>
    /// <remarks>
    /// Original: int error;
    /// </remarks>
    public int error;
    /// <summary>
    /// Context ID
    /// </summary>
    /// <remarks>
    /// Original: int context;
    /// </remarks>
    public int context;
    /// <summary>
    /// Type
    /// </summary>
    /// <remarks>
    /// Original: int type;
    /// </remarks>
    public int type;
    /// <summary>
    /// Server that is responding to the request
    /// </summary>
    /// <remarks>
    /// Original: netadr_t remote_address;
    /// </remarks>
    public netadr_t remote_address;
    /// <summary>
    /// Response RTT ping time
    /// </summary>
    /// <remarks>
    /// Original: double ping;
    /// </remarks>
    public double ping;
    /// <summary>
    /// Key/Value pair string ( separated by backlash
    /// \
    /// characters )
    /// WARNING:  You must copy this buffer in the callback function, because it is freed
    /// by the engine right after the call!!!!
    /// ALSO:  For NETAPI_REQUEST_SERVERLIST requests, this will be a pointer to a linked list of net_adrlist_t's
    /// </summary>
    /// <remarks>
    /// Original: void* response;
    /// </remarks>
    public void* response;
}

