// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct net_api_s { // APIs void (*InitNetworking)(void); void (*Status)(struct net_status_s* status); void (*SendRequest)(int context, int request, int flags, double timeout, struct netadr_s* remote_address, net_api_response_func...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct net_api_t
{
    /// <summary>
    /// APIs
    /// </summary>
    /// <remarks>
    /// Original: void (*InitNetworking)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> InitNetworking;
    /// <remarks>
    /// Original: void (*Status)(struct net_status_s* status);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<net_status_t*, void> Status;
    /// <remarks>
    /// Original: void (*SendRequest)(int context, int request, int flags, double timeout, struct netadr_s* remote_address, net_api_response_func_t response);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, int, double, netadr_t*, delegate* unmanaged[Cdecl]<net_response_t*, void>, void> SendRequest;
    /// <remarks>
    /// Original: void (*CancelRequest)(int context);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, void> CancelRequest;
    /// <remarks>
    /// Original: void (*CancelAllRequests)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> CancelAllRequests;
    /// <remarks>
    /// Original: char* (*AdrToString)(struct netadr_s* a);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<netadr_t*, NChar*> AdrToString;
    /// <remarks>
    /// Original: int (*CompareAdr)(struct netadr_s* a, struct netadr_s* b);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<netadr_t*, netadr_t*, int> CompareAdr;
    /// <remarks>
    /// Original: int (*StringToAdr)(char* s, struct netadr_s* a);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, netadr_t*, int> StringToAdr;
    /// <remarks>
    /// Original: const char* (*ValueForKey)(const char* s, const char* key);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar*, NChar*> ValueForKey;
    /// <remarks>
    /// Original: void (*RemoveKey)(char* s, const char* key);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar*, void> RemoveKey;
    /// <remarks>
    /// Original: void (*SetValueForKey)(char* s, const char* key, const char* value, int maxsize);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar*, NChar*, int, void> SetValueForKey;
}

