// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct mstudioevent_s { int frame; int event; int type; char options[64]; } mstudioevent_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct mstudioevent_t
{
    /// <remarks>
    /// Original: int frame;
    /// </remarks>
    public int frame;
    /// <remarks>
    /// Original: int event;
    /// </remarks>
    public int @event;
    /// <remarks>
    /// Original: int type;
    /// </remarks>
    public int type;
    /// <remarks>
    /// Original: char options[64];
    /// </remarks>
    public InlineArray64<NChar> options;
}

