// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct efrag_s { struct mleaf_s* leaf; struct efrag_s* leafnext; struct cl_entity_s* entity; struct efrag_s* entnext; } efrag_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct efrag_t
{
    /// <remarks>
    /// Original: struct mleaf_s* leaf;
    /// </remarks>
    public mleaf_t* leaf;
    /// <remarks>
    /// Original: struct efrag_s* leafnext;
    /// </remarks>
    public efrag_t* leafnext;
    /// <remarks>
    /// Original: struct cl_entity_s* entity;
    /// </remarks>
    public cl_entity_t* entity;
    /// <remarks>
    /// Original: struct efrag_s* entnext;
    /// </remarks>
    public efrag_t* entnext;
}

