// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct { float prevanimtime; float sequencetime; byte prevseqblending[2]; Vector prevorigin; Vector prevangles; int prevsequence; float prevframe; byte prevcontroller[4]; byte prevblending[2]; } latchedvars_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct latchedvars_t
{
    /// <remarks>
    /// Original: float prevanimtime;
    /// </remarks>
    public float prevanimtime;
    /// <remarks>
    /// Original: float sequencetime;
    /// </remarks>
    public float sequencetime;
    /// <remarks>
    /// Original: byte prevseqblending[2];
    /// </remarks>
    public InlineArray2<byte> prevseqblending;
    /// <remarks>
    /// Original: Vector prevorigin;
    /// </remarks>
    public Vector3 prevorigin;
    /// <remarks>
    /// Original: Vector prevangles;
    /// </remarks>
    public Vector3 prevangles;
    /// <remarks>
    /// Original: int prevsequence;
    /// </remarks>
    public int prevsequence;
    /// <remarks>
    /// Original: float prevframe;
    /// </remarks>
    public float prevframe;
    /// <remarks>
    /// Original: byte prevcontroller[4];
    /// </remarks>
    public InlineArray4<byte> prevcontroller;
    /// <remarks>
    /// Original: byte prevblending[2];
    /// </remarks>
    public InlineArray2<byte> prevblending;
}

