// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct { byte mouthopen; // 0 = mouth closed, 255 = mouth agape byte sndcount;	// counter for running average int sndavg;		// running average } mouth_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct mouth_t
{
    /// <summary>
    /// 0 = mouth closed, 255 = mouth agape
    /// </summary>
    /// <remarks>
    /// Original: byte mouthopen; // 0 = mouth closed, 255 = mouth agape
    /// </remarks>
    public byte mouthopen;
    /// <summary>
    /// counter for running average
    /// </summary>
    /// <remarks>
    /// Original: byte sndcount;	// counter for running average
    /// </remarks>
    public byte sndcount;
    /// <summary>
    /// running average
    /// </summary>
    /// <remarks>
    /// Original: int sndavg;		// running average
    /// </remarks>
    public int sndavg;
}

