// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct { // Time stamp for this movement float animtime; Vector origin; Vector angles; } position_history_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct position_history_t
{
    /// <summary>
    /// Time stamp for this movement
    /// </summary>
    /// <remarks>
    /// Original: float animtime;
    /// </remarks>
    public float animtime;
    /// <remarks>
    /// Original: Vector origin;
    /// </remarks>
    public Vector3 origin;
    /// <remarks>
    /// Original: Vector angles;
    /// </remarks>
    public Vector3 angles;
}

