// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// Source: external/hlsdk/engine/eiface.h only forward-declares/uses
/// struct delta_s* in engine callbacks. Public HLSDK does not expose layout.
/// </summary>
/// <remarks>
/// Original: struct delta_s { };
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct delta_s
{
}

