// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// Source: external/hlsdk/common/com_model.h only uses struct surfcache_s*.
/// Public HLSDK does not expose layout.
/// </summary>
/// <remarks>
/// Original: struct surfcache_s { };
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct surfcache_s
{
}

