// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct triangleapi_s { int version; void (*RenderMode)(int mode); void (*Begin)(int primitiveCode); void (*End)(void); void (*Color4f)(float r, float g, float b, float a); void (*Color4ub)(unsigned char r, unsigned char g, unsign...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct triangleapi_t
{
    /// <remarks>
    /// Original: int version;
    /// </remarks>
    public int version;
    /// <remarks>
    /// Original: void (*RenderMode)(int mode);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, void> RenderMode;
    /// <remarks>
    /// Original: void (*Begin)(int primitiveCode);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, void> Begin;
    /// <remarks>
    /// Original: void (*End)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> End;
    /// <remarks>
    /// Original: void (*Color4f)(float r, float g, float b, float a);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float, float, float, float, void> Color4f;
    /// <remarks>
    /// Original: void (*Color4ub)(unsigned char r, unsigned char g, unsigned char b, unsigned char a);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<byte, byte, byte, byte, void> Color4ub;
    /// <remarks>
    /// Original: void (*TexCoord2f)(float u, float v);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float, float, void> TexCoord2f;
    /// <remarks>
    /// Original: void (*Vertex3fv)(const float* worldPnt);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, void> Vertex3fv;
    /// <remarks>
    /// Original: void (*Vertex3f)(float x, float y, float z);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float, float, float, void> Vertex3f;
    /// <remarks>
    /// Original: void (*Brightness)(float brightness);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float, void> Brightness;
    /// <remarks>
    /// Original: void (*CullFace)(TRICULLSTYLE style);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<TRICULLSTYLE, void> CullFace;
    /// <remarks>
    /// Original: int (*SpriteTexture)(struct model_s* pSpriteModel, int frame);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<model_t*, int, int> SpriteTexture;
    /// <summary>
    /// Returns 1 if it's z clipped
    /// </summary>
    /// <remarks>
    /// Original: int (*WorldToScreen)(float* world, float* screen);					   // Returns 1 if it's z clipped
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, int> WorldToScreen;
    /// <summary>
    /// Works just like GL_FOG, flFogColor is r/g/b.
    /// </summary>
    /// <remarks>
    /// Original: void (*Fog)(float flFogColor[3], float flStart, float flEnd, int bOn); // Works just like GL_FOG, flFogColor is r/g/b.
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float, float, int, void> Fog;
    /// <remarks>
    /// Original: void (*ScreenToWorld)(float* screen, float* world);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, void> ScreenToWorld;
    /// <remarks>
    /// Original: void (*GetMatrix)(const int pname, float* matrix);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, float*, void> GetMatrix;
    /// <remarks>
    /// Original: int (*BoxInPVS)(float* mins, float* maxs);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, int> BoxInPVS;
    /// <remarks>
    /// Original: void (*LightAtPoint)(float* pos, float* value);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, void> LightAtPoint;
    /// <remarks>
    /// Original: void (*Color4fRendermode)(float r, float g, float b, float a, int rendermode);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float, float, float, float, int, void> Color4fRendermode;
    /// <summary>
    /// Used with Fog()...sets fog density and whether the fog should be applied to the skybox
    /// </summary>
    /// <remarks>
    /// Original: void (*FogParams)(float flDensity, int iFogSkybox); // Used with Fog()...sets fog density and whether the fog should be applied to the skybox
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float, int, void> FogParams;
}

