// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef enum { TRI_FRONT = 0, TRI_NONE = 1, } TRICULLSTYLE;
/// </remarks>
public enum TRICULLSTYLE
{
    TRI_FRONT = 0,
    TRI_NONE = 1,
}

