// <auto-generated/>
// Primitive codes accepted by triangleapi_t.Begin. These are the engine's TRI_*
// codes (not GL constants); the engine maps them internally to the renderer.
//
// Values cross-verified against two independent engine sources in this repo:
//   external/bare/common/triangleapi.h
//   external/xash3d-fwgs/common/triangleapi.h
// Both define the identical set. xash3d itself uses Begin(TRI_LINES) for its own
// debug line drawing in engine/client/cl_view.c:441.

namespace GoldsrcFramework.Engine.Native;

public enum TriPrimitive
{
    Triangles = 0,
    TriangleFan = 1,
    Quads = 2,
    Polygon = 3,
    Lines = 4,
    TriangleStrip = 5,
    QuadStrip = 6,
}
