// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// Pointers to the exported engine functions themselves
/// </summary>
/// <remarks>
/// Original: typedef struct cl_enginefuncs_s { pfnEngSrc_pfnSPR_Load_t pfnSPR_Load; pfnEngSrc_pfnSPR_Frames_t pfnSPR_Frames; pfnEngSrc_pfnSPR_Height_t pfnSPR_Height; pfnEngSrc_pfnSPR_Width_t pfnSPR_Width; pfnEngSrc_pfnSPR_Set_t pfnSPR_Set; pfnEngSrc_...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct ClientEngineFuncs
{
    /// <remarks>
    /// Original: pfnEngSrc_pfnSPR_Load_t pfnSPR_Load;
    /// Alias: typedef HSPRITE (*pfnEngSrc_pfnSPR_Load_t)(const char* szPicName);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, HSPRITE> SPR_Load;
    /// <remarks>
    /// Original: pfnEngSrc_pfnSPR_Frames_t pfnSPR_Frames;
    /// Alias: typedef int (*pfnEngSrc_pfnSPR_Frames_t)(HSPRITE hPic);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<HSPRITE, int> SPR_Frames;
    /// <remarks>
    /// Original: pfnEngSrc_pfnSPR_Height_t pfnSPR_Height;
    /// Alias: typedef int (*pfnEngSrc_pfnSPR_Height_t)(HSPRITE hPic, int frame);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<HSPRITE, int, int> SPR_Height;
    /// <remarks>
    /// Original: pfnEngSrc_pfnSPR_Width_t pfnSPR_Width;
    /// Alias: typedef int (*pfnEngSrc_pfnSPR_Width_t)(HSPRITE hPic, int frame);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<HSPRITE, int, int> SPR_Width;
    /// <remarks>
    /// Original: pfnEngSrc_pfnSPR_Set_t pfnSPR_Set;
    /// Alias: typedef void (*pfnEngSrc_pfnSPR_Set_t)(HSPRITE hPic, int r, int g, int b);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<HSPRITE, int, int, int, void> SPR_Set;
    /// <remarks>
    /// Original: pfnEngSrc_pfnSPR_Draw_t pfnSPR_Draw;
    /// Alias: typedef void (*pfnEngSrc_pfnSPR_Draw_t)(int frame, int x, int y, const Rect* prc);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, int, Rect*, void> SPR_Draw;
    /// <remarks>
    /// Original: pfnEngSrc_pfnSPR_DrawHoles_t pfnSPR_DrawHoles;
    /// Alias: typedef void (*pfnEngSrc_pfnSPR_DrawHoles_t)(int frame, int x, int y, const Rect* prc);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, int, Rect*, void> SPR_DrawHoles;
    /// <remarks>
    /// Original: pfnEngSrc_pfnSPR_DrawAdditive_t pfnSPR_DrawAdditive;
    /// Alias: typedef void (*pfnEngSrc_pfnSPR_DrawAdditive_t)(int frame, int x, int y, const Rect* prc);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, int, Rect*, void> SPR_DrawAdditive;
    /// <remarks>
    /// Original: pfnEngSrc_pfnSPR_EnableScissor_t pfnSPR_EnableScissor;
    /// Alias: typedef void (*pfnEngSrc_pfnSPR_EnableScissor_t)(int x, int y, int width, int height);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, int, int, void> SPR_EnableScissor;
    /// <remarks>
    /// Original: pfnEngSrc_pfnSPR_DisableScissor_t pfnSPR_DisableScissor;
    /// Alias: typedef void (*pfnEngSrc_pfnSPR_DisableScissor_t)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> SPR_DisableScissor;
    /// <remarks>
    /// Original: pfnEngSrc_pfnSPR_GetList_t pfnSPR_GetList;
    /// Alias: typedef struct client_sprite_s* (*pfnEngSrc_pfnSPR_GetList_t)(const char* psz, int* piCount);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int*, client_sprite_t*> SPR_GetList;
    /// <remarks>
    /// Original: pfnEngSrc_pfnFillRGBA_t pfnFillRGBA;
    /// Alias: typedef void (*pfnEngSrc_pfnFillRGBA_t)(int x, int y, int width, int height, int r, int g, int b, int a);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, int, int, int, int, int, int, void> FillRGBA;
    /// <remarks>
    /// Original: pfnEngSrc_pfnGetScreenInfo_t pfnGetScreenInfo;
    /// Alias: typedef int (*pfnEngSrc_pfnGetScreenInfo_t)(struct SCREENINFO_s* pscrinfo);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<SCREENINFO*, int> GetScreenInfo;
    /// <remarks>
    /// Original: pfnEngSrc_pfnSetCrosshair_t pfnSetCrosshair;
    /// Alias: typedef void (*pfnEngSrc_pfnSetCrosshair_t)(HSPRITE hspr, Rect rc, int r, int g, int b);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<HSPRITE, Rect, int, int, int, void> SetCrosshair;
    /// <remarks>
    /// Original: pfnEngSrc_pfnRegisterVariable_t pfnRegisterVariable;
    /// Alias: typedef struct cvar_s* (*pfnEngSrc_pfnRegisterVariable_t)(const char* szName, const char* szValue, int flags);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar*, int, cvar_t*> RegisterVariable;
    /// <remarks>
    /// Original: pfnEngSrc_pfnGetCvarFloat_t pfnGetCvarFloat;
    /// Alias: typedef float (*pfnEngSrc_pfnGetCvarFloat_t)(const char* szName);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, float> GetCvarFloat;
    /// <remarks>
    /// Original: pfnEngSrc_pfnGetCvarString_t pfnGetCvarString;
    /// Alias: typedef const char* (*pfnEngSrc_pfnGetCvarString_t)(const char* szName);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar*> GetCvarString;
    /// <remarks>
    /// Original: pfnEngSrc_pfnAddCommand_t pfnAddCommand;
    /// Alias: typedef int (*pfnEngSrc_pfnAddCommand_t)(const char* cmd_name, void (*pfnEngSrc_function)(void));
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, delegate* unmanaged[Cdecl]<void>, int> AddCommand;
    /// <remarks>
    /// Original: pfnEngSrc_pfnHookUserMsg_t pfnHookUserMsg;
    /// Alias: typedef int (*pfnEngSrc_pfnHookUserMsg_t)(const char* szMsgName, pfnUserMsgHook pfn);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, delegate* unmanaged[Cdecl]<NChar*, int, void*, int>, int> HookUserMsg;
    /// <remarks>
    /// Original: pfnEngSrc_pfnServerCmd_t pfnServerCmd;
    /// Alias: typedef int (*pfnEngSrc_pfnServerCmd_t)(const char* szCmdString);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int> ServerCmd;
    /// <remarks>
    /// Original: pfnEngSrc_pfnClientCmd_t pfnClientCmd;
    /// Alias: typedef int (*pfnEngSrc_pfnClientCmd_t)(const char* szCmdString);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int> ClientCmd;
    /// <remarks>
    /// Original: pfnEngSrc_pfnGetPlayerInfo_t pfnGetPlayerInfo;
    /// Alias: typedef void (*pfnEngSrc_pfnGetPlayerInfo_t)(int ent_num, struct hud_player_info_s* pinfo);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, hud_player_info_t*, void> GetPlayerInfo;
    /// <remarks>
    /// Original: pfnEngSrc_pfnPlaySoundByName_t pfnPlaySoundByName;
    /// Alias: typedef void (*pfnEngSrc_pfnPlaySoundByName_t)(const char* szSound, float volume);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, float, void> PlaySoundByName;
    /// <remarks>
    /// Original: pfnEngSrc_pfnPlaySoundByIndex_t pfnPlaySoundByIndex;
    /// Alias: typedef void (*pfnEngSrc_pfnPlaySoundByIndex_t)(int iSound, float volume);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, float, void> PlaySoundByIndex;
    /// <remarks>
    /// Original: pfnEngSrc_pfnAngleVectors_t pfnAngleVectors;
    /// Alias: typedef void (*pfnEngSrc_pfnAngleVectors_t)(const float* vecAngles, float* forward, float* right, float* up);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, float*, float*, void> AngleVectors;
    /// <remarks>
    /// Original: pfnEngSrc_pfnTextMessageGet_t pfnTextMessageGet;
    /// Alias: typedef struct client_textmessage_s* (*pfnEngSrc_pfnTextMessageGet_t)(const char* pName);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, client_textmessage_t*> TextMessageGet;
    /// <remarks>
    /// Original: pfnEngSrc_pfnDrawCharacter_t pfnDrawCharacter;
    /// Alias: typedef int (*pfnEngSrc_pfnDrawCharacter_t)(int x, int y, int number, int r, int g, int b);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, int, int, int, int, int> DrawCharacter;
    /// <remarks>
    /// Original: pfnEngSrc_pfnDrawConsoleString_t pfnDrawConsoleString;
    /// Alias: typedef int (*pfnEngSrc_pfnDrawConsoleString_t)(int x, int y, char* string);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, NChar*, int> DrawConsoleString;
    /// <remarks>
    /// Original: pfnEngSrc_pfnDrawSetTextColor_t pfnDrawSetTextColor;
    /// Alias: typedef void (*pfnEngSrc_pfnDrawSetTextColor_t)(float r, float g, float b);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float, float, float, void> DrawSetTextColor;
    /// <remarks>
    /// Original: pfnEngSrc_pfnDrawConsoleStringLen_t pfnDrawConsoleStringLen;
    /// Alias: typedef void (*pfnEngSrc_pfnDrawConsoleStringLen_t)(const char* string, int* length, int* height);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int*, int*, void> DrawConsoleStringLen;
    /// <remarks>
    /// Original: pfnEngSrc_pfnConsolePrint_t pfnConsolePrint;
    /// Alias: typedef void (*pfnEngSrc_pfnConsolePrint_t)(const char* string);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, void> ConsolePrint;
    /// <remarks>
    /// Original: pfnEngSrc_pfnCenterPrint_t pfnCenterPrint;
    /// Alias: typedef void (*pfnEngSrc_pfnCenterPrint_t)(const char* string);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, void> CenterPrint;
    /// <remarks>
    /// Original: pfnEngSrc_GetWindowCenterX_t GetWindowCenterX;
    /// Alias: typedef int (*pfnEngSrc_GetWindowCenterX_t)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> GetWindowCenterX;
    /// <remarks>
    /// Original: pfnEngSrc_GetWindowCenterY_t GetWindowCenterY;
    /// Alias: typedef int (*pfnEngSrc_GetWindowCenterY_t)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> GetWindowCenterY;
    /// <remarks>
    /// Original: pfnEngSrc_GetViewAngles_t GetViewAngles;
    /// Alias: typedef void (*pfnEngSrc_GetViewAngles_t)(float*);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, void> GetViewAngles;
    /// <remarks>
    /// Original: pfnEngSrc_SetViewAngles_t SetViewAngles;
    /// Alias: typedef void (*pfnEngSrc_SetViewAngles_t)(float*);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, void> SetViewAngles;
    /// <remarks>
    /// Original: pfnEngSrc_GetMaxClients_t GetMaxClients;
    /// Alias: typedef int (*pfnEngSrc_GetMaxClients_t)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> GetMaxClients;
    /// <remarks>
    /// Original: pfnEngSrc_Cvar_SetValue_t Cvar_SetValue;
    /// Alias: typedef void (*pfnEngSrc_Cvar_SetValue_t)(const char* cvar, float value);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, float, void> Cvar_SetValue;
    /// <remarks>
    /// Original: pfnEngSrc_Cmd_Argc_t Cmd_Argc;
    /// Alias: typedef int (*pfnEngSrc_Cmd_Argc_t)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> Cmd_Argc;
    /// <remarks>
    /// Original: pfnEngSrc_Cmd_Argv_t Cmd_Argv;
    /// Alias: typedef const char* (*pfnEngSrc_Cmd_Argv_t)(int arg);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, NChar*> Cmd_Argv;
    /// <remarks>
    /// Original: pfnEngSrc_Con_Printf_t Con_Printf;
    /// Alias: typedef void (*pfnEngSrc_Con_Printf_t)(const char* fmt, ...);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, void> Con_Printf;
    /// <remarks>
    /// Original: pfnEngSrc_Con_DPrintf_t Con_DPrintf;
    /// Alias: typedef void (*pfnEngSrc_Con_DPrintf_t)(const char* fmt, ...);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, void> Con_DPrintf;
    /// <remarks>
    /// Original: pfnEngSrc_Con_NPrintf_t Con_NPrintf;
    /// Alias: typedef void (*pfnEngSrc_Con_NPrintf_t)(int pos, const char* fmt, ...);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, NChar*, void> Con_NPrintf;
    /// <remarks>
    /// Original: pfnEngSrc_Con_NXPrintf_t Con_NXPrintf;
    /// Alias: typedef void (*pfnEngSrc_Con_NXPrintf_t)(struct con_nprint_s* info, const char* fmt, ...);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<con_nprint_t*, NChar*, void> Con_NXPrintf;
    /// <remarks>
    /// Original: pfnEngSrc_PhysInfo_ValueForKey_t PhysInfo_ValueForKey;
    /// Alias: typedef const char* (*pfnEngSrc_PhysInfo_ValueForKey_t)(const char* key);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar*> PhysInfo_ValueForKey;
    /// <remarks>
    /// Original: pfnEngSrc_ServerInfo_ValueForKey_t ServerInfo_ValueForKey;
    /// Alias: typedef const char* (*pfnEngSrc_ServerInfo_ValueForKey_t)(const char* key);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar*> ServerInfo_ValueForKey;
    /// <remarks>
    /// Original: pfnEngSrc_GetClientMaxspeed_t GetClientMaxspeed;
    /// Alias: typedef float (*pfnEngSrc_GetClientMaxspeed_t)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float> GetClientMaxspeed;
    /// <remarks>
    /// Original: pfnEngSrc_CheckParm_t CheckParm;
    /// Alias: typedef int (*pfnEngSrc_CheckParm_t)(const char* parm, const char** ppnext);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar**, int> CheckParm;
    /// <remarks>
    /// Original: pfnEngSrc_Key_Event_t Key_Event;
    /// Alias: typedef void (*pfnEngSrc_Key_Event_t)(int key, int down);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, void> Key_Event;
    /// <remarks>
    /// Original: pfnEngSrc_GetMousePosition_t GetMousePosition;
    /// Alias: typedef void (*pfnEngSrc_GetMousePosition_t)(int* mx, int* my);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int*, int*, void> GetMousePosition;
    /// <remarks>
    /// Original: pfnEngSrc_IsNoClipping_t IsNoClipping;
    /// Alias: typedef int (*pfnEngSrc_IsNoClipping_t)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> IsNoClipping;
    /// <remarks>
    /// Original: pfnEngSrc_GetLocalPlayer_t GetLocalPlayer;
    /// Alias: typedef struct cl_entity_s* (*pfnEngSrc_GetLocalPlayer_t)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<cl_entity_t*> GetLocalPlayer;
    /// <remarks>
    /// Original: pfnEngSrc_GetViewModel_t GetViewModel;
    /// Alias: typedef struct cl_entity_s* (*pfnEngSrc_GetViewModel_t)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<cl_entity_t*> GetViewModel;
    /// <remarks>
    /// Original: pfnEngSrc_GetEntityByIndex_t GetEntityByIndex;
    /// Alias: typedef struct cl_entity_s* (*pfnEngSrc_GetEntityByIndex_t)(int idx);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, cl_entity_t*> GetEntityByIndex;
    /// <remarks>
    /// Original: pfnEngSrc_GetClientTime_t GetClientTime;
    /// Alias: typedef float (*pfnEngSrc_GetClientTime_t)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float> GetClientTime;
    /// <remarks>
    /// Original: pfnEngSrc_V_CalcShake_t V_CalcShake;
    /// Alias: typedef void (*pfnEngSrc_V_CalcShake_t)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> V_CalcShake;
    /// <remarks>
    /// Original: pfnEngSrc_V_ApplyShake_t V_ApplyShake;
    /// Alias: typedef void (*pfnEngSrc_V_ApplyShake_t)(float* origin, float* angles, float factor);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, float, void> V_ApplyShake;
    /// <remarks>
    /// Original: pfnEngSrc_PM_PointContents_t PM_PointContents;
    /// Alias: typedef int (*pfnEngSrc_PM_PointContents_t)(float* point, int* truecontents);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, int*, int> PM_PointContents;
    /// <remarks>
    /// Original: pfnEngSrc_PM_WaterEntity_t PM_WaterEntity;
    /// Alias: typedef int (*pfnEngSrc_PM_WaterEntity_t)(float* p);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, int> PM_WaterEntity;
    /// <remarks>
    /// Original: pfnEngSrc_PM_TraceLine_t PM_TraceLine;
    /// Alias: typedef struct pmtrace_s* (*pfnEngSrc_PM_TraceLine_t)(float* start, float* end, int flags, int usehull, int ignore_pe);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, int, int, int, pmtrace_t*> PM_TraceLine;
    /// <remarks>
    /// Original: pfnEngSrc_CL_LoadModel_t CL_LoadModel;
    /// Alias: typedef struct model_s* (*pfnEngSrc_CL_LoadModel_t)(const char* modelname, int* index);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int*, model_t*> CL_LoadModel;
    /// <remarks>
    /// Original: pfnEngSrc_CL_CreateVisibleEntity_t CL_CreateVisibleEntity;
    /// Alias: typedef int (*pfnEngSrc_CL_CreateVisibleEntity_t)(int type, struct cl_entity_s* ent);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, cl_entity_t*, int> CL_CreateVisibleEntity;
    /// <remarks>
    /// Original: pfnEngSrc_GetSpritePointer_t GetSpritePointer;
    /// Alias: typedef const struct model_s* (*pfnEngSrc_GetSpritePointer_t)(HSPRITE hSprite);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<HSPRITE, model_t*> GetSpritePointer;
    /// <remarks>
    /// Original: pfnEngSrc_pfnPlaySoundByNameAtLocation_t pfnPlaySoundByNameAtLocation;
    /// Alias: typedef void (*pfnEngSrc_pfnPlaySoundByNameAtLocation_t)(const char* szSound, float volume, float* origin);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, float, float*, void> PlaySoundByNameAtLocation;
    /// <remarks>
    /// Original: pfnEngSrc_pfnPrecacheEvent_t pfnPrecacheEvent;
    /// Alias: typedef unsigned short (*pfnEngSrc_pfnPrecacheEvent_t)(int type, const char* psz);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, NChar*, ushort> PrecacheEvent;
    /// <remarks>
    /// Original: pfnEngSrc_pfnPlaybackEvent_t pfnPlaybackEvent;
    /// Alias: typedef void (*pfnEngSrc_pfnPlaybackEvent_t)(int flags, const struct edict_s* pInvoker, unsigned short eventindex, float delay, const float* origin, const float* angles, float fparam1, float fparam2, int iparam1, int iparam2, int bparam1...
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, edict_t*, ushort, float, float*, float*, float, float, int, int, int, int, void> PlaybackEvent;
    /// <remarks>
    /// Original: pfnEngSrc_pfnWeaponAnim_t pfnWeaponAnim;
    /// Alias: typedef void (*pfnEngSrc_pfnWeaponAnim_t)(int iAnim, int body);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, void> WeaponAnim;
    /// <remarks>
    /// Original: pfnEngSrc_pfnRandomFloat_t pfnRandomFloat;
    /// Alias: typedef float (*pfnEngSrc_pfnRandomFloat_t)(float flLow, float flHigh);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float, float, float> RandomFloat;
    /// <remarks>
    /// Original: pfnEngSrc_pfnRandomLong_t pfnRandomLong;
    /// Alias: typedef int32 (*pfnEngSrc_pfnRandomLong_t)(int32 lLow, int32 lHigh);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, int> RandomLong;
    /// <remarks>
    /// Original: pfnEngSrc_pfnHookEvent_t pfnHookEvent;
    /// Alias: typedef void (*pfnEngSrc_pfnHookEvent_t)(const char* name, void (*pfnEvent)(struct event_args_s* args));
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, delegate* unmanaged[Cdecl]<event_args_t*, void>, void> HookEvent;
    /// <remarks>
    /// Original: pfnEngSrc_Con_IsVisible_t Con_IsVisible;
    /// Alias: typedef int (*pfnEngSrc_Con_IsVisible_t)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> Con_IsVisible;
    /// <remarks>
    /// Original: pfnEngSrc_pfnGetGameDirectory_t pfnGetGameDirectory;
    /// Alias: typedef const char* (*pfnEngSrc_pfnGetGameDirectory_t)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*> GetGameDirectory;
    /// <remarks>
    /// Original: pfnEngSrc_pfnGetCvarPointer_t pfnGetCvarPointer;
    /// Alias: typedef struct cvar_s* (*pfnEngSrc_pfnGetCvarPointer_t)(const char* szName);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, cvar_t*> GetCvarPointer;
    /// <remarks>
    /// Original: pfnEngSrc_Key_LookupBinding_t Key_LookupBinding;
    /// Alias: typedef const char* (*pfnEngSrc_Key_LookupBinding_t)(const char* pBinding);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar*> Key_LookupBinding;
    /// <remarks>
    /// Original: pfnEngSrc_pfnGetLevelName_t pfnGetLevelName;
    /// Alias: typedef const char* (*pfnEngSrc_pfnGetLevelName_t)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*> GetLevelName;
    /// <remarks>
    /// Original: pfnEngSrc_pfnGetScreenFade_t pfnGetScreenFade;
    /// Alias: typedef void (*pfnEngSrc_pfnGetScreenFade_t)(struct screenfade_s* fade);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<screenfade_t*, void> GetScreenFade;
    /// <remarks>
    /// Original: pfnEngSrc_pfnSetScreenFade_t pfnSetScreenFade;
    /// Alias: typedef void (*pfnEngSrc_pfnSetScreenFade_t)(struct screenfade_s* fade);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<screenfade_t*, void> SetScreenFade;
    /// <remarks>
    /// Original: pfnEngSrc_VGui_GetPanel_t VGui_GetPanel;
    /// Alias: typedef void* (*pfnEngSrc_VGui_GetPanel_t)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void*> VGui_GetPanel;
    /// <remarks>
    /// Original: pfnEngSrc_VGui_ViewportPaintBackground_t VGui_ViewportPaintBackground;
    /// Alias: typedef void (*pfnEngSrc_VGui_ViewportPaintBackground_t)(int extents[4]);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int*, void> VGui_ViewportPaintBackground;
    /// <remarks>
    /// Original: pfnEngSrc_COM_LoadFile_t COM_LoadFile;
    /// Alias: typedef byte* (*pfnEngSrc_COM_LoadFile_t)(const char* path, int usehunk, int* pLength);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int, int*, byte*> COM_LoadFile;
    /// <remarks>
    /// Original: pfnEngSrc_COM_ParseFile_t COM_ParseFile;
    /// Alias: typedef char* (*pfnEngSrc_COM_ParseFile_t)(const char* data, char* token);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar*, NChar*> COM_ParseFile;
    /// <remarks>
    /// Original: pfnEngSrc_COM_FreeFile_t COM_FreeFile;
    /// Alias: typedef void (*pfnEngSrc_COM_FreeFile_t)(void* buffer);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void*, void> COM_FreeFile;
    /// <remarks>
    /// Original: struct triangleapi_s* pTriAPI;
    /// </remarks>
    public triangleapi_t* pTriAPI;
    /// <remarks>
    /// Original: struct efx_api_s* pEfxAPI;
    /// </remarks>
    public efx_api_t* pEfxAPI;
    /// <remarks>
    /// Original: struct event_api_s* pEventAPI;
    /// </remarks>
    public event_api_t* pEventAPI;
    /// <remarks>
    /// Original: struct demo_api_s* pDemoAPI;
    /// </remarks>
    public demo_api_t* pDemoAPI;
    /// <remarks>
    /// Original: struct net_api_s* pNetAPI;
    /// </remarks>
    public net_api_t* pNetAPI;
    /// <remarks>
    /// Original: struct IVoiceTweak_s* pVoiceTweak;
    /// </remarks>
    public IVoiceTweak* pVoiceTweak;
    /// <remarks>
    /// Original: pfnEngSrc_IsSpectateOnly_t IsSpectateOnly;
    /// Alias: typedef int (*pfnEngSrc_IsSpectateOnly_t)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> IsSpectateOnly;
    /// <remarks>
    /// Original: pfnEngSrc_LoadMapSprite_t LoadMapSprite;
    /// Alias: typedef struct model_s* (*pfnEngSrc_LoadMapSprite_t)(const char* filename);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, model_t*> LoadMapSprite;
    /// <remarks>
    /// Original: pfnEngSrc_COM_AddAppDirectoryToSearchPath_t COM_AddAppDirectoryToSearchPath;
    /// Alias: typedef void (*pfnEngSrc_COM_AddAppDirectoryToSearchPath_t)(const char* pszBaseDir, const char* appName);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar*, void> COM_AddAppDirectoryToSearchPath;
    /// <remarks>
    /// Original: pfnEngSrc_COM_ExpandFilename_t COM_ExpandFilename;
    /// Alias: typedef int (*pfnEngSrc_COM_ExpandFilename_t)(const char* fileName, char* nameOutBuffer, int nameOutBufferSize);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar*, int, int> COM_ExpandFilename;
    /// <remarks>
    /// Original: pfnEngSrc_PlayerInfo_ValueForKey_t PlayerInfo_ValueForKey;
    /// Alias: typedef const char* (*pfnEngSrc_PlayerInfo_ValueForKey_t)(int playerNum, const char* key);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, NChar*, NChar*> PlayerInfo_ValueForKey;
    /// <remarks>
    /// Original: pfnEngSrc_PlayerInfo_SetValueForKey_t PlayerInfo_SetValueForKey;
    /// Alias: typedef void (*pfnEngSrc_PlayerInfo_SetValueForKey_t)(const char* key, const char* value);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar*, void> PlayerInfo_SetValueForKey;
    /// <remarks>
    /// Original: pfnEngSrc_GetPlayerUniqueID_t GetPlayerUniqueID;
    /// Alias: typedef qboolean (*pfnEngSrc_GetPlayerUniqueID_t)(int iPlayer, char playerID[16]);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, NChar*, qboolean> GetPlayerUniqueID;
    /// <remarks>
    /// Original: pfnEngSrc_GetTrackerIDForPlayer_t GetTrackerIDForPlayer;
    /// Alias: typedef int (*pfnEngSrc_GetTrackerIDForPlayer_t)(int playerSlot);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int> GetTrackerIDForPlayer;
    /// <remarks>
    /// Original: pfnEngSrc_GetPlayerForTrackerID_t GetPlayerForTrackerID;
    /// Alias: typedef int (*pfnEngSrc_GetPlayerForTrackerID_t)(int trackerID);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int> GetPlayerForTrackerID;
    /// <remarks>
    /// Original: pfnEngSrc_pfnServerCmdUnreliable_t pfnServerCmdUnreliable;
    /// Alias: typedef int (*pfnEngSrc_pfnServerCmdUnreliable_t)(char* szCmdString);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int> ServerCmdUnreliable;
    /// <remarks>
    /// Original: pfnEngSrc_GetMousePos_t pfnGetMousePos;
    /// Alias: typedef void (*pfnEngSrc_GetMousePos_t)(Point* ppt);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<Point*, void> GetMousePos;
    /// <remarks>
    /// Original: pfnEngSrc_SetMousePos_t pfnSetMousePos;
    /// Alias: typedef void (*pfnEngSrc_SetMousePos_t)(int x, int y);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, void> SetMousePos;
    /// <remarks>
    /// Original: pfnEngSrc_SetMouseEnable_t pfnSetMouseEnable;
    /// Alias: typedef void (*pfnEngSrc_SetMouseEnable_t)(qboolean fEnable);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<qboolean, void> SetMouseEnable;
    /// <remarks>
    /// Original: pfnEngSrc_GetFirstCVarPtr_t GetFirstCvarPtr;
    /// Alias: typedef struct cvar_s* (*pfnEngSrc_GetFirstCVarPtr_t)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<cvar_t*> GetFirstCvarPtr;
    /// <remarks>
    /// Original: pfnEngSrc_GetFirstCmdFunctionHandle_t GetFirstCmdFunctionHandle;
    /// Alias: typedef unsigned int (*pfnEngSrc_GetFirstCmdFunctionHandle_t)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<uint> GetFirstCmdFunctionHandle;
    /// <remarks>
    /// Original: pfnEngSrc_GetNextCmdFunctionHandle_t GetNextCmdFunctionHandle;
    /// Alias: typedef unsigned int (*pfnEngSrc_GetNextCmdFunctionHandle_t)(unsigned int cmdhandle);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<uint, uint> GetNextCmdFunctionHandle;
    /// <remarks>
    /// Original: pfnEngSrc_GetCmdFunctionName_t GetCmdFunctionName;
    /// Alias: typedef const char* (*pfnEngSrc_GetCmdFunctionName_t)(unsigned int cmdhandle);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<uint, NChar*> GetCmdFunctionName;
    /// <remarks>
    /// Original: pfnEngSrc_GetClientOldTime_t hudGetClientOldTime;
    /// Alias: typedef float (*pfnEngSrc_GetClientOldTime_t)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float> hudGetClientOldTime;
    /// <remarks>
    /// Original: pfnEngSrc_GetServerGravityValue_t hudGetServerGravityValue;
    /// Alias: typedef float (*pfnEngSrc_GetServerGravityValue_t)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float> hudGetServerGravityValue;
    /// <remarks>
    /// Original: pfnEngSrc_GetModelByIndex_t hudGetModelByIndex;
    /// Alias: typedef struct model_s* (*pfnEngSrc_GetModelByIndex_t)(int index);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, model_t*> hudGetModelByIndex;
    /// <remarks>
    /// Original: pfnEngSrc_pfnSetFilterMode_t pfnSetFilterMode;
    /// Alias: typedef void (*pfnEngSrc_pfnSetFilterMode_t)(int mode);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, void> SetFilterMode;
    /// <remarks>
    /// Original: pfnEngSrc_pfnSetFilterColor_t pfnSetFilterColor;
    /// Alias: typedef void (*pfnEngSrc_pfnSetFilterColor_t)(float r, float g, float b);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float, float, float, void> SetFilterColor;
    /// <remarks>
    /// Original: pfnEngSrc_pfnSetFilterBrightness_t pfnSetFilterBrightness;
    /// Alias: typedef void (*pfnEngSrc_pfnSetFilterBrightness_t)(float brightness);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float, void> SetFilterBrightness;
    /// <remarks>
    /// Original: pfnEngSrc_pfnSequenceGet_t pfnSequenceGet;
    /// Alias: typedef sequenceEntry_s* (*pfnEngSrc_pfnSequenceGet_t)(const char* fileName, const char* entryName);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar*, sequenceEntry_s*> SequenceGet;
    /// <remarks>
    /// Original: pfnEngSrc_pfnSPR_DrawGeneric_t pfnSPR_DrawGeneric;
    /// Alias: typedef void (*pfnEngSrc_pfnSPR_DrawGeneric_t)(int frame, int x, int y, const Rect* prc, int src, int dest, int w, int h);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, int, Rect*, int, int, int, int, void> SPR_DrawGeneric;
    /// <remarks>
    /// Original: pfnEngSrc_pfnSequencePickSentence_t pfnSequencePickSentence;
    /// Alias: typedef sentenceEntry_s* (*pfnEngSrc_pfnSequencePickSentence_t)(const char* sentenceName, int pickMethod, int* entryPicked);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int, int*, sentenceEntry_s*> SequencePickSentence;
    /// <remarks>
    /// Original: pfnEngSrc_pfnDrawString_t pfnDrawString;
    /// Alias: typedef int (*pfnEngSrc_pfnDrawString_t)(int x, int y, const char* str, int r, int g, int b);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, NChar*, int, int, int, int> DrawString;
    /// <remarks>
    /// Original: pfnEngSrc_pfnDrawStringReverse_t pfnDrawStringReverse;
    /// Alias: typedef int (*pfnEngSrc_pfnDrawStringReverse_t)(int x, int y, const char* str, int r, int g, int b);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, NChar*, int, int, int, int> DrawStringReverse;
    /// <remarks>
    /// Original: pfnEngSrc_LocalPlayerInfo_ValueForKey_t LocalPlayerInfo_ValueForKey;
    /// Alias: typedef const char* (*pfnEngSrc_LocalPlayerInfo_ValueForKey_t)(const char* key);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar*> LocalPlayerInfo_ValueForKey;
    /// <remarks>
    /// Original: pfnEngSrc_pfnVGUI2DrawCharacter_t pfnVGUI2DrawCharacter;
    /// Alias: typedef int (*pfnEngSrc_pfnVGUI2DrawCharacter_t)(int x, int y, int ch, unsigned int font);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, int, uint, int> VGUI2DrawCharacter;
    /// <remarks>
    /// Original: pfnEngSrc_pfnVGUI2DrawCharacterAdd_t pfnVGUI2DrawCharacterAdd;
    /// Alias: typedef int (*pfnEngSrc_pfnVGUI2DrawCharacterAdd_t)(int x, int y, int ch, int r, int g, int b, unsigned int font);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, int, int, int, int, uint, int> VGUI2DrawCharacterAdd;
    /// <remarks>
    /// Original: pfnEngSrc_COM_GetApproxWavePlayLength COM_GetApproxWavePlayLength;
    /// Alias: typedef unsigned int (*pfnEngSrc_COM_GetApproxWavePlayLength)(const char* filename);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, uint> COM_GetApproxWavePlayLength;
    /// <remarks>
    /// Original: pfnEngSrc_pfnGetCareerUI_t pfnGetCareerUI;
    /// Alias: typedef void* (*pfnEngSrc_pfnGetCareerUI_t)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void*> GetCareerUI;
    /// <remarks>
    /// Original: pfnEngSrc_Cvar_Set_t Cvar_Set;
    /// Alias: typedef void (*pfnEngSrc_Cvar_Set_t)(const char* cvar, const char* value);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar*, void> Cvar_Set;
    /// <remarks>
    /// Original: pfnEngSrc_pfnIsPlayingCareerMatch_t pfnIsCareerMatch;
    /// Alias: typedef int (*pfnEngSrc_pfnIsPlayingCareerMatch_t)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> IsCareerMatch;
    /// <remarks>
    /// Original: pfnEngSrc_pfnPlaySoundVoiceByName_t pfnPlaySoundVoiceByName;
    /// Alias: typedef void (*pfnEngSrc_pfnPlaySoundVoiceByName_t)(const char* szSound, float volume, int pitch);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, float, int, void> PlaySoundVoiceByName;
    /// <remarks>
    /// Original: pfnEngSrc_pfnPrimeMusicStream_t pfnPrimeMusicStream;
    /// Alias: typedef void (*pfnEngSrc_pfnPrimeMusicStream_t)(const char* szFilename, int looping);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int, void> PrimeMusicStream;
    /// <remarks>
    /// Original: pfnEngSrc_GetAbsoluteTime_t GetAbsoluteTime;
    /// Alias: typedef double (*pfnEngSrc_GetAbsoluteTime_t)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<double> GetAbsoluteTime;
    /// <remarks>
    /// Original: pfnEngSrc_pfnProcessTutorMessageDecayBuffer_t pfnProcessTutorMessageDecayBuffer;
    /// Alias: typedef void (*pfnEngSrc_pfnProcessTutorMessageDecayBuffer_t)(int* buffer, int bufferLength);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int*, int, void> ProcessTutorMessageDecayBuffer;
    /// <remarks>
    /// Original: pfnEngSrc_pfnConstructTutorMessageDecayBuffer_t pfnConstructTutorMessageDecayBuffer;
    /// Alias: typedef void (*pfnEngSrc_pfnConstructTutorMessageDecayBuffer_t)(int* buffer, int bufferLength);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int*, int, void> ConstructTutorMessageDecayBuffer;
    /// <remarks>
    /// Original: pfnEngSrc_pfnResetTutorMessageDecayData_t pfnResetTutorMessageDecayData;
    /// Alias: typedef void (*pfnEngSrc_pfnResetTutorMessageDecayData_t)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> ResetTutorMessageDecayData;
    /// <remarks>
    /// Original: pfnEngSrc_pfnPlaySoundByNameAtPitch_t pfnPlaySoundByNameAtPitch;
    /// Alias: typedef void (*pfnEngSrc_pfnPlaySoundByNameAtPitch_t)(const char* szSound, float volume, int pitch);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, float, int, void> PlaySoundByNameAtPitch;
    /// <remarks>
    /// Original: pfnEngSrc_pfnFillRGBABlend_t pfnFillRGBABlend;
    /// Alias: typedef void (*pfnEngSrc_pfnFillRGBABlend_t)(int x, int y, int width, int height, int r, int g, int b, int a);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, int, int, int, int, int, int, void> FillRGBABlend;
    /// <remarks>
    /// Original: pfnEngSrc_pfnGetAppID_t pfnGetAppID;
    /// Alias: typedef int (*pfnEngSrc_pfnGetAppID_t)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> GetAppID;
    /// <remarks>
    /// Original: pfnEngSrc_pfnGetAliases_t pfnGetAliasList;
    /// Alias: typedef cmdalias_t* (*pfnEngSrc_pfnGetAliases_t)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<cmdalias_t*> GetAliasList;
    /// <remarks>
    /// Original: pfnEngSrc_pfnVguiWrap2_GetMouseDelta_t pfnVguiWrap2_GetMouseDelta;
    /// Alias: typedef void (*pfnEngSrc_pfnVguiWrap2_GetMouseDelta_t)(int* x, int* y);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int*, int*, void> VguiWrap2_GetMouseDelta;
    /// <remarks>
    /// Original: pfnEngSrc_pfnFilteredClientCmd_t pfnFilteredClientCmd;
    /// Alias: typedef int (*pfnEngSrc_pfnFilteredClientCmd_t)(const char* szCmdString);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int> FilteredClientCmd;
}

