// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// Pointers to the exported client functions themselves
/// </summary>
/// <remarks>
/// Original: typedef struct { INITIALIZE_FUNC pInitFunc; HUD_INIT_FUNC pHudInitFunc; HUD_VIDINIT_FUNC pHudVidInitFunc; HUD_REDRAW_FUNC pHudRedrawFunc; HUD_UPDATECLIENTDATA_FUNC pHudUpdateClientDataFunc; HUD_RESET_FUNC pHudResetFunc; HUD_CLIENTMOVE_FU...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct ClientExportFuncs
{
    /// <remarks>
    /// Original: INITIALIZE_FUNC pInitFunc;
    /// Alias: typedef int (*INITIALIZE_FUNC)(struct cl_enginefuncs_s*, int);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<ClientEngineFuncs*, int, int> Initialize;
    /// <remarks>
    /// Original: HUD_INIT_FUNC pHudInitFunc;
    /// Alias: typedef void (*HUD_INIT_FUNC)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> HUD_Init;
    /// <remarks>
    /// Original: HUD_VIDINIT_FUNC pHudVidInitFunc;
    /// Alias: typedef int (*HUD_VIDINIT_FUNC)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> HUD_VidInit;
    /// <remarks>
    /// Original: HUD_REDRAW_FUNC pHudRedrawFunc;
    /// Alias: typedef int (*HUD_REDRAW_FUNC)(float, int);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float, int, int> HUD_Redraw;
    /// <remarks>
    /// Original: HUD_UPDATECLIENTDATA_FUNC pHudUpdateClientDataFunc;
    /// Alias: typedef int (*HUD_UPDATECLIENTDATA_FUNC)(struct client_data_s*, float);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<client_data_t*, float, int> HUD_UpdateClientData;
    /// <remarks>
    /// Original: HUD_RESET_FUNC pHudResetFunc;
    /// Alias: typedef void (*HUD_RESET_FUNC)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> HUD_Reset;
    /// <remarks>
    /// Original: HUD_CLIENTMOVE_FUNC pClientMove;
    /// Alias: typedef void (*HUD_CLIENTMOVE_FUNC)(struct playermove_s* ppmove, qboolean server);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<playermove_t*, qboolean, void> HUD_PlayerMove;
    /// <remarks>
    /// Original: HUD_CLIENTMOVEINIT_FUNC pClientMoveInit;
    /// Alias: typedef void (*HUD_CLIENTMOVEINIT_FUNC)(struct playermove_s* ppmove);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<playermove_t*, void> HUD_PlayerMoveInit;
    /// <remarks>
    /// Original: HUD_TEXTURETYPE_FUNC pClientTextureType;
    /// Alias: typedef char (*HUD_TEXTURETYPE_FUNC)(char* name);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar> HUD_PlayerMoveTexture;
    /// <remarks>
    /// Original: HUD_IN_ACTIVATEMOUSE_FUNC pIN_ActivateMouse;
    /// Alias: typedef void (*HUD_IN_ACTIVATEMOUSE_FUNC)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> IN_ActivateMouse;
    /// <remarks>
    /// Original: HUD_IN_DEACTIVATEMOUSE_FUNC pIN_DeactivateMouse;
    /// Alias: typedef void (*HUD_IN_DEACTIVATEMOUSE_FUNC)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> IN_DeactivateMouse;
    /// <remarks>
    /// Original: HUD_IN_MOUSEEVENT_FUNC pIN_MouseEvent;
    /// Alias: typedef void (*HUD_IN_MOUSEEVENT_FUNC)(int mstate);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, void> IN_MouseEvent;
    /// <remarks>
    /// Original: HUD_IN_CLEARSTATES_FUNC pIN_ClearStates;
    /// Alias: typedef void (*HUD_IN_CLEARSTATES_FUNC)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> IN_ClearStates;
    /// <remarks>
    /// Original: HUD_IN_ACCUMULATE_FUNC pIN_Accumulate;
    /// Alias: typedef void (*HUD_IN_ACCUMULATE_FUNC)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> IN_Accumulate;
    /// <remarks>
    /// Original: HUD_CL_CREATEMOVE_FUNC pCL_CreateMove;
    /// Alias: typedef void (*HUD_CL_CREATEMOVE_FUNC)(float frametime, struct usercmd_s* cmd, int active);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float, usercmd_t*, int, void> CL_CreateMove;
    /// <remarks>
    /// Original: HUD_CL_ISTHIRDPERSON_FUNC pCL_IsThirdPerson;
    /// Alias: typedef int (*HUD_CL_ISTHIRDPERSON_FUNC)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> CL_IsThirdPerson;
    /// <remarks>
    /// Original: HUD_CL_GETCAMERAOFFSETS_FUNC pCL_GetCameraOffsets;
    /// Alias: typedef void (*HUD_CL_GETCAMERAOFFSETS_FUNC)(float* ofs);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, void> CL_CameraOffset;
    /// <remarks>
    /// Original: HUD_KB_FIND_FUNC pFindKey;
    /// Alias: typedef struct kbutton_s* (*HUD_KB_FIND_FUNC)(const char* name);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, kbutton_t*> KB_Find;
    /// <remarks>
    /// Original: HUD_CAMTHINK_FUNC pCamThink;
    /// Alias: typedef void (*HUD_CAMTHINK_FUNC)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> CAM_Think;
    /// <remarks>
    /// Original: HUD_CALCREF_FUNC pCalcRefdef;
    /// Alias: typedef void (*HUD_CALCREF_FUNC)(struct ref_params_s* pparams);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<ref_params_t*, void> V_CalcRefdef;
    /// <remarks>
    /// Original: HUD_ADDENTITY_FUNC pAddEntity;
    /// Alias: typedef int (*HUD_ADDENTITY_FUNC)(int type, struct cl_entity_s* ent, const char* modelname);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, cl_entity_t*, NChar*, int> HUD_AddEntity;
    /// <remarks>
    /// Original: HUD_CREATEENTITIES_FUNC pCreateEntities;
    /// Alias: typedef void (*HUD_CREATEENTITIES_FUNC)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> HUD_CreateEntities;
    /// <remarks>
    /// Original: HUD_DRAWNORMALTRIS_FUNC pDrawNormalTriangles;
    /// Alias: typedef void (*HUD_DRAWNORMALTRIS_FUNC)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> HUD_DrawNormalTriangles;
    /// <remarks>
    /// Original: HUD_DRAWTRANSTRIS_FUNC pDrawTransparentTriangles;
    /// Alias: typedef void (*HUD_DRAWTRANSTRIS_FUNC)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> HUD_DrawTransparentTriangles;
    /// <remarks>
    /// Original: HUD_STUDIOEVENT_FUNC pStudioEvent;
    /// Alias: typedef void (*HUD_STUDIOEVENT_FUNC)(const struct mstudioevent_s* event, const struct cl_entity_s* entity);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<mstudioevent_t*, cl_entity_t*, void> HUD_StudioEvent;
    /// <remarks>
    /// Original: HUD_POSTRUNCMD_FUNC pPostRunCmd;
    /// Alias: typedef void (*HUD_POSTRUNCMD_FUNC)(struct local_state_s* from, struct local_state_s* to, struct usercmd_s* cmd, int runfuncs, double time, unsigned int random_seed);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<local_state_t*, local_state_t*, usercmd_t*, int, double, uint, void> HUD_PostRunCmd;
    /// <remarks>
    /// Original: HUD_SHUTDOWN_FUNC pShutdown;
    /// Alias: typedef void (*HUD_SHUTDOWN_FUNC)(void);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> HUD_Shutdown;
    /// <remarks>
    /// Original: HUD_TXFERLOCALOVERRIDES_FUNC pTxferLocalOverrides;
    /// Alias: typedef void (*HUD_TXFERLOCALOVERRIDES_FUNC)(struct entity_state_s* state, const struct clientdata_s* client);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<entity_state_t*, clientdata_t*, void> HUD_TxferLocalOverrides;
    /// <remarks>
    /// Original: HUD_PROCESSPLAYERSTATE_FUNC pProcessPlayerState;
    /// Alias: typedef void (*HUD_PROCESSPLAYERSTATE_FUNC)(struct entity_state_s* dst, const struct entity_state_s* src);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<entity_state_t*, entity_state_t*, void> HUD_ProcessPlayerState;
    /// <remarks>
    /// Original: HUD_TXFERPREDICTIONDATA_FUNC pTxferPredictionData;
    /// Alias: typedef void (*HUD_TXFERPREDICTIONDATA_FUNC)(struct entity_state_s* ps, const struct entity_state_s* pps, struct clientdata_s* pcd, const struct clientdata_s* ppcd, struct weapon_data_s* wd, const struct weapon_data_s* pwd);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<entity_state_t*, entity_state_t*, clientdata_t*, clientdata_t*, weapon_data_t*, weapon_data_t*, void> HUD_TxferPredictionData;
    /// <remarks>
    /// Original: HUD_DEMOREAD_FUNC pReadDemoBuffer;
    /// Alias: typedef void (*HUD_DEMOREAD_FUNC)(int size, unsigned char* buffer);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, byte*, void> Demo_ReadBuffer;
    /// <remarks>
    /// Original: HUD_CONNECTIONLESS_FUNC pConnectionlessPacket;
    /// Alias: typedef int (*HUD_CONNECTIONLESS_FUNC)(const struct netadr_s* net_from, const char* args, char* response_buffer, int* response_buffer_size);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<netadr_t*, NChar*, NChar*, int*, int> HUD_ConnectionlessPacket;
    /// <remarks>
    /// Original: HUD_GETHULLBOUNDS_FUNC pGetHullBounds;
    /// Alias: typedef int (*HUD_GETHULLBOUNDS_FUNC)(int hullnumber, float* mins, float* maxs);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, float*, float*, int> HUD_GetHullBounds;
    /// <remarks>
    /// Original: HUD_FRAME_FUNC pHudFrame;
    /// Alias: typedef void (*HUD_FRAME_FUNC)(double);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<double, void> HUD_Frame;
    /// <remarks>
    /// Original: HUD_KEY_EVENT_FUNC pKeyEvent;
    /// Alias: typedef int (*HUD_KEY_EVENT_FUNC)(int eventcode, int keynum, const char* pszCurrentBinding);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, NChar*, int> HUD_Key_Event;
    /// <remarks>
    /// Original: HUD_TEMPENTUPDATE_FUNC pTempEntUpdate;
    /// Alias: typedef void (*HUD_TEMPENTUPDATE_FUNC)(double frametime, double client_time, double cl_gravity, struct tempent_s** ppTempEntFree, struct tempent_s** ppTempEntActive, int (*Callback_AddVisibleEntity)(struct cl_entity_s* pEntity), void (*C...
    /// </remarks>
    public delegate* unmanaged[Cdecl]<double, double, double, TEMPENTITY**, TEMPENTITY**, delegate* unmanaged[Cdecl]<cl_entity_t*, int>, delegate* unmanaged[Cdecl]<TEMPENTITY*, float, void>, void> HUD_TempEntUpdate;
    /// <remarks>
    /// Original: HUD_GETUSERENTITY_FUNC pGetUserEntity;
    /// Alias: typedef struct cl_entity_s* (*HUD_GETUSERENTITY_FUNC)(int index);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, cl_entity_t*> HUD_GetUserEntity;
    /// <summary>
    /// Possibly null on old client dlls.
    /// </summary>
    /// <remarks>
    /// Original: HUD_VOICESTATUS_FUNC pVoiceStatus;			   // Possibly null on old client dlls.
    /// Alias: typedef void (*HUD_VOICESTATUS_FUNC)(int entindex, qboolean bTalking);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, qboolean, void> HUD_VoiceStatus;
    /// <summary>
    /// Possibly null on old client dlls.
    /// </summary>
    /// <remarks>
    /// Original: HUD_DIRECTORMESSAGE_FUNC pDirectorMessage;	   // Possibly null on old client dlls.
    /// Alias: typedef void (*HUD_DIRECTORMESSAGE_FUNC)(int iSize, void* pbuf);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, void*, void> HUD_DirectorMessage;
    /// <summary>
    /// Not used by all clients
    /// </summary>
    /// <remarks>
    /// Original: HUD_STUDIO_INTERFACE_FUNC pStudioInterface;	   // Not used by all clients
    /// Alias: typedef int (*HUD_STUDIO_INTERFACE_FUNC)(int version, struct r_studio_interface_s** ppinterface, struct engine_studio_api_s* pstudio);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, r_studio_interface_t**, engine_studio_api_t*, int> HUD_GetStudioModelInterface;
    /// <summary>
    /// Not used by all clients
    /// </summary>
    /// <remarks>
    /// Original: HUD_CHATINPUTPOSITION_FUNC pChatInputPosition; // Not used by all clients
    /// Alias: typedef void (*HUD_CHATINPUTPOSITION_FUNC)(int* x, int* y);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int*, int*, void> HUD_ChatInputPosition;
    /// <summary>
    /// Not used by all clients
    /// </summary>
    /// <remarks>
    /// Original: HUD_GETPLAYERTEAM pGetPlayerTeam;			   // Not used by all clients
    /// Alias: typedef int (*HUD_GETPLAYERTEAM)(int iplayer);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int> HUD_GetPlayerTeam;
    /// <remarks>
    /// Original: CLIENTFACTORY pClientFactory;
    /// Alias: typedef void* (*CLIENTFACTORY)(); // this should be CreateInterfaceFn but that means including interface.h
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void*> ClientFactory;
}

