// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>Macros collapsed into an enum by [EntityType] from entity_types.h.
/// </summary>
/// <remarks>
/// Entity type handed to cldll_func_t.pAddEntity (HUD_AddEntity).
/// Macro: #define ET_BEAM 3
/// Macro: #define ET_FRAGMENTED 4
/// Macro: #define ET_NORMAL 0
/// Macro: #define ET_PLAYER 1
/// Macro: #define ET_TEMPENTITY 2
/// </remarks>
public enum EntityType : int
{
    BEAM = 3,
    FRAGMENTED = 4,
    NORMAL = 0,
    PLAYER = 1,
    TEMPENTITY = 2,
}

/// <summary>Macros collapsed into an enum by [EntityFlags] from const.h.
/// </summary>
/// <remarks>
/// entvars_t.flags bits. FL_DORMANT uses bit 31, so it is emitted as unchecked((int)0x80000000).
/// Macro: #define FL_ALWAYSTHINK (1&lt;&lt;21)
/// Macro: #define FL_BASEVELOCITY (1&lt;&lt;22)
/// Macro: #define FL_CLIENT (1&lt;&lt;3)
/// Macro: #define FL_CONVEYOR (1&lt;&lt;2)
/// Macro: #define FL_CUSTOMENTITY (1&lt;&lt;29)
/// Macro: #define FL_DORMANT (1&lt;&lt;31)
/// Macro: #define FL_DUCKING (1&lt;&lt;14)
/// Macro: #define FL_FAKECLIENT (1&lt;&lt;13)
/// Macro: #define FL_FLOAT (1&lt;&lt;15)
/// Macro: #define FL_FLY (1&lt;&lt;0)
/// Macro: #define FL_FROZEN (1&lt;&lt;12)
/// Macro: #define FL_GODMODE (1&lt;&lt;6)
/// Macro: #define FL_GRAPHED (1&lt;&lt;16)
/// Macro: #define FL_IMMUNE_LAVA (1&lt;&lt;19)
/// Macro: #define FL_IMMUNE_SLIME (1&lt;&lt;18)
/// Macro: #define FL_IMMUNE_WATER (1&lt;&lt;17)
/// Macro: #define FL_INWATER (1&lt;&lt;4)
/// Macro: #define FL_KILLME (1&lt;&lt;30)
/// Macro: #define FL_MONSTER (1&lt;&lt;5)
/// Macro: #define FL_MONSTERCLIP (1&lt;&lt;23)
/// Macro: #define FL_NOTARGET (1&lt;&lt;7)
/// Macro: #define FL_ONGROUND (1&lt;&lt;9)
/// Macro: #define FL_ONTRAIN (1&lt;&lt;24)
/// Macro: #define FL_PARTIALGROUND (1&lt;&lt;10)
/// Macro: #define FL_PROXY (1&lt;&lt;20)
/// Macro: #define FL_SKIPLOCALHOST (1&lt;&lt;8)
/// Macro: #define FL_SPECTATOR (1&lt;&lt;26)
/// Macro: #define FL_SWIM (1&lt;&lt;1)
/// Macro: #define FL_WATERJUMP (1&lt;&lt;11)
/// Macro: #define FL_WORLDBRUSH (1&lt;&lt;25)
/// </remarks>
public enum EntityFlags : int
{
    ALWAYSTHINK = 2097152,
    BASEVELOCITY = 4194304,
    CLIENT = 8,
    CONVEYOR = 4,
    CUSTOMENTITY = 536870912,
    DORMANT = unchecked((int)0x80000000),
    DUCKING = 16384,
    FAKECLIENT = 8192,
    FLOAT = 32768,
    FLY = 1,
    FROZEN = 4096,
    GODMODE = 64,
    GRAPHED = 65536,
    IMMUNE_LAVA = 524288,
    IMMUNE_SLIME = 262144,
    IMMUNE_WATER = 131072,
    INWATER = 16,
    KILLME = 1073741824,
    MONSTER = 32,
    MONSTERCLIP = 8388608,
    NOTARGET = 128,
    ONGROUND = 512,
    ONTRAIN = 16777216,
    PARTIALGROUND = 1024,
    PROXY = 1048576,
    SKIPLOCALHOST = 256,
    SPECTATOR = 67108864,
    SWIM = 2,
    WATERJUMP = 2048,
    WORLDBRUSH = 33554432,
}

/// <summary>Macros collapsed into an enum by [EntityStateFlags] from const.h.
/// </summary>
/// <remarks>
/// entity_state_t.eflags bits. The field is a byte in the ABI, so the enum is byte backed to keep the layout.
/// Macro: #define EFLAG_FLESH_SOUND 2
/// Macro: #define EFLAG_SLERP 1
/// </remarks>
public enum EntityStateFlags : byte
{
    FLESH_SOUND = 2,
    SLERP = 1,
}

/// <summary>Macros collapsed into an enum by [EntityEffects] from const.h.
/// </summary>
/// <remarks>
/// cl_entity_t.curstate.effects bits.
/// Macro: #define EF_BRIGHTFIELD 1
/// Macro: #define EF_BRIGHTLIGHT 4
/// Macro: #define EF_DIMLIGHT 8
/// Macro: #define EF_FIBERCAMERA 1024
/// Macro: #define EF_INVLIGHT 16
/// Macro: #define EF_LIGHT 64
/// Macro: #define EF_MUZZLEFLASH 2
/// Macro: #define EF_NIGHTVISION 256
/// Macro: #define EF_NODRAW 128
/// Macro: #define EF_NOINTERP 32
/// Macro: #define EF_SNIPERLASER 512
/// </remarks>
public enum EntityEffects : int
{
    BRIGHTFIELD = 1,
    BRIGHTLIGHT = 4,
    DIMLIGHT = 8,
    FIBERCAMERA = 1024,
    INVLIGHT = 16,
    LIGHT = 64,
    MUZZLEFLASH = 2,
    NIGHTVISION = 256,
    NODRAW = 128,
    NOINTERP = 32,
    SNIPERLASER = 512,
}

/// <summary>Macros collapsed into an enum by [MoveType] from const.h.
/// </summary>
/// <remarks>
/// entvars_t.movetype. Values 1 and 2 are commented out in const.h.
/// Macro: #define MOVETYPE_BOUNCE 10
/// Macro: #define MOVETYPE_BOUNCEMISSILE 11
/// Macro: #define MOVETYPE_FLY 5
/// Macro: #define MOVETYPE_FLYMISSILE 9
/// Macro: #define MOVETYPE_FOLLOW 12
/// Macro: #define MOVETYPE_NOCLIP 8
/// Macro: #define MOVETYPE_NONE 0
/// Macro: #define MOVETYPE_PUSH 7
/// Macro: #define MOVETYPE_PUSHSTEP 13
/// Macro: #define MOVETYPE_STEP 4
/// Macro: #define MOVETYPE_TOSS 6
/// Macro: #define MOVETYPE_WALK 3
/// </remarks>
public enum MoveType : int
{
    BOUNCE = 10,
    BOUNCEMISSILE = 11,
    FLY = 5,
    FLYMISSILE = 9,
    FOLLOW = 12,
    NOCLIP = 8,
    NONE = 0,
    PUSH = 7,
    PUSHSTEP = 13,
    STEP = 4,
    TOSS = 6,
    WALK = 3,
}

/// <summary>Macros collapsed into an enum by [WalkMoveMode] from const.h.
/// </summary>
/// <remarks>
/// Mode argument of the entity walkmove API.
/// Macro: #define WALKMOVE_CHECKONLY 2
/// Macro: #define WALKMOVE_NORMAL 0
/// Macro: #define WALKMOVE_WORLDONLY 1
/// </remarks>
public enum WalkMoveMode : int
{
    CHECKONLY = 2,
    NORMAL = 0,
    WORLDONLY = 1,
}

/// <summary>Macros collapsed into an enum by [SolidType] from const.h.
/// </summary>
/// <remarks>
/// entvars_t.solid.
/// Macro: #define SOLID_BBOX 2
/// Macro: #define SOLID_BSP 4
/// Macro: #define SOLID_NOT 0
/// Macro: #define SOLID_SLIDEBOX 3
/// Macro: #define SOLID_TRIGGER 1
/// </remarks>
public enum SolidType : int
{
    BBOX = 2,
    BSP = 4,
    NOT = 0,
    SLIDEBOX = 3,
    TRIGGER = 1,
}

/// <summary>Macros collapsed into an enum by [DeadState] from const.h.
/// </summary>
/// <remarks>
/// entvars_t.deadflag.
/// Macro: #define DEAD_DEAD 2
/// Macro: #define DEAD_DISCARDBODY 4
/// Macro: #define DEAD_DYING 1
/// Macro: #define DEAD_NO 0
/// Macro: #define DEAD_RESPAWNABLE 3
/// </remarks>
public enum DeadState : int
{
    DEAD = 2,
    DISCARDBODY = 4,
    DYING = 1,
    NO = 0,
    RESPAWNABLE = 3,
}

/// <summary>Macros collapsed into an enum by [DamageMode] from const.h.
/// </summary>
/// <remarks>
/// entvars_t.takedamage.
/// Macro: #define DAMAGE_AIM 2
/// Macro: #define DAMAGE_NO 0
/// Macro: #define DAMAGE_YES 1
/// </remarks>
public enum DamageMode : int
{
    AIM = 2,
    NO = 0,
    YES = 1,
}

/// <summary>Macros collapsed into an enum by [DamageType] from cdll_dll.h.
/// </summary>
/// <remarks>
/// Damage type bits taken by the damage API. The composite members (DMG_GIB_CORPSE, DMG_SHOWNHUD) combine several bits.
/// Macro: #define DMG_ACID (1&lt;&lt;20)
/// Macro: #define DMG_AIMED (1&lt;&lt;28)
/// Macro: #define DMG_ALWAYSGIB (1&lt;&lt;13)
/// Macro: #define DMG_BLAST (1&lt;&lt;6)
/// Macro: #define DMG_BULLET (1&lt;&lt;1)
/// Macro: #define DMG_BURN (1&lt;&lt;3)
/// Macro: #define DMG_CALTROP (1&lt;&lt;30)
/// Macro: #define DMG_CLUB (1&lt;&lt;7)
/// Macro: #define DMG_CONCUSS DMG_SONIC
/// Macro: #define DMG_CRUSH (1&lt;&lt;0)
/// Macro: #define DMG_DROWN (1&lt;&lt;14)
/// Macro: #define DMG_DROWNRECOVER (1&lt;&lt;19)
/// Macro: #define DMG_ENERGYBEAM (1&lt;&lt;10)
/// Macro: #define DMG_FALL (1&lt;&lt;5)
/// Macro: #define DMG_FIRSTTIMEBASED DMG_DROWN
/// Macro: #define DMG_FREEZE (1&lt;&lt;4)
/// Macro: #define DMG_GENERIC 0
/// Macro: #define DMG_GIB_CORPSE (DMG_CRUSH|DMG_FALL|DMG_BLAST|DMG_SONIC|DMG_CLUB)
/// Macro: #define DMG_HALLUC (1&lt;&lt;31)
/// Macro: #define DMG_IGNITE (1&lt;&lt;24)
/// Macro: #define DMG_IGNOREARMOR (1&lt;&lt;27)
/// Macro: #define DMG_IGNORE_MAXHEALTH DMG_IGNITE
/// Macro: #define DMG_MORTAR (1&lt;&lt;23)
/// Macro: #define DMG_NAIL DMG_SLASH
/// Macro: #define DMG_NERVEGAS (1&lt;&lt;16)
/// Macro: #define DMG_NEVERGIB (1&lt;&lt;12)
/// Macro: #define DMG_NOT_SELF DMG_FREEZE
/// Macro: #define DMG_PARALYZE (1&lt;&lt;15)
/// Macro: #define DMG_POISON (1&lt;&lt;17)
/// Macro: #define DMG_RADIATION (1&lt;&lt;18)
/// Macro: #define DMG_RADIUS_MAX (1&lt;&lt;25)
/// Macro: #define DMG_RADIUS_QUAKE (1&lt;&lt;26)
/// Macro: #define DMG_SHOCK (1&lt;&lt;8)
/// Macro: #define DMG_SHOWNHUD (DMG_POISON|DMG_ACID|DMG_FREEZE|DMG_SLOWFREEZE|DMG_DROWN|DMG_BURN|DMG_SLOWBURN|DMG_NERVEGAS|DMG_RADIATION|DMG_SHOCK)
/// Macro: #define DMG_SLASH (1&lt;&lt;2)
/// Macro: #define DMG_SLOWBURN (1&lt;&lt;21)
/// Macro: #define DMG_SLOWFREEZE (1&lt;&lt;22)
/// Macro: #define DMG_SONIC (1&lt;&lt;9)
/// Macro: #define DMG_TIMEBASED (~(0xff003fff))
/// Macro: #define DMG_TRANQ DMG_MORTAR
/// Macro: #define DMG_WALLPIERCING (1&lt;&lt;29)
/// </remarks>
public enum DamageType : int
{
    ACID = 1048576,
    AIMED = 268435456,
    ALWAYSGIB = 8192,
    BLAST = 64,
    BULLET = 2,
    BURN = 8,
    CALTROP = 1073741824,
    CLUB = 128,
    CONCUSS = 512,
    CRUSH = 1,
    DROWN = 16384,
    DROWNRECOVER = 524288,
    ENERGYBEAM = 1024,
    FALL = 32,
    FIRSTTIMEBASED = 16384,
    FREEZE = 16,
    GENERIC = 0,
    GIB_CORPSE = 737,
    HALLUC = unchecked((int)0x80000000),
    IGNITE = 16777216,
    IGNOREARMOR = 134217728,
    IGNORE_MAXHEALTH = 16777216,
    MORTAR = 8388608,
    NAIL = 4,
    NERVEGAS = 65536,
    NEVERGIB = 4096,
    NOT_SELF = 16,
    PARALYZE = 32768,
    POISON = 131072,
    RADIATION = 262144,
    RADIUS_MAX = 33554432,
    RADIUS_QUAKE = 67108864,
    SHOCK = 256,
    SHOWNHUD = 7815448,
    SLASH = 4,
    SLOWBURN = 2097152,
    SLOWFREEZE = 4194304,
    SONIC = 512,
    TIMEBASED = 16760832,
    TRANQ = 8388608,
    WALLPIERCING = 536870912,
}

/// <summary>Macros collapsed into an enum by [DamageImage] from health.h.
/// </summary>
/// <remarks>
/// Damage indicator slot indices of the client health HUD (cl_dll/health.h). DMG_IMAGE_LIFE is a duration in seconds rather than a slot, and shares its value with DMG_IMAGE_COLD.
/// Macro: #define DMG_IMAGE_ACID 1
/// Macro: #define DMG_IMAGE_BURN 4
/// Macro: #define DMG_IMAGE_CALTROP 8
/// Macro: #define DMG_IMAGE_COLD 2
/// Macro: #define DMG_IMAGE_CONCUSS 10
/// Macro: #define DMG_IMAGE_DROWN 3
/// Macro: #define DMG_IMAGE_HALLUC 11
/// Macro: #define DMG_IMAGE_LIFE 2
/// Macro: #define DMG_IMAGE_NERVE 5
/// Macro: #define DMG_IMAGE_POISON 0
/// Macro: #define DMG_IMAGE_RAD 6
/// Macro: #define DMG_IMAGE_SHOCK 7
/// Macro: #define DMG_IMAGE_TRANQ 9
/// </remarks>
public enum DamageImage : int
{
    ACID = 1,
    BURN = 4,
    CALTROP = 8,
    COLD = 2,
    CONCUSS = 10,
    DROWN = 3,
    HALLUC = 11,
    LIFE = 2,
    NERVE = 5,
    POISON = 0,
    RAD = 6,
    SHOCK = 7,
    TRANQ = 9,
}

/// <summary>Macros collapsed into an enum by [ExplosionFlags] from const.h.
/// </summary>
/// <remarks>
/// Flags of the TE_EXPLOSION message.
/// Macro: #define TE_EXPLFLAG_NOADDITIVE 1
/// Macro: #define TE_EXPLFLAG_NODLIGHTS 2
/// Macro: #define TE_EXPLFLAG_NONE 0
/// Macro: #define TE_EXPLFLAG_NOPARTICLES 8
/// Macro: #define TE_EXPLFLAG_NOSOUND 4
/// </remarks>
public enum ExplosionFlags : int
{
    NOADDITIVE = 1,
    NODLIGHTS = 2,
    NONE = 0,
    NOPARTICLES = 8,
    NOSOUND = 4,
}

/// <summary>Macros collapsed into an enum by [FireFieldFlags] from const.h.
/// </summary>
/// <remarks>
/// Flags of the TE_FIREFIELD message.
/// Macro: #define TEFIRE_FLAG_ADDITIVE 32
/// Macro: #define TEFIRE_FLAG_ALLFLOAT 1
/// Macro: #define TEFIRE_FLAG_ALPHA 8
/// Macro: #define TEFIRE_FLAG_LOOP 4
/// Macro: #define TEFIRE_FLAG_PLANAR 16
/// Macro: #define TEFIRE_FLAG_SOMEFLOAT 2
/// </remarks>
public enum FireFieldFlags : int
{
    ADDITIVE = 32,
    ALLFLOAT = 1,
    ALPHA = 8,
    LOOP = 4,
    PLANAR = 16,
    SOMEFLOAT = 2,
}

/// <summary>Macros collapsed into an enum by [BounceSound] from const.h.
/// </summary>
/// <remarks>
/// Sound selected by the TE_BREAKMODEL message.
/// Macro: #define TE_BOUNCE_NULL 0
/// Macro: #define TE_BOUNCE_SHELL 1
/// Macro: #define TE_BOUNCE_SHOTSHELL 2
/// </remarks>
public enum BounceSound : int
{
    NULL = 0,
    SHELL = 1,
    SHOTSHELL = 2,
}

/// <summary>Macros collapsed into an enum by [TempEntityType] from const.h.
/// </summary>
/// <remarks>
/// Message id of a temporary entity effect (TE_* in const.h).
/// Macro: #define TE_ARMOR_RICOCHET 111
/// Macro: #define TE_BEAM 16
/// Macro: #define TE_BEAMCYLINDER 21
/// Macro: #define TE_BEAMDISK 20
/// Macro: #define TE_BEAMENTPOINT 1
/// Macro: #define TE_BEAMENTS 8
/// Macro: #define TE_BEAMFOLLOW 22
/// Macro: #define TE_BEAMHOSE 26
/// Macro: #define TE_BEAMPOINTS 0
/// Macro: #define TE_BEAMRING 24
/// Macro: #define TE_BEAMSPRITE 18
/// Macro: #define TE_BEAMTORUS 19
/// Macro: #define TE_BLOOD 103
/// Macro: #define TE_BLOODSPRITE 115
/// Macro: #define TE_BLOODSTREAM 101
/// Macro: #define TE_BOX 31
/// Macro: #define TE_BREAKMODEL 108
/// Macro: #define TE_BSPDECAL 13
/// Macro: #define TE_BUBBLES 113
/// Macro: #define TE_BUBBLETRAIL 114
/// Macro: #define TE_DECAL 104
/// Macro: #define TE_DECALHIGH 118
/// Macro: #define TE_DLIGHT 27
/// Macro: #define TE_ELIGHT 28
/// Macro: #define TE_EXPLODEMODEL 107
/// Macro: #define TE_EXPLOSION 3
/// Macro: #define TE_EXPLOSION2 12
/// Macro: #define TE_FIREFIELD 123
/// Macro: #define TE_FIZZ 105
/// Macro: #define TE_GLOWSPRITE 23
/// Macro: #define TE_GUNSHOT 2
/// Macro: #define TE_GUNSHOTDECAL 109
/// Macro: #define TE_IMPLOSION 14
/// Macro: #define TE_KILLBEAM 99
/// Macro: #define TE_KILLPLAYERATTACHMENTS 125
/// Macro: #define TE_LARGEFUNNEL 100
/// Macro: #define TE_LAVASPLASH 10
/// Macro: #define TE_LIGHTNING 7
/// Macro: #define TE_LINE 30
/// Macro: #define TE_MODEL 106
/// Macro: #define TE_MULTIGUNSHOT 126
/// Macro: #define TE_PARTICLEBURST 122
/// Macro: #define TE_PLAYERATTACHMENT 124
/// Macro: #define TE_PLAYERDECAL 112
/// Macro: #define TE_PLAYERSPRITES 121
/// Macro: #define TE_PROJECTILE 119
/// Macro: #define TE_SHOWLINE 102
/// Macro: #define TE_SMOKE 5
/// Macro: #define TE_SPARKS 9
/// Macro: #define TE_SPRAY 120
/// Macro: #define TE_SPRITE 17
/// Macro: #define TE_SPRITETRAIL 15
/// Macro: #define TE_SPRITE_SPRAY 110
/// Macro: #define TE_STREAK_SPLASH 25
/// Macro: #define TE_TAREXPLOSION 4
/// Macro: #define TE_TELEPORT 11
/// Macro: #define TE_TEXTMESSAGE 29
/// Macro: #define TE_TRACER 6
/// Macro: #define TE_USERTRACER 127
/// Macro: #define TE_WORLDDECAL 116
/// Macro: #define TE_WORLDDECALHIGH 117
/// </remarks>
public enum TempEntityType : int
{
    ARMOR_RICOCHET = 111,
    BEAM = 16,
    BEAMCYLINDER = 21,
    BEAMDISK = 20,
    BEAMENTPOINT = 1,
    BEAMENTS = 8,
    BEAMFOLLOW = 22,
    BEAMHOSE = 26,
    BEAMPOINTS = 0,
    BEAMRING = 24,
    BEAMSPRITE = 18,
    BEAMTORUS = 19,
    BLOOD = 103,
    BLOODSPRITE = 115,
    BLOODSTREAM = 101,
    BOX = 31,
    BREAKMODEL = 108,
    BSPDECAL = 13,
    BUBBLES = 113,
    BUBBLETRAIL = 114,
    DECAL = 104,
    DECALHIGH = 118,
    DLIGHT = 27,
    ELIGHT = 28,
    EXPLODEMODEL = 107,
    EXPLOSION = 3,
    EXPLOSION2 = 12,
    FIREFIELD = 123,
    FIZZ = 105,
    GLOWSPRITE = 23,
    GUNSHOT = 2,
    GUNSHOTDECAL = 109,
    IMPLOSION = 14,
    KILLBEAM = 99,
    KILLPLAYERATTACHMENTS = 125,
    LARGEFUNNEL = 100,
    LAVASPLASH = 10,
    LIGHTNING = 7,
    LINE = 30,
    MODEL = 106,
    MULTIGUNSHOT = 126,
    PARTICLEBURST = 122,
    PLAYERATTACHMENT = 124,
    PLAYERDECAL = 112,
    PLAYERSPRITES = 121,
    PROJECTILE = 119,
    SHOWLINE = 102,
    SMOKE = 5,
    SPARKS = 9,
    SPRAY = 120,
    SPRITE = 17,
    SPRITETRAIL = 15,
    SPRITE_SPRAY = 110,
    STREAK_SPLASH = 25,
    TAREXPLOSION = 4,
    TELEPORT = 11,
    TEXTMESSAGE = 29,
    TRACER = 6,
    USERTRACER = 127,
    WORLDDECAL = 116,
    WORLDDECALHIGH = 117,
}

/// <summary>Macros collapsed into an enum by [Contents] from const.h.
/// </summary>
/// <remarks>
/// Contents of a leaf or point. The tab separated rows in const.h (CONTENTS_ORIGIN and friends) do not survive parsing, so this enum has fewer members than the header.
/// Macro: #define CONTENTS_EMPTY -1
/// Macro: #define CONTENTS_LADDER -16
/// Macro: #define CONTENTS_LAVA -5
/// Macro: #define CONTENTS_SKY -6
/// Macro: #define CONTENTS_SLIME -4
/// Macro: #define CONTENTS_SOLID -2
/// Macro: #define CONTENTS_WATER -3
/// </remarks>
public enum Contents : int
{
    EMPTY = -1,
    LADDER = -16,
    LAVA = -5,
    SKY = -6,
    SLIME = -4,
    SOLID = -2,
    WATER = -3,
}

/// <summary>Macros collapsed into an enum by [ContentType] from const.h.
/// </summary>
/// <remarks>
/// The second contents family. Its values overlap CONTENTS_* but the names differ, so the two are separate enums.
/// Macro: #define CONTENT_EMPTY -1
/// Macro: #define CONTENT_FLYFIELD -17
/// Macro: #define CONTENT_FOG -19
/// Macro: #define CONTENT_GRAVITY_FLYFIELD -18
/// Macro: #define CONTENT_LAVA -5
/// Macro: #define CONTENT_SKY -6
/// Macro: #define CONTENT_SLIME -4
/// Macro: #define CONTENT_SOLID -2
/// Macro: #define CONTENT_WATER -3
/// </remarks>
public enum ContentType : int
{
    EMPTY = -1,
    FLYFIELD = -17,
    FOG = -19,
    GRAVITY_FLYFIELD = -18,
    LAVA = -5,
    SKY = -6,
    SLIME = -4,
    SOLID = -2,
    WATER = -3,
}

/// <summary>Macros collapsed into an enum by [BreakMaterial] from const.h.
/// </summary>
/// <remarks>
/// Material of a breakable surface.
/// Macro: #define BREAK_2 0x80
/// Macro: #define BREAK_CONCRETE 0x40
/// Macro: #define BREAK_FLESH 0x04
/// Macro: #define BREAK_GLASS 0x01
/// Macro: #define BREAK_METAL 0x02
/// Macro: #define BREAK_SMOKE 0x10
/// Macro: #define BREAK_TRANS 0x20
/// Macro: #define BREAK_TYPEMASK 0x4F
/// Macro: #define BREAK_WOOD 0x08
/// </remarks>
public enum BreakMaterial : int
{
    _2 = 128,
    CONCRETE = 64,
    FLESH = 4,
    GLASS = 1,
    METAL = 2,
    SMOKE = 16,
    TRANS = 32,
    TYPEMASK = 79,
    WOOD = 8,
}

/// <summary>Macros collapsed into an enum by [BounceMaterial] from const.h.
/// </summary>
/// <remarks>
/// Bounce material. Several members alias the BREAK_* values.
/// Macro: #define BOUNCE_CONCRETE BREAK_CONCRETE
/// Macro: #define BOUNCE_FLESH BREAK_FLESH
/// Macro: #define BOUNCE_GLASS BREAK_GLASS
/// Macro: #define BOUNCE_METAL BREAK_METAL
/// Macro: #define BOUNCE_SHELL 0x20
/// Macro: #define BOUNCE_SHOTSHELL 0x80
/// Macro: #define BOUNCE_SHRAP 0x10
/// Macro: #define BOUNCE_WOOD BREAK_WOOD
/// </remarks>
public enum BounceMaterial : int
{
    CONCRETE = 64,
    FLESH = 4,
    GLASS = 1,
    METAL = 2,
    SHELL = 32,
    SHOTSHELL = 128,
    SHRAP = 16,
    WOOD = 8,
}

/// <summary>Macros collapsed into an enum by [TrainSpawnFlags] from const.h.
/// </summary>
/// <remarks>
/// Spawnflags of func_train.
/// Macro: #define SF_TRAIN_PASSABLE 8
/// Macro: #define SF_TRAIN_START_ON 4
/// Macro: #define SF_TRAIN_WAIT_RETRIGGER 1
/// </remarks>
public enum TrainSpawnFlags : int
{
    PASSABLE = 8,
    START_ON = 4,
    WAIT_RETRIGGER = 1,
}

/// <summary>Macros collapsed into an enum by [SoundChannel] from const.h.
/// </summary>
/// <remarks>
/// Channel passed to the sound API.
/// Macro: #define CHAN_AUTO 0
/// Macro: #define CHAN_BODY 4
/// Macro: #define CHAN_BOT 501
/// Macro: #define CHAN_ITEM 3
/// Macro: #define CHAN_NETWORKVOICE_BASE 7
/// Macro: #define CHAN_NETWORKVOICE_END 500
/// Macro: #define CHAN_STATIC 6
/// Macro: #define CHAN_STREAM 5
/// Macro: #define CHAN_VOICE 2
/// Macro: #define CHAN_WEAPON 1
/// </remarks>
public enum SoundChannel : int
{
    AUTO = 0,
    BODY = 4,
    BOT = 501,
    ITEM = 3,
    NETWORKVOICE_BASE = 7,
    NETWORKVOICE_END = 500,
    STATIC = 6,
    STREAM = 5,
    VOICE = 2,
    WEAPON = 1,
}

/// <summary>Macros collapsed into an enum by [Pitch] from const.h.
/// </summary>
/// <remarks>
/// Default pitch values.
/// Macro: #define PITCH_HIGH 120
/// Macro: #define PITCH_LOW 95
/// Macro: #define PITCH_NORM 100
/// </remarks>
public enum Pitch : int
{
    HIGH = 120,
    LOW = 95,
    NORM = 100,
}

/// <summary>Macros collapsed into an enum by [MessageDestination] from const.h.
/// </summary>
/// <remarks>
/// Destination of a server message.
/// Macro: #define MSG_ALL 2
/// Macro: #define MSG_BROADCAST 0
/// Macro: #define MSG_INIT 3
/// Macro: #define MSG_ONE 1
/// Macro: #define MSG_ONE_UNRELIABLE 8
/// Macro: #define MSG_PAS 5
/// Macro: #define MSG_PAS_R 7
/// Macro: #define MSG_PVS 4
/// Macro: #define MSG_PVS_R 6
/// Macro: #define MSG_SPEC 9
/// </remarks>
public enum MessageDestination : int
{
    ALL = 2,
    BROADCAST = 0,
    INIT = 3,
    ONE = 1,
    ONE_UNRELIABLE = 8,
    PAS = 5,
    PAS_R = 7,
    PVS = 4,
    PVS_R = 6,
    SPEC = 9,
}

/// <summary>Macros collapsed into an enum by [InputButtons] from in_buttons.h.
/// </summary>
/// <remarks>
/// usercmd_t button bits (common/in_buttons.h).
/// Macro: #define IN_ALT1 (1&lt;&lt;14)
/// Macro: #define IN_ATTACK (1&lt;&lt;0)
/// Macro: #define IN_ATTACK2 (1&lt;&lt;11)
/// Macro: #define IN_BACK (1&lt;&lt;4)
/// Macro: #define IN_CANCEL (1&lt;&lt;6)
/// Macro: #define IN_DUCK (1&lt;&lt;2)
/// Macro: #define IN_FORWARD (1&lt;&lt;3)
/// Macro: #define IN_JUMP (1&lt;&lt;1)
/// Macro: #define IN_LEFT (1&lt;&lt;7)
/// Macro: #define IN_MOVELEFT (1&lt;&lt;9)
/// Macro: #define IN_MOVERIGHT (1&lt;&lt;10)
/// Macro: #define IN_RELOAD (1&lt;&lt;13)
/// Macro: #define IN_RIGHT (1&lt;&lt;8)
/// Macro: #define IN_RUN (1&lt;&lt;12)
/// Macro: #define IN_SCORE (1&lt;&lt;15)
/// Macro: #define IN_USE (1&lt;&lt;5)
/// </remarks>
public enum InputButtons : int
{
    ALT1 = 16384,
    ATTACK = 1,
    ATTACK2 = 2048,
    BACK = 16,
    CANCEL = 64,
    DUCK = 4,
    FORWARD = 8,
    JUMP = 2,
    LEFT = 128,
    MOVELEFT = 512,
    MOVERIGHT = 1024,
    RELOAD = 8192,
    RIGHT = 256,
    RUN = 4096,
    SCORE = 32768,
    USE = 32,
}

/// <summary>Macros collapsed into an enum by [HideHudFlags] from cdll_dll.h.
/// </summary>
/// <remarks>
/// HUD elements hidden by the client (dlls/cdll_dll.h).
/// Macro: #define HIDEHUD_ALL (1&lt;&lt;2)
/// Macro: #define HIDEHUD_FLASHLIGHT (1&lt;&lt;1)
/// Macro: #define HIDEHUD_HEALTH (1&lt;&lt;3)
/// Macro: #define HIDEHUD_WEAPONS (1&lt;&lt;0)
/// </remarks>
public enum HideHudFlags : int
{
    ALL = 4,
    FLASHLIGHT = 2,
    HEALTH = 8,
    WEAPONS = 1,
}

/// <summary>Macros collapsed into an enum by [ScreenInfoFlags] from cdll_int.h.
/// </summary>
/// <remarks>
/// SCREENINFO.iFlags bits (engine/cdll_int.h).
/// Macro: #define SCRINFO_SCREENFLASH 1
/// Macro: #define SCRINFO_STRETCHED 2
/// </remarks>
public enum ScreenInfoFlags : int
{
    SCREENFLASH = 1,
    STRETCHED = 2,
}

/// <summary>Macros collapsed into an enum by [ScreenFadeFlags] from shake.h.
/// </summary>
/// <remarks>
/// screenfade_t.fadeFlags bits (engine/shake.h).
/// Macro: #define FFADE_IN 0x0000
/// Macro: #define FFADE_LONGFADE 0x0008
/// Macro: #define FFADE_MODULATE 0x0002
/// Macro: #define FFADE_OUT 0x0001
/// Macro: #define FFADE_STAYOUT 0x0004
/// </remarks>
public enum ScreenFadeFlags : int
{
    IN = 0,
    LONGFADE = 8,
    MODULATE = 2,
    OUT = 1,
    STAYOUT = 4,
}

/// <summary>Macros collapsed into an enum by [BeamFlags] from customentity.h.
/// </summary>
/// <remarks>
/// Beam draw flags (engine/customentity.h). The prefix has no trailing underscore.
/// Macro: #define BEAM_FSHADEIN 0x40
/// Macro: #define BEAM_FSHADEOUT 0x80
/// Macro: #define BEAM_FSINE 0x10
/// Macro: #define BEAM_FSOLID 0x20
/// </remarks>
public enum BeamFlags : int
{
    SHADEIN = 64,
    SHADEOUT = 128,
    SINE = 16,
    SOLID = 32,
}

/// <summary>Macros collapsed into an enum by [EntityTableFlags] from eiface.h.
/// </summary>
/// <remarks>
/// ENTITYTABLE.flags bits (engine/eiface.h). The top bits need unchecked((int)0x...).
/// Macro: #define FENTTABLE_GLOBAL 0x10000000
/// Macro: #define FENTTABLE_MOVEABLE 0x20000000
/// Macro: #define FENTTABLE_PLAYER 0x80000000
/// Macro: #define FENTTABLE_REMOVED 0x40000000
/// </remarks>
public enum EntityTableFlags : int
{
    GLOBAL = 268435456,
    MOVEABLE = 536870912,
    PLAYER = unchecked((int)0x80000000),
    REMOVED = 1073741824,
}

/// <summary>Macros collapsed into an enum by [StudioTextureFlags] from studio.h.
/// </summary>
/// <remarks>
/// mstudiotexture_t.flags bits (engine/studio.h).
/// Macro: #define STUDIO_NF_ADDITIVE 0x0020
/// Macro: #define STUDIO_NF_ALPHA 0x0010
/// Macro: #define STUDIO_NF_CHROME 0x0002
/// Macro: #define STUDIO_NF_FLATSHADE 0x0001
/// Macro: #define STUDIO_NF_FULLBRIGHT 0x0004
/// Macro: #define STUDIO_NF_MASKED 0x0040
/// Macro: #define STUDIO_NF_NOMIPS 0x0008
/// </remarks>
public enum StudioTextureFlags : int
{
    ADDITIVE = 32,
    ALPHA = 16,
    CHROME = 2,
    FLATSHADE = 1,
    FULLBRIGHT = 4,
    MASKED = 64,
    NOMIPS = 8,
}

/// <summary>Macros collapsed into an enum by [StudioHasFlags] from studio.h.
/// </summary>
/// <remarks>
/// studiohdr_t feature bits (engine/studio.h).
/// Macro: #define STUDIO_HAS_BBOX 0x0004
/// Macro: #define STUDIO_HAS_CHROME 0x0008
/// Macro: #define STUDIO_HAS_NORMALS 0x0001
/// Macro: #define STUDIO_HAS_VERTICES 0x0002
/// </remarks>
public enum StudioHasFlags : int
{
    BBOX = 4,
    CHROME = 8,
    NORMALS = 1,
    VERTICES = 2,
}

/// <summary>Macros collapsed into an enum by [StudioLooping] from studio.h.
/// </summary>
/// <remarks>
/// Sequence flag marking a looping animation (engine/studio.h).
/// Macro: #define STUDIO_LOOPING 0x0001
/// </remarks>
public enum StudioLooping : int
{
    LOOPING = 1,
}

