// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <summary>
/// Engine hands this to DLLs for functionality callbacks
/// </summary>
/// <remarks>
/// Original: typedef struct enginefuncs_s { int (*pfnPrecacheModel)(const char* s); int (*pfnPrecacheSound)(const char* s); void (*pfnSetModel)(edict_t* e, const char* m); int (*pfnModelIndex)(const char* m); int (*pfnModelFrames)(int modelIndex); vo...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct ServerEngineFuncs
{
    /// <remarks>
    /// Original: int (*pfnPrecacheModel)(const char* s);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int> PrecacheModel;
    /// <remarks>
    /// Original: int (*pfnPrecacheSound)(const char* s);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int> PrecacheSound;
    /// <remarks>
    /// Original: void (*pfnSetModel)(edict_t* e, const char* m);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, NChar*, void> SetModel;
    /// <remarks>
    /// Original: int (*pfnModelIndex)(const char* m);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int> ModelIndex;
    /// <remarks>
    /// Original: int (*pfnModelFrames)(int modelIndex);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int> ModelFrames;
    /// <remarks>
    /// Original: void (*pfnSetSize)(edict_t* e, const float* rgflMin, const float* rgflMax);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, float*, float*, void> SetSize;
    /// <remarks>
    /// Original: void (*pfnChangeLevel)(const char* s1, const char* s2);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar*, void> ChangeLevel;
    /// <remarks>
    /// Original: void (*pfnGetSpawnParms)(edict_t* ent);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, void> GetSpawnParms;
    /// <remarks>
    /// Original: void (*pfnSaveSpawnParms)(edict_t* ent);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, void> SaveSpawnParms;
    /// <remarks>
    /// Original: float (*pfnVecToYaw)(const float* rgflVector);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float> VecToYaw;
    /// <remarks>
    /// Original: void (*pfnVecToAngles)(const float* rgflVectorIn, float* rgflVectorOut);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, void> VecToAngles;
    /// <remarks>
    /// Original: void (*pfnMoveToOrigin)(edict_t* ent, const float* pflGoal, float dist, int iMoveType);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, float*, float, int, void> MoveToOrigin;
    /// <remarks>
    /// Original: void (*pfnChangeYaw)(edict_t* ent);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, void> ChangeYaw;
    /// <remarks>
    /// Original: void (*pfnChangePitch)(edict_t* ent);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, void> ChangePitch;
    /// <remarks>
    /// Original: edict_t* (*pfnFindEntityByString)(edict_t* pEdictStartSearchAfter, const char* pszField, const char* pszValue);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, NChar*, NChar*, edict_t*> FindEntityByString;
    /// <remarks>
    /// Original: int (*pfnGetEntityIllum)(edict_t* pEnt);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, int> GetEntityIllum;
    /// <remarks>
    /// Original: edict_t* (*pfnFindEntityInSphere)(edict_t* pEdictStartSearchAfter, const float* org, float rad);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, float*, float, edict_t*> FindEntityInSphere;
    /// <remarks>
    /// Original: edict_t* (*pfnFindClientInPVS)(edict_t* pEdict);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, edict_t*> FindClientInPVS;
    /// <remarks>
    /// Original: edict_t* (*pfnEntitiesInPVS)(edict_t* pplayer);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, edict_t*> EntitiesInPVS;
    /// <remarks>
    /// Original: void (*pfnMakeVectors)(const float* rgflVector);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, void> MakeVectors;
    /// <remarks>
    /// Original: void (*pfnAngleVectors)(const float* rgflVector, float* forward, float* right, float* up);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, float*, float*, void> AngleVectors;
    /// <remarks>
    /// Original: edict_t* (*pfnCreateEntity)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*> CreateEntity;
    /// <remarks>
    /// Original: void (*pfnRemoveEntity)(edict_t* e);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, void> RemoveEntity;
    /// <remarks>
    /// Original: edict_t* (*pfnCreateNamedEntity)(int className);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, edict_t*> CreateNamedEntity;
    /// <remarks>
    /// Original: void (*pfnMakeStatic)(edict_t* ent);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, void> MakeStatic;
    /// <remarks>
    /// Original: int (*pfnEntIsOnFloor)(edict_t* e);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, int> EntIsOnFloor;
    /// <remarks>
    /// Original: int (*pfnDropToFloor)(edict_t* e);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, int> DropToFloor;
    /// <remarks>
    /// Original: int (*pfnWalkMove)(edict_t* ent, float yaw, float dist, int iMode);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, float, float, int, int> WalkMove;
    /// <remarks>
    /// Original: void (*pfnSetOrigin)(edict_t* e, const float* rgflOrigin);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, float*, void> SetOrigin;
    /// <summary>
    /// int
    /// </summary>
    /// <remarks>
    /// Original: void (*pfnEmitSound)(edict_t* entity, int channel, const char* sample, /*int*/ float volume, float attenuation, int fFlags, int pitch);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, int, NChar*, float, float, int, int, void> EmitSound;
    /// <remarks>
    /// Original: void (*pfnEmitAmbientSound)(edict_t* entity, float* pos, const char* samp, float vol, float attenuation, int fFlags, int pitch);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, float*, NChar*, float, float, int, int, void> EmitAmbientSound;
    /// <remarks>
    /// Original: void (*pfnTraceLine)(const float* v1, const float* v2, int fNoMonsters, edict_t* pentToSkip, TraceResult* ptr);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, int, edict_t*, TraceResult*, void> TraceLine;
    /// <remarks>
    /// Original: void (*pfnTraceToss)(edict_t* pent, edict_t* pentToIgnore, TraceResult* ptr);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, edict_t*, TraceResult*, void> TraceToss;
    /// <remarks>
    /// Original: int (*pfnTraceMonsterHull)(edict_t* pEdict, const float* v1, const float* v2, int fNoMonsters, edict_t* pentToSkip, TraceResult* ptr);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, float*, float*, int, edict_t*, TraceResult*, int> TraceMonsterHull;
    /// <remarks>
    /// Original: void (*pfnTraceHull)(const float* v1, const float* v2, int fNoMonsters, int hullNumber, edict_t* pentToSkip, TraceResult* ptr);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, int, int, edict_t*, TraceResult*, void> TraceHull;
    /// <remarks>
    /// Original: void (*pfnTraceModel)(const float* v1, const float* v2, int hullNumber, edict_t* pent, TraceResult* ptr);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, int, edict_t*, TraceResult*, void> TraceModel;
    /// <remarks>
    /// Original: const char* (*pfnTraceTexture)(edict_t* pTextureEntity, const float* v1, const float* v2);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, float*, float*, NChar*> TraceTexture;
    /// <remarks>
    /// Original: void (*pfnTraceSphere)(const float* v1, const float* v2, int fNoMonsters, float radius, edict_t* pentToSkip, TraceResult* ptr);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, int, float, edict_t*, TraceResult*, void> TraceSphere;
    /// <remarks>
    /// Original: void (*pfnGetAimVector)(edict_t* ent, float speed, float* rgflReturn);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, float, float*, void> GetAimVector;
    /// <remarks>
    /// Original: void (*pfnServerCommand)(const char* str);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, void> ServerCommand;
    /// <remarks>
    /// Original: void (*pfnServerExecute)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> ServerExecute;
    /// <remarks>
    /// Original: void (*pfnClientCommand)(edict_t* pEdict, const char* szFmt, ...);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, NChar*, void> ClientCommand;
    /// <remarks>
    /// Original: void (*pfnParticleEffect)(const float* org, const float* dir, float color, float count);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, float*, float, float, void> ParticleEffect;
    /// <remarks>
    /// Original: void (*pfnLightStyle)(int style, const char* val);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, NChar*, void> LightStyle;
    /// <remarks>
    /// Original: int (*pfnDecalIndex)(const char* name);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int> DecalIndex;
    /// <remarks>
    /// Original: int (*pfnPointContents)(const float* rgflVector);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, int> PointContents;
    /// <remarks>
    /// Original: void (*pfnMessageBegin)(int msg_dest, int msg_type, const float* pOrigin, edict_t* ed);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, float*, edict_t*, void> MessageBegin;
    /// <remarks>
    /// Original: void (*pfnMessageEnd)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> MessageEnd;
    /// <remarks>
    /// Original: void (*pfnWriteByte)(int iValue);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, void> WriteByte;
    /// <remarks>
    /// Original: void (*pfnWriteChar)(int iValue);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, void> WriteChar;
    /// <remarks>
    /// Original: void (*pfnWriteShort)(int iValue);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, void> WriteShort;
    /// <remarks>
    /// Original: void (*pfnWriteLong)(int iValue);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, void> WriteLong;
    /// <remarks>
    /// Original: void (*pfnWriteAngle)(float flValue);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float, void> WriteAngle;
    /// <remarks>
    /// Original: void (*pfnWriteCoord)(float flValue);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float, void> WriteCoord;
    /// <remarks>
    /// Original: void (*pfnWriteString)(const char* sz);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, void> WriteString;
    /// <remarks>
    /// Original: void (*pfnWriteEntity)(int iValue);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, void> WriteEntity;
    /// <remarks>
    /// Original: void (*pfnCVarRegister)(cvar_t* pCvar);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<cvar_t*, void> CVarRegister;
    /// <remarks>
    /// Original: float (*pfnCVarGetFloat)(const char* szVarName);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, float> CVarGetFloat;
    /// <remarks>
    /// Original: const char* (*pfnCVarGetString)(const char* szVarName);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar*> CVarGetString;
    /// <remarks>
    /// Original: void (*pfnCVarSetFloat)(const char* szVarName, float flValue);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, float, void> CVarSetFloat;
    /// <remarks>
    /// Original: void (*pfnCVarSetString)(const char* szVarName, const char* szValue);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar*, void> CVarSetString;
    /// <remarks>
    /// Original: void (*pfnAlertMessage)(ALERT_TYPE atype, const char* szFmt, ...);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<ALERT_TYPE, NChar*, void> AlertMessage;
    /// <remarks>
    /// Original: void (*pfnEngineFprintf)(void* pfile, const char* szFmt, ...);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void*, NChar*, void> EngineFprintf;
    /// <remarks>
    /// Original: void* (*pfnPvAllocEntPrivateData)(edict_t* pEdict, int32 cb);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, int, void*> PvAllocEntPrivateData;
    /// <remarks>
    /// Original: void* (*pfnPvEntPrivateData)(edict_t* pEdict);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, void*> PvEntPrivateData;
    /// <remarks>
    /// Original: void (*pfnFreeEntPrivateData)(edict_t* pEdict);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, void> FreeEntPrivateData;
    /// <remarks>
    /// Original: const char* (*pfnSzFromIndex)(int iString);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, NChar*> SzFromIndex;
    /// <remarks>
    /// Original: int (*pfnAllocString)(const char* szValue);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int> AllocString;
    /// <remarks>
    /// Original: struct entvars_s* (*pfnGetVarsOfEnt)(edict_t* pEdict);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, entvars_t*> GetVarsOfEnt;
    /// <remarks>
    /// Original: edict_t* (*pfnPEntityOfEntOffset)(int iEntOffset);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, edict_t*> PEntityOfEntOffset;
    /// <remarks>
    /// Original: int (*pfnEntOffsetOfPEntity)(const edict_t* pEdict);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, int> EntOffsetOfPEntity;
    /// <remarks>
    /// Original: int (*pfnIndexOfEdict)(const edict_t* pEdict);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, int> IndexOfEdict;
    /// <remarks>
    /// Original: edict_t* (*pfnPEntityOfEntIndex)(int iEntIndex);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, edict_t*> PEntityOfEntIndex;
    /// <remarks>
    /// Original: edict_t* (*pfnFindEntityByVars)(struct entvars_s* pvars);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<entvars_t*, edict_t*> FindEntityByVars;
    /// <remarks>
    /// Original: void* (*pfnGetModelPtr)(edict_t* pEdict);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, void*> GetModelPtr;
    /// <remarks>
    /// Original: int (*pfnRegUserMsg)(const char* pszName, int iSize);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int, int> RegUserMsg;
    /// <remarks>
    /// Original: void (*pfnAnimationAutomove)(const edict_t* pEdict, float flTime);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, float, void> AnimationAutomove;
    /// <remarks>
    /// Original: void (*pfnGetBonePosition)(const edict_t* pEdict, int iBone, float* rgflOrigin, float* rgflAngles);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, int, float*, float*, void> GetBonePosition;
    /// <remarks>
    /// Original: uint32 (*pfnFunctionFromName)(const char* pName);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, uint> FunctionFromName;
    /// <remarks>
    /// Original: const char* (*pfnNameForFunction)(uint32 function);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<uint, NChar*> NameForFunction;
    /// <summary>
    /// JOHN: engine callbacks so game DLL can print messages to individual clients
    /// </summary>
    /// <remarks>
    /// Original: void (*pfnClientPrintf)(edict_t* pEdict, PRINT_TYPE ptype, const char* szMsg); // JOHN: engine callbacks so game DLL can print messages to individual clients
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, PRINT_TYPE, NChar*, void> ClientPrintf;
    /// <remarks>
    /// Original: void (*pfnServerPrint)(const char* szMsg);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, void> ServerPrint;
    /// <summary>
    /// these 3 added
    /// </summary>
    /// <remarks>
    /// Original: const char* (*pfnCmd_Args)();		  // these 3 added
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*> Cmd_Args;
    /// <summary>
    /// so game DLL can easily
    /// </summary>
    /// <remarks>
    /// Original: const char* (*pfnCmd_Argv)(int argc); // so game DLL can easily
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, NChar*> Cmd_Argv;
    /// <summary>
    /// access client 'cmd' strings
    /// </summary>
    /// <remarks>
    /// Original: int (*pfnCmd_Argc)();				  // access client 'cmd' strings
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> Cmd_Argc;
    /// <remarks>
    /// Original: void (*pfnGetAttachment)(const edict_t* pEdict, int iAttachment, float* rgflOrigin, float* rgflAngles);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, int, float*, float*, void> GetAttachment;
    /// <remarks>
    /// Original: void (*pfnCRC32_Init)(CRC32_t* pulCRC);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<uint*, void> CRC32_Init;
    /// <remarks>
    /// Original: void (*pfnCRC32_ProcessBuffer)(CRC32_t* pulCRC, void* p, int len);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<uint*, void*, int, void> CRC32_ProcessBuffer;
    /// <remarks>
    /// Original: void (*pfnCRC32_ProcessByte)(CRC32_t* pulCRC, unsigned char ch);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<uint*, byte, void> CRC32_ProcessByte;
    /// <remarks>
    /// Original: CRC32_t (*pfnCRC32_Final)(CRC32_t pulCRC);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<uint, uint> CRC32_Final;
    /// <remarks>
    /// Original: int32 (*pfnRandomLong)(int32 lLow, int32 lHigh);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, int> RandomLong;
    /// <remarks>
    /// Original: float (*pfnRandomFloat)(float flLow, float flHigh);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float, float, float> RandomFloat;
    /// <remarks>
    /// Original: void (*pfnSetView)(const edict_t* pClient, const edict_t* pViewent);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, edict_t*, void> SetView;
    /// <remarks>
    /// Original: float (*pfnTime)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float> Time;
    /// <remarks>
    /// Original: void (*pfnCrosshairAngle)(const edict_t* pClient, float pitch, float yaw);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, float, float, void> CrosshairAngle;
    /// <remarks>
    /// Original: byte* (*pfnLoadFileForMe)(const char* filename, int* pLength);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int*, byte*> LoadFileForMe;
    /// <remarks>
    /// Original: void (*pfnFreeFile)(void* buffer);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void*, void> FreeFile;
    /// <summary>
    /// trigger_endsection
    /// </summary>
    /// <remarks>
    /// Original: void (*pfnEndSection)(const char* pszSectionName); // trigger_endsection
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, void> EndSection;
    /// <remarks>
    /// Original: int (*pfnCompareFileTime)(const char* filename1, const char* filename2, int* iCompare);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar*, int*, int> CompareFileTime;
    /// <remarks>
    /// Original: void (*pfnGetGameDir)(char* szGetGameDir);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, void> GetGameDir;
    /// <remarks>
    /// Original: void (*pfnCvar_RegisterVariable)(cvar_t* variable);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<cvar_t*, void> Cvar_RegisterVariable;
    /// <remarks>
    /// Original: void (*pfnFadeClientVolume)(const edict_t* pEdict, int fadePercent, int fadeOutSeconds, int holdTime, int fadeInSeconds);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, int, int, int, int, void> FadeClientVolume;
    /// <remarks>
    /// Original: void (*pfnSetClientMaxspeed)(const edict_t* pEdict, float fNewMaxspeed);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, float, void> SetClientMaxspeed;
    /// <summary>
    /// returns NULL if fake client can't be created
    /// </summary>
    /// <remarks>
    /// Original: edict_t* (*pfnCreateFakeClient)(const char* netname); // returns NULL if fake client can't be created
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, edict_t*> CreateFakeClient;
    /// <remarks>
    /// Original: void (*pfnRunPlayerMove)(edict_t* fakeclient, const float* viewangles, float forwardmove, float sidemove, float upmove, unsigned short buttons, byte impulse, byte msec);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, float*, float, float, float, ushort, byte, byte, void> RunPlayerMove;
    /// <remarks>
    /// Original: int (*pfnNumberOfEntities)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> NumberOfEntities;
    /// <summary>
    /// passing in NULL gets the serverinfo
    /// </summary>
    /// <remarks>
    /// Original: char* (*pfnGetInfoKeyBuffer)(edict_t* e); // passing in NULL gets the serverinfo
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, NChar*> GetInfoKeyBuffer;
    /// <remarks>
    /// Original: char* (*pfnInfoKeyValue)(char* infobuffer, const char* key);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar*, NChar*> InfoKeyValue;
    /// <remarks>
    /// Original: void (*pfnSetKeyValue)(char* infobuffer, const char* key, const char* value);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar*, NChar*, void> SetKeyValue;
    /// <remarks>
    /// Original: void (*pfnSetClientKeyValue)(int clientIndex, char* infobuffer, const char* key, const char* value);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, NChar*, NChar*, NChar*, void> SetClientKeyValue;
    /// <remarks>
    /// Original: int (*pfnIsMapValid)(const char* filename);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int> IsMapValid;
    /// <remarks>
    /// Original: void (*pfnStaticDecal)(const float* origin, int decalIndex, int entityIndex, int modelIndex);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, int, int, int, void> StaticDecal;
    /// <remarks>
    /// Original: int (*pfnPrecacheGeneric)(const char* s);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int> PrecacheGeneric;
    /// <summary>
    /// returns the server assigned userid for this player.  useful for logging frags, etc.  returns -1 if the edict couldn't be found in the list of clients
    /// </summary>
    /// <remarks>
    /// Original: int (*pfnGetPlayerUserId)(edict_t* e); // returns the server assigned userid for this player.  useful for logging frags, etc.  returns -1 if the edict couldn't be found in the list of clients
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, int> GetPlayerUserId;
    /// <summary>
    /// int
    /// </summary>
    /// <remarks>
    /// Original: void (*pfnBuildSoundMsg)(edict_t* entity, int channel, const char* sample, /*int*/ float volume, float attenuation, int fFlags, int pitch, int msg_dest, int msg_type, const float* pOrigin, edict_t* ed);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, int, NChar*, float, float, int, int, int, int, float*, edict_t*, void> BuildSoundMsg;
    /// <summary>
    /// is this a dedicated server?
    /// </summary>
    /// <remarks>
    /// Original: int (*pfnIsDedicatedServer)(); // is this a dedicated server?
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> IsDedicatedServer;
    /// <remarks>
    /// Original: cvar_t* (*pfnCVarGetPointer)(const char* szVarName);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, cvar_t*> CVarGetPointer;
    /// <summary>
    /// returns the server assigned WONid for this player.  useful for logging frags, etc.  returns -1 if the edict couldn't be found in the list of clients
    /// </summary>
    /// <remarks>
    /// Original: unsigned int (*pfnGetPlayerWONId)(edict_t* e); // returns the server assigned WONid for this player.  useful for logging frags, etc.  returns -1 if the edict couldn't be found in the list of clients
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, uint> GetPlayerWONId;
    /// <summary>
    /// YWB 8/1/99 TFF Physics additions
    /// </summary>
    /// <remarks>
    /// Original: void (*pfnInfo_RemoveKey)(char* s, const char* key);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar*, void> Info_RemoveKey;
    /// <remarks>
    /// Original: const char* (*pfnGetPhysicsKeyValue)(const edict_t* pClient, const char* key);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, NChar*, NChar*> GetPhysicsKeyValue;
    /// <remarks>
    /// Original: void (*pfnSetPhysicsKeyValue)(const edict_t* pClient, const char* key, const char* value);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, NChar*, NChar*, void> SetPhysicsKeyValue;
    /// <remarks>
    /// Original: const char* (*pfnGetPhysicsInfoString)(const edict_t* pClient);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, NChar*> GetPhysicsInfoString;
    /// <remarks>
    /// Original: unsigned short (*pfnPrecacheEvent)(int type, const char* psz);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, NChar*, ushort> PrecacheEvent;
    /// <remarks>
    /// Original: void (*pfnPlaybackEvent)(int flags, const edict_t* pInvoker, unsigned short eventindex, float delay, const float* origin, const float* angles, float fparam1, float fparam2, int iparam1, int iparam2, int bparam1, int bparam2);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, edict_t*, ushort, float, float*, float*, float, float, int, int, int, int, void> PlaybackEvent;
    /// <remarks>
    /// Original: unsigned char* (*pfnSetFatPVS)(float* org);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, byte*> SetFatPVS;
    /// <remarks>
    /// Original: unsigned char* (*pfnSetFatPAS)(float* org);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<float*, byte*> SetFatPAS;
    /// <remarks>
    /// Original: int (*pfnCheckVisibility)(const edict_t* entity, unsigned char* pset);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, byte*, int> CheckVisibility;
    /// <remarks>
    /// Original: void (*pfnDeltaSetField)(struct delta_s* pFields, const char* fieldname);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<delta_s*, NChar*, void> DeltaSetField;
    /// <remarks>
    /// Original: void (*pfnDeltaUnsetField)(struct delta_s* pFields, const char* fieldname);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<delta_s*, NChar*, void> DeltaUnsetField;
    /// <remarks>
    /// Original: void (*pfnDeltaAddEncoder)(const char* name, void (*conditionalencode)(struct delta_s* pFields, const unsigned char* from, const unsigned char* to));
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, delegate* unmanaged[Cdecl]<delta_s*, byte*, byte*, void>, void> DeltaAddEncoder;
    /// <remarks>
    /// Original: int (*pfnGetCurrentPlayer)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> GetCurrentPlayer;
    /// <remarks>
    /// Original: int (*pfnCanSkipPlayer)(const edict_t* player);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, int> CanSkipPlayer;
    /// <remarks>
    /// Original: int (*pfnDeltaFindField)(struct delta_s* pFields, const char* fieldname);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<delta_s*, NChar*, int> DeltaFindField;
    /// <remarks>
    /// Original: void (*pfnDeltaSetFieldByIndex)(struct delta_s* pFields, int fieldNumber);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<delta_s*, int, void> DeltaSetFieldByIndex;
    /// <remarks>
    /// Original: void (*pfnDeltaUnsetFieldByIndex)(struct delta_s* pFields, int fieldNumber);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<delta_s*, int, void> DeltaUnsetFieldByIndex;
    /// <remarks>
    /// Original: void (*pfnSetGroupMask)(int mask, int op);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, void> SetGroupMask;
    /// <remarks>
    /// Original: int (*pfnCreateInstancedBaseline)(int classname, struct entity_state_s* baseline);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, entity_state_t*, int> CreateInstancedBaseline;
    /// <remarks>
    /// Original: void (*pfnCvar_DirectSet)(struct cvar_s* var, const char* value);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<cvar_t*, NChar*, void> Cvar_DirectSet;
    /// <summary>
    /// Forces the client and server to be running with the same version of the specified file
    /// ( e.g., a player model ).
    /// Calling this has no effect in single player
    /// </summary>
    /// <remarks>
    /// Original: void (*pfnForceUnmodified)(FORCE_TYPE type, float* mins, float* maxs, const char* filename);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<FORCE_TYPE, float*, float*, NChar*, void> ForceUnmodified;
    /// <remarks>
    /// Original: void (*pfnGetPlayerStats)(const edict_t* pClient, int* ping, int* packet_loss);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, int*, int*, void> GetPlayerStats;
    /// <remarks>
    /// Original: void (*pfnAddServerCommand)(const char* cmd_name, void (*function)());
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, delegate* unmanaged[Cdecl]<void>, void> AddServerCommand;
    /// <summary>
    /// For voice communications, set which clients hear eachother.
    /// NOTE: these functions take player entity indices (starting at 1).
    /// </summary>
    /// <remarks>
    /// Original: qboolean (*pfnVoice_GetClientListening)(int iReceiver, int iSender);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, qboolean> Voice_GetClientListening;
    /// <remarks>
    /// Original: qboolean (*pfnVoice_SetClientListening)(int iReceiver, int iSender, qboolean bListen);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, qboolean, qboolean> Voice_SetClientListening;
    /// <remarks>
    /// Original: const char* (*pfnGetPlayerAuthId)(edict_t* e);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, NChar*> GetPlayerAuthId;
    /// <summary>
    /// PSV: Added for CZ training map
    /// const char *(*pfnKeyNameForBinding)		( const char* pBinding );
    /// </summary>
    /// <remarks>
    /// Original: sequenceEntry_s* (*pfnSequenceGet)(const char* fileName, const char* entryName);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar*, sequenceEntry_s*> SequenceGet;
    /// <remarks>
    /// Original: sentenceEntry_s* (*pfnSequencePickSentence)(const char* groupName, int pickMethod, int* picked);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int, int*, sentenceEntry_s*> SequencePickSentence;
    /// <summary>
    /// LH: Give access to filesize via filesystem
    /// </summary>
    /// <remarks>
    /// Original: int (*pfnGetFileSize)(const char* filename);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int> GetFileSize;
    /// <remarks>
    /// Original: unsigned int (*pfnGetApproxWavePlayLen)(const char* filepath);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, uint> GetApproxWavePlayLen;
    /// <summary>
    /// MDC: Added for CZ career-mode
    /// </summary>
    /// <remarks>
    /// Original: int (*pfnIsCareerMatch)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> IsCareerMatch;
    /// <summary>
    /// BGC: return the number of characters of the localized string referenced by using "label"
    /// </summary>
    /// <remarks>
    /// Original: int (*pfnGetLocalizedStringLength)(const char* label);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, int> GetLocalizedStringLength;
    /// <summary>
    /// BGC: added to facilitate persistent storage of tutor message decay values for
    /// different career game profiles.  Also needs to persist regardless of mp.dll being
    /// destroyed and recreated.
    /// </summary>
    /// <remarks>
    /// Original: void (*pfnRegisterTutorMessageShown)(int mid);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, void> RegisterTutorMessageShown;
    /// <remarks>
    /// Original: int (*pfnGetTimesTutorMessageShown)(int mid);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int> GetTimesTutorMessageShown;
    /// <remarks>
    /// Original: void (*ProcessTutorMessageDecayBuffer)(int* buffer, int bufferLength);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int*, int, void> ProcessTutorMessageDecayBuffer;
    /// <remarks>
    /// Original: void (*ConstructTutorMessageDecayBuffer)(int* buffer, int bufferLength);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int*, int, void> ConstructTutorMessageDecayBuffer;
    /// <remarks>
    /// Original: void (*ResetTutorMessageDecayData)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> ResetTutorMessageDecayData;
    /// <remarks>
    /// Original: void (*pfnQueryClientCvarValue)(const edict_t* player, const char* cvarName);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, NChar*, void> QueryClientCvarValue;
    /// <remarks>
    /// Original: void (*pfnQueryClientCvarValue2)(const edict_t* player, const char* cvarName, int requestID);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, NChar*, int, void> QueryClientCvarValue2;
    /// <remarks>
    /// Original: int (*pfnCheckParm)(const char* pchCmdLineToken, const char** ppnext);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar**, int> CheckParm;
    /// <remarks>
    /// Original: edict_t* (*pfnPEntityOfEntIndexAllEntities)(int iEntIndex);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, edict_t*> PEntityOfEntIndexAllEntities;
}

