// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct { // Initialize/shutdown the game (one-time call after loading of game .dll ) void (*pfnGameInit)(); int (*pfnSpawn)(edict_t* pent); void (*pfnThink)(edict_t* pent); void (*pfnUse)(edict_t* pentUsed, edict_t* pentOther); v...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct ServerExportFuncs
{
    /// <summary>
    /// Initialize/shutdown the game (one-time call after loading of game .dll )
    /// </summary>
    /// <remarks>
    /// Original: void (*pfnGameInit)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> GameDLLInit;
    /// <remarks>
    /// Original: int (*pfnSpawn)(edict_t* pent);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, int> DispatchSpawn;
    /// <remarks>
    /// Original: void (*pfnThink)(edict_t* pent);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, void> DispatchThink;
    /// <remarks>
    /// Original: void (*pfnUse)(edict_t* pentUsed, edict_t* pentOther);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, edict_t*, void> DispatchUse;
    /// <remarks>
    /// Original: void (*pfnTouch)(edict_t* pentTouched, edict_t* pentOther);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, edict_t*, void> DispatchTouch;
    /// <remarks>
    /// Original: void (*pfnBlocked)(edict_t* pentBlocked, edict_t* pentOther);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, edict_t*, void> DispatchBlocked;
    /// <remarks>
    /// Original: void (*pfnKeyValue)(edict_t* pentKeyvalue, KeyValueData* pkvd);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, KeyValueData*, void> DispatchKeyValue;
    /// <remarks>
    /// Original: void (*pfnSave)(edict_t* pent, SAVERESTOREDATA* pSaveData);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, SAVERESTOREDATA*, void> DispatchSave;
    /// <remarks>
    /// Original: int (*pfnRestore)(edict_t* pent, SAVERESTOREDATA* pSaveData, int globalEntity);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, SAVERESTOREDATA*, int, int> DispatchRestore;
    /// <remarks>
    /// Original: void (*pfnSetAbsBox)(edict_t* pent);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, void> DispatchObjectCollsionBox;
    /// <remarks>
    /// Original: void (*pfnSaveWriteFields)(SAVERESTOREDATA*, const char*, void*, TYPEDESCRIPTION*, int);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<SAVERESTOREDATA*, NChar*, void*, TYPEDESCRIPTION*, int, void> SaveWriteFields;
    /// <remarks>
    /// Original: void (*pfnSaveReadFields)(SAVERESTOREDATA*, const char*, void*, TYPEDESCRIPTION*, int);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<SAVERESTOREDATA*, NChar*, void*, TYPEDESCRIPTION*, int, void> SaveReadFields;
    /// <remarks>
    /// Original: void (*pfnSaveGlobalState)(SAVERESTOREDATA*);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<SAVERESTOREDATA*, void> SaveGlobalState;
    /// <remarks>
    /// Original: void (*pfnRestoreGlobalState)(SAVERESTOREDATA*);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<SAVERESTOREDATA*, void> RestoreGlobalState;
    /// <remarks>
    /// Original: void (*pfnResetGlobalState)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> ResetGlobalState;
    /// <remarks>
    /// Original: qboolean (*pfnClientConnect)(edict_t* pEntity, const char* pszName, const char* pszAddress, char szRejectReason[128]);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, NChar*, NChar*, NChar*, qboolean> ClientConnect;
    /// <remarks>
    /// Original: void (*pfnClientDisconnect)(edict_t* pEntity);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, void> ClientDisconnect;
    /// <remarks>
    /// Original: void (*pfnClientKill)(edict_t* pEntity);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, void> ClientKill;
    /// <remarks>
    /// Original: void (*pfnClientPutInServer)(edict_t* pEntity);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, void> ClientPutInServer;
    /// <remarks>
    /// Original: void (*pfnClientCommand)(edict_t* pEntity);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, void> ClientCommand;
    /// <remarks>
    /// Original: void (*pfnClientUserInfoChanged)(edict_t* pEntity, char* infobuffer);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, NChar*, void> ClientUserInfoChanged;
    /// <remarks>
    /// Original: void (*pfnServerActivate)(edict_t* pEdictList, int edictCount, int clientMax);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, int, int, void> ServerActivate;
    /// <remarks>
    /// Original: void (*pfnServerDeactivate)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> ServerDeactivate;
    /// <remarks>
    /// Original: void (*pfnPlayerPreThink)(edict_t* pEntity);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, void> PlayerPreThink;
    /// <remarks>
    /// Original: void (*pfnPlayerPostThink)(edict_t* pEntity);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, void> PlayerPostThink;
    /// <remarks>
    /// Original: void (*pfnStartFrame)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> StartFrame;
    /// <remarks>
    /// Original: void (*pfnParmsNewLevel)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> ParmsNewLevel;
    /// <remarks>
    /// Original: void (*pfnParmsChangeLevel)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> ParmsChangeLevel;
    /// <summary>
    /// Returns string describing current .dll.  E.g., TeamFotrress 2, Half-Life
    /// </summary>
    /// <remarks>
    /// Original: const char* (*pfnGetGameDescription)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*> GetGameDescription;
    /// <summary>
    /// Notify dll about a player customization.
    /// </summary>
    /// <remarks>
    /// Original: void (*pfnPlayerCustomization)(edict_t* pEntity, customization_t* pCustom);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, customization_t*, void> PlayerCustomization;
    /// <summary>
    /// Spectator funcs
    /// </summary>
    /// <remarks>
    /// Original: void (*pfnSpectatorConnect)(edict_t* pEntity);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, void> SpectatorConnect;
    /// <remarks>
    /// Original: void (*pfnSpectatorDisconnect)(edict_t* pEntity);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, void> SpectatorDisconnect;
    /// <remarks>
    /// Original: void (*pfnSpectatorThink)(edict_t* pEntity);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, void> SpectatorThink;
    /// <summary>
    /// Notify game .dll that engine is going to shut down.  Allows mod authors to set a breakpoint.
    /// </summary>
    /// <remarks>
    /// Original: void (*pfnSys_Error)(const char* error_string);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, void> Sys_Error;
    /// <remarks>
    /// Original: void (*pfnPM_Move)(struct playermove_s* ppmove, qboolean server);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<playermove_t*, qboolean, void> PM_Move;
    /// <remarks>
    /// Original: void (*pfnPM_Init)(struct playermove_s* ppmove);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<playermove_t*, void> PM_Init;
    /// <remarks>
    /// Original: char (*pfnPM_FindTextureType)(const char* name);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<NChar*, NChar> PM_FindTextureType;
    /// <remarks>
    /// Original: void (*pfnSetupVisibility)(struct edict_s* pViewEntity, struct edict_s* pClient, unsigned char** pvs, unsigned char** pas);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, edict_t*, byte**, byte**, void> SetupVisibility;
    /// <remarks>
    /// Original: void (*pfnUpdateClientData)(const struct edict_s* ent, int sendweapons, struct clientdata_s* cd);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, int, clientdata_t*, void> UpdateClientData;
    /// <remarks>
    /// Original: int (*pfnAddToFullPack)(struct entity_state_s* state, int e, edict_t* ent, edict_t* host, int hostflags, int player, unsigned char* pSet);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<entity_state_t*, int, edict_t*, edict_t*, int, int, byte*, int> AddToFullPack;
    /// <remarks>
    /// Original: void (*pfnCreateBaseline)(int player, int eindex, struct entity_state_s* baseline, struct edict_s* entity, int playermodelindex, Vector* player_mins, Vector* player_maxs);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, int, entity_state_t*, edict_t*, int, Vector3*, Vector3*, void> CreateBaseline;
    /// <remarks>
    /// Original: void (*pfnRegisterEncoders)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> RegisterEncoders;
    /// <remarks>
    /// Original: int (*pfnGetWeaponData)(struct edict_s* player, struct weapon_data_s* info);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, weapon_data_t*, int> GetWeaponData;
    /// <remarks>
    /// Original: void (*pfnCmdStart)(const edict_t* player, const struct usercmd_s* cmd, unsigned int random_seed);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, usercmd_t*, uint, void> CmdStart;
    /// <remarks>
    /// Original: void (*pfnCmdEnd)(const edict_t* player);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, void> CmdEnd;
    /// <summary>
    /// Return 1 if the packet is valid.  Set response_buffer_size if you want to send a response packet.  Incoming, it holds the max
    /// size of the response_buffer, so you must zero it out if you choose not to respond.
    /// </summary>
    /// <remarks>
    /// Original: int (*pfnConnectionlessPacket)(const struct netadr_s* net_from, const char* args, char* response_buffer, int* response_buffer_size);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<netadr_t*, NChar*, NChar*, int*, int> ConnectionlessPacket;
    /// <summary>
    /// Enumerates player hulls.  Returns 0 if the hull number doesn't exist, 1 otherwise
    /// </summary>
    /// <remarks>
    /// Original: int (*pfnGetHullBounds)(int hullnumber, float* mins, float* maxs);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int, float*, float*, int> GetHullBounds;
    /// <summary>
    /// Create baselines for certain "unplaced" items.
    /// </summary>
    /// <remarks>
    /// Original: void (*pfnCreateInstancedBaselines)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> CreateInstancedBaselines;
    /// <summary>
    /// One of the pfnForceUnmodified files failed the consistency check for the specified player
    /// Return 0 to allow the client to continue, 1 to force immediate disconnection ( with an optional disconnect message of up to 256 characters )
    /// </summary>
    /// <remarks>
    /// Original: int (*pfnInconsistentFile)(const struct edict_s* player, const char* filename, char* disconnect_message);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, NChar*, NChar*, int> InconsistentFile;
    /// <summary>
    /// The game .dll should return 1 if lag compensation should be allowed ( could also just set
    /// the sv_unlag cvar.
    /// Most games right now should return 0, until client-side weapon prediction code is written
    /// and tested for them.
    /// </summary>
    /// <remarks>
    /// Original: int (*pfnAllowLagCompensation)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<int> AllowLagCompensation;
}

