// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct { // Called right before the object's memory is freed. // Calls its destructor. void (*pfnOnFreeEntPrivateData)(edict_t* pEnt); void (*pfnGameShutdown)(); int (*pfnShouldCollide)(edict_t* pentTouched, edict_t* pentOther); ...
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct ServerNewExportFuncs
{
    /// <summary>
    /// Called right before the object's memory is freed.
    /// Calls its destructor.
    /// </summary>
    /// <remarks>
    /// Original: void (*pfnOnFreeEntPrivateData)(edict_t* pEnt);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, void> OnFreeEntPrivateData;
    /// <remarks>
    /// Original: void (*pfnGameShutdown)();
    /// </remarks>
    public delegate* unmanaged[Cdecl]<void> GameDLLShutdown;
    /// <remarks>
    /// Original: int (*pfnShouldCollide)(edict_t* pentTouched, edict_t* pentOther);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, edict_t*, int> ShouldCollide;
    /// <remarks>
    /// Original: void (*pfnCvarValue)(const edict_t* pEnt, const char* value);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, NChar*, void> CvarValue;
    /// <remarks>
    /// Original: void (*pfnCvarValue2)(const edict_t* pEnt, int requestID, const char* cvarName, const char* value);
    /// </remarks>
    public delegate* unmanaged[Cdecl]<edict_t*, int, NChar*, NChar*, void> CvarValue2;
}

