// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using GoldsrcFramework.LinearMath;
using NativeInterop;

namespace GoldsrcFramework.Engine.Native;

/// <remarks>
/// Original: typedef struct kbutton_s { int down[2]; // key nums holding it down int state;	 // low bit is down state } kbutton_t;
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct kbutton_t
{
    /// <summary>
    /// key nums holding it down
    /// </summary>
    /// <remarks>
    /// Original: int down[2]; // key nums holding it down
    /// </remarks>
    public InlineArray2<int> down;
    /// <summary>
    /// low bit is down state
    /// </summary>
    /// <remarks>
    /// Original: int state;	 // low bit is down state
    /// </remarks>
    public int state;
}

